// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protos/perfetto/metrics/android/android_garbage_collection_stats.proto
// Protobuf C++ Version: 7.34.0

#ifndef protos_2fperfetto_2fmetrics_2fandroid_2fandroid_5fgarbage_5fcollection_5fstats_2eproto_2epb_2eh
#define protos_2fperfetto_2fmetrics_2fandroid_2fandroid_5fgarbage_5fcollection_5fstats_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

// clang-format off
#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 7034000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "protos/perfetto/metrics/android/process_metadata.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_protos_2fperfetto_2fmetrics_2fandroid_2fandroid_5fgarbage_5fcollection_5fstats_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_protos_2fperfetto_2fmetrics_2fandroid_2fandroid_5fgarbage_5fcollection_5fstats_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_protos_2fperfetto_2fmetrics_2fandroid_2fandroid_5fgarbage_5fcollection_5fstats_2eproto;
}  // extern "C"
namespace perfetto {
namespace protos {
class AndroidGarbageCollectionStats;
struct AndroidGarbageCollectionStatsDefaultTypeInternal;
extern AndroidGarbageCollectionStatsDefaultTypeInternal _AndroidGarbageCollectionStats_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull AndroidGarbageCollectionStats_class_data_;
class AndroidGarbageCollectionStats_ProcessStats;
struct AndroidGarbageCollectionStats_ProcessStatsDefaultTypeInternal;
extern AndroidGarbageCollectionStats_ProcessStatsDefaultTypeInternal _AndroidGarbageCollectionStats_ProcessStats_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull AndroidGarbageCollectionStats_ProcessStats_class_data_;
}  // namespace protos
}  // namespace perfetto
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace perfetto {
namespace protos {

// ===================================================================


// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED AndroidGarbageCollectionStats_ProcessStats final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:perfetto.protos.AndroidGarbageCollectionStats.ProcessStats) */ {
 public:
  inline AndroidGarbageCollectionStats_ProcessStats() : AndroidGarbageCollectionStats_ProcessStats(nullptr) {}
  ~AndroidGarbageCollectionStats_ProcessStats() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(AndroidGarbageCollectionStats_ProcessStats* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(AndroidGarbageCollectionStats_ProcessStats));
  }
#endif

  template <typename = void>
  explicit constexpr AndroidGarbageCollectionStats_ProcessStats(::google::protobuf::internal::ConstantInitialized);

  inline AndroidGarbageCollectionStats_ProcessStats(const AndroidGarbageCollectionStats_ProcessStats& from) : AndroidGarbageCollectionStats_ProcessStats(nullptr, from) {}
  inline AndroidGarbageCollectionStats_ProcessStats(AndroidGarbageCollectionStats_ProcessStats&& from) noexcept
      : AndroidGarbageCollectionStats_ProcessStats(nullptr, ::std::move(from)) {}
  inline AndroidGarbageCollectionStats_ProcessStats& operator=(const AndroidGarbageCollectionStats_ProcessStats& from) {
    CopyFrom(from);
    return *this;
  }
  inline AndroidGarbageCollectionStats_ProcessStats& operator=(AndroidGarbageCollectionStats_ProcessStats&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const AndroidGarbageCollectionStats_ProcessStats& default_instance() {
    return *reinterpret_cast<const AndroidGarbageCollectionStats_ProcessStats*>(
        &_AndroidGarbageCollectionStats_ProcessStats_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(AndroidGarbageCollectionStats_ProcessStats& a, AndroidGarbageCollectionStats_ProcessStats& b) { a.Swap(&b); }
  inline void Swap(AndroidGarbageCollectionStats_ProcessStats* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AndroidGarbageCollectionStats_ProcessStats* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] AndroidGarbageCollectionStats_ProcessStats* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<AndroidGarbageCollectionStats_ProcessStats>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const AndroidGarbageCollectionStats_ProcessStats& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const AndroidGarbageCollectionStats_ProcessStats& from) { AndroidGarbageCollectionStats_ProcessStats::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(AndroidGarbageCollectionStats_ProcessStats* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "perfetto.protos.AndroidGarbageCollectionStats.ProcessStats"; }

  explicit AndroidGarbageCollectionStats_ProcessStats(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  AndroidGarbageCollectionStats_ProcessStats(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const AndroidGarbageCollectionStats_ProcessStats& from);
  AndroidGarbageCollectionStats_ProcessStats(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, AndroidGarbageCollectionStats_ProcessStats&& from) noexcept
      : AndroidGarbageCollectionStats_ProcessStats(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kProcessFieldNumber = 1,
    kHeapSizeMbsFieldNumber = 2,
    kHeapSizeMbFieldNumber = 3,
    kHeapAllocatedMbFieldNumber = 4,
    kHeapAllocationRateFieldNumber = 5,
    kHeapLiveMbsFieldNumber = 6,
    kHeapTotalMbsFieldNumber = 7,
    kHeapUtilizationFieldNumber = 8,
    kGcRunningDurFieldNumber = 9,
    kGcRunningRateFieldNumber = 10,
    kGcRunningEfficiencyFieldNumber = 11,
    kGcDuringAndroidStartupDurFieldNumber = 12,
    kGcDuringAndroidStartupRateFieldNumber = 13,
    kGcDuringAndroidStartupEfficiencyFieldNumber = 14,
  };
  // optional .perfetto.protos.AndroidProcessMetadata process = 1;
  [[nodiscard]] bool has_process()
      const;
  void clear_process() ;
  [[nodiscard]] const ::perfetto::protos::AndroidProcessMetadata& process() const;
  [[nodiscard]] ::perfetto::protos::AndroidProcessMetadata* PROTOBUF_NULLABLE release_process();
  ::perfetto::protos::AndroidProcessMetadata* PROTOBUF_NONNULL mutable_process();
  void set_allocated_process(::perfetto::protos::AndroidProcessMetadata* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_process(::perfetto::protos::AndroidProcessMetadata* PROTOBUF_NULLABLE value);
  ::perfetto::protos::AndroidProcessMetadata* PROTOBUF_NULLABLE unsafe_arena_release_process();

  private:
  const ::perfetto::protos::AndroidProcessMetadata& _internal_process() const;
  ::perfetto::protos::AndroidProcessMetadata* PROTOBUF_NONNULL _internal_mutable_process();

  public:
  // optional double heap_size_mbs = 2;
  [[nodiscard]] bool has_heap_size_mbs()
      const;
  void clear_heap_size_mbs() ;
  [[nodiscard]] double heap_size_mbs() const;
  void set_heap_size_mbs(double value);

  private:
  double _internal_heap_size_mbs() const;
  void _internal_set_heap_size_mbs(double value);

  public:
  // optional double heap_size_mb = 3;
  [[nodiscard]] bool has_heap_size_mb()
      const;
  void clear_heap_size_mb() ;
  [[nodiscard]] double heap_size_mb() const;
  void set_heap_size_mb(double value);

  private:
  double _internal_heap_size_mb() const;
  void _internal_set_heap_size_mb(double value);

  public:
  // optional double heap_allocated_mb = 4;
  [[nodiscard]] bool has_heap_allocated_mb()
      const;
  void clear_heap_allocated_mb() ;
  [[nodiscard]] double heap_allocated_mb() const;
  void set_heap_allocated_mb(double value);

  private:
  double _internal_heap_allocated_mb() const;
  void _internal_set_heap_allocated_mb(double value);

  public:
  // optional double heap_allocation_rate = 5;
  [[nodiscard]] bool has_heap_allocation_rate()
      const;
  void clear_heap_allocation_rate() ;
  [[nodiscard]] double heap_allocation_rate() const;
  void set_heap_allocation_rate(double value);

  private:
  double _internal_heap_allocation_rate() const;
  void _internal_set_heap_allocation_rate(double value);

  public:
  // optional double heap_live_mbs = 6;
  [[nodiscard]] bool has_heap_live_mbs()
      const;
  void clear_heap_live_mbs() ;
  [[nodiscard]] double heap_live_mbs() const;
  void set_heap_live_mbs(double value);

  private:
  double _internal_heap_live_mbs() const;
  void _internal_set_heap_live_mbs(double value);

  public:
  // optional double heap_total_mbs = 7;
  [[nodiscard]] bool has_heap_total_mbs()
      const;
  void clear_heap_total_mbs() ;
  [[nodiscard]] double heap_total_mbs() const;
  void set_heap_total_mbs(double value);

  private:
  double _internal_heap_total_mbs() const;
  void _internal_set_heap_total_mbs(double value);

  public:
  // optional double heap_utilization = 8;
  [[nodiscard]] bool has_heap_utilization()
      const;
  void clear_heap_utilization() ;
  [[nodiscard]] double heap_utilization() const;
  void set_heap_utilization(double value);

  private:
  double _internal_heap_utilization() const;
  void _internal_set_heap_utilization(double value);

  public:
  // optional int64 gc_running_dur = 9;
  [[nodiscard]] bool has_gc_running_dur()
      const;
  void clear_gc_running_dur() ;
  [[nodiscard]] ::int64_t gc_running_dur() const;
  void set_gc_running_dur(::int64_t value);

  private:
  ::int64_t _internal_gc_running_dur() const;
  void _internal_set_gc_running_dur(::int64_t value);

  public:
  // optional double gc_running_rate = 10;
  [[nodiscard]] bool has_gc_running_rate()
      const;
  void clear_gc_running_rate() ;
  [[nodiscard]] double gc_running_rate() const;
  void set_gc_running_rate(double value);

  private:
  double _internal_gc_running_rate() const;
  void _internal_set_gc_running_rate(double value);

  public:
  // optional double gc_running_efficiency = 11;
  [[nodiscard]] bool has_gc_running_efficiency()
      const;
  void clear_gc_running_efficiency() ;
  [[nodiscard]] double gc_running_efficiency() const;
  void set_gc_running_efficiency(double value);

  private:
  double _internal_gc_running_efficiency() const;
  void _internal_set_gc_running_efficiency(double value);

  public:
  // optional int64 gc_during_android_startup_dur = 12;
  [[nodiscard]] bool has_gc_during_android_startup_dur()
      const;
  void clear_gc_during_android_startup_dur() ;
  [[nodiscard]] ::int64_t gc_during_android_startup_dur() const;
  void set_gc_during_android_startup_dur(::int64_t value);

  private:
  ::int64_t _internal_gc_during_android_startup_dur() const;
  void _internal_set_gc_during_android_startup_dur(::int64_t value);

  public:
  // optional double gc_during_android_startup_rate = 13;
  [[nodiscard]] bool has_gc_during_android_startup_rate()
      const;
  void clear_gc_during_android_startup_rate() ;
  [[nodiscard]] double gc_during_android_startup_rate() const;
  void set_gc_during_android_startup_rate(double value);

  private:
  double _internal_gc_during_android_startup_rate() const;
  void _internal_set_gc_during_android_startup_rate(double value);

  public:
  // optional double gc_during_android_startup_efficiency = 14;
  [[nodiscard]] bool has_gc_during_android_startup_efficiency()
      const;
  void clear_gc_during_android_startup_efficiency() ;
  [[nodiscard]] double gc_during_android_startup_efficiency() const;
  void set_gc_during_android_startup_efficiency(double value);

  private:
  double _internal_gc_during_android_startup_efficiency() const;
  void _internal_set_gc_during_android_startup_efficiency(double value);

  public:
  // @@protoc_insertion_point(class_scope:perfetto.protos.AndroidGarbageCollectionStats.ProcessStats)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<4, 14,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const AndroidGarbageCollectionStats_ProcessStats& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::perfetto::protos::AndroidProcessMetadata* PROTOBUF_NULLABLE process_;
    double heap_size_mbs_;
    double heap_size_mb_;
    double heap_allocated_mb_;
    double heap_allocation_rate_;
    double heap_live_mbs_;
    double heap_total_mbs_;
    double heap_utilization_;
    ::int64_t gc_running_dur_;
    double gc_running_rate_;
    double gc_running_efficiency_;
    ::int64_t gc_during_android_startup_dur_;
    double gc_during_android_startup_rate_;
    double gc_during_android_startup_efficiency_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_protos_2fperfetto_2fmetrics_2fandroid_2fandroid_5fgarbage_5fcollection_5fstats_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull AndroidGarbageCollectionStats_ProcessStats_class_data_;
// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED AndroidGarbageCollectionStats final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:perfetto.protos.AndroidGarbageCollectionStats) */ {
 public:
  inline AndroidGarbageCollectionStats() : AndroidGarbageCollectionStats(nullptr) {}
  ~AndroidGarbageCollectionStats() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(AndroidGarbageCollectionStats* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(AndroidGarbageCollectionStats));
  }
#endif

  template <typename = void>
  explicit constexpr AndroidGarbageCollectionStats(::google::protobuf::internal::ConstantInitialized);

  inline AndroidGarbageCollectionStats(const AndroidGarbageCollectionStats& from) : AndroidGarbageCollectionStats(nullptr, from) {}
  inline AndroidGarbageCollectionStats(AndroidGarbageCollectionStats&& from) noexcept
      : AndroidGarbageCollectionStats(nullptr, ::std::move(from)) {}
  inline AndroidGarbageCollectionStats& operator=(const AndroidGarbageCollectionStats& from) {
    CopyFrom(from);
    return *this;
  }
  inline AndroidGarbageCollectionStats& operator=(AndroidGarbageCollectionStats&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const AndroidGarbageCollectionStats& default_instance() {
    return *reinterpret_cast<const AndroidGarbageCollectionStats*>(
        &_AndroidGarbageCollectionStats_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(AndroidGarbageCollectionStats& a, AndroidGarbageCollectionStats& b) { a.Swap(&b); }
  inline void Swap(AndroidGarbageCollectionStats* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AndroidGarbageCollectionStats* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] AndroidGarbageCollectionStats* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<AndroidGarbageCollectionStats>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const AndroidGarbageCollectionStats& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const AndroidGarbageCollectionStats& from) { AndroidGarbageCollectionStats::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(AndroidGarbageCollectionStats* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "perfetto.protos.AndroidGarbageCollectionStats"; }

  explicit AndroidGarbageCollectionStats(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  AndroidGarbageCollectionStats(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const AndroidGarbageCollectionStats& from);
  AndroidGarbageCollectionStats(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, AndroidGarbageCollectionStats&& from) noexcept
      : AndroidGarbageCollectionStats(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using ProcessStats = AndroidGarbageCollectionStats_ProcessStats;

  // accessors -------------------------------------------------------
  enum : int {
    kProcessesFieldNumber = 17,
    kTsFieldNumber = 1,
    kDurFieldNumber = 2,
    kHeapSizeMbsFieldNumber = 3,
    kHeapSizeMbFieldNumber = 4,
    kHeapAllocatedMbFieldNumber = 5,
    kHeapAllocationRateFieldNumber = 6,
    kHeapLiveMbsFieldNumber = 7,
    kHeapTotalMbsFieldNumber = 8,
    kHeapUtilizationFieldNumber = 9,
    kGcRunningDurFieldNumber = 10,
    kGcRunningRateFieldNumber = 11,
    kGcRunningEfficiencyFieldNumber = 12,
    kGcDuringAndroidStartupDurFieldNumber = 13,
    kTotalAndroidStartupDurFieldNumber = 14,
    kGcDuringAndroidStartupRateFieldNumber = 15,
    kGcDuringAndroidStartupEfficiencyFieldNumber = 16,
  };
  // repeated .perfetto.protos.AndroidGarbageCollectionStats.ProcessStats processes = 17;
  [[nodiscard]] int processes_size()
      const;
  private:
  int _internal_processes_size() const;

  public:
  void clear_processes() ;
  [[nodiscard]] ::perfetto::protos::AndroidGarbageCollectionStats_ProcessStats* PROTOBUF_NONNULL mutable_processes(int index);
  [[nodiscard]] ::google::protobuf::RepeatedPtrField<::perfetto::protos::AndroidGarbageCollectionStats_ProcessStats>* PROTOBUF_NONNULL
  mutable_processes();

  private:
  const ::google::protobuf::RepeatedPtrField<::perfetto::protos::AndroidGarbageCollectionStats_ProcessStats>& _internal_processes() const;
  ::google::protobuf::RepeatedPtrField<::perfetto::protos::AndroidGarbageCollectionStats_ProcessStats>* PROTOBUF_NONNULL _internal_mutable_processes();
  public:
  [[nodiscard]] const ::perfetto::protos::AndroidGarbageCollectionStats_ProcessStats& processes(int index) const;
  ::perfetto::protos::AndroidGarbageCollectionStats_ProcessStats* PROTOBUF_NONNULL add_processes();
  [[nodiscard]] const ::google::protobuf::RepeatedPtrField<::perfetto::protos::AndroidGarbageCollectionStats_ProcessStats>& processes()
      const;
  // optional int64 ts = 1;
  [[nodiscard]] bool has_ts()
      const;
  void clear_ts() ;
  [[nodiscard]] ::int64_t ts() const;
  void set_ts(::int64_t value);

  private:
  ::int64_t _internal_ts() const;
  void _internal_set_ts(::int64_t value);

  public:
  // optional int64 dur = 2;
  [[nodiscard]] bool has_dur()
      const;
  void clear_dur() ;
  [[nodiscard]] ::int64_t dur() const;
  void set_dur(::int64_t value);

  private:
  ::int64_t _internal_dur() const;
  void _internal_set_dur(::int64_t value);

  public:
  // optional double heap_size_mbs = 3;
  [[nodiscard]] bool has_heap_size_mbs()
      const;
  void clear_heap_size_mbs() ;
  [[nodiscard]] double heap_size_mbs() const;
  void set_heap_size_mbs(double value);

  private:
  double _internal_heap_size_mbs() const;
  void _internal_set_heap_size_mbs(double value);

  public:
  // optional double heap_size_mb = 4;
  [[nodiscard]] bool has_heap_size_mb()
      const;
  void clear_heap_size_mb() ;
  [[nodiscard]] double heap_size_mb() const;
  void set_heap_size_mb(double value);

  private:
  double _internal_heap_size_mb() const;
  void _internal_set_heap_size_mb(double value);

  public:
  // optional double heap_allocated_mb = 5;
  [[nodiscard]] bool has_heap_allocated_mb()
      const;
  void clear_heap_allocated_mb() ;
  [[nodiscard]] double heap_allocated_mb() const;
  void set_heap_allocated_mb(double value);

  private:
  double _internal_heap_allocated_mb() const;
  void _internal_set_heap_allocated_mb(double value);

  public:
  // optional double heap_allocation_rate = 6;
  [[nodiscard]] bool has_heap_allocation_rate()
      const;
  void clear_heap_allocation_rate() ;
  [[nodiscard]] double heap_allocation_rate() const;
  void set_heap_allocation_rate(double value);

  private:
  double _internal_heap_allocation_rate() const;
  void _internal_set_heap_allocation_rate(double value);

  public:
  // optional double heap_live_mbs = 7;
  [[nodiscard]] bool has_heap_live_mbs()
      const;
  void clear_heap_live_mbs() ;
  [[nodiscard]] double heap_live_mbs() const;
  void set_heap_live_mbs(double value);

  private:
  double _internal_heap_live_mbs() const;
  void _internal_set_heap_live_mbs(double value);

  public:
  // optional double heap_total_mbs = 8;
  [[nodiscard]] bool has_heap_total_mbs()
      const;
  void clear_heap_total_mbs() ;
  [[nodiscard]] double heap_total_mbs() const;
  void set_heap_total_mbs(double value);

  private:
  double _internal_heap_total_mbs() const;
  void _internal_set_heap_total_mbs(double value);

  public:
  // optional double heap_utilization = 9;
  [[nodiscard]] bool has_heap_utilization()
      const;
  void clear_heap_utilization() ;
  [[nodiscard]] double heap_utilization() const;
  void set_heap_utilization(double value);

  private:
  double _internal_heap_utilization() const;
  void _internal_set_heap_utilization(double value);

  public:
  // optional int64 gc_running_dur = 10;
  [[nodiscard]] bool has_gc_running_dur()
      const;
  void clear_gc_running_dur() ;
  [[nodiscard]] ::int64_t gc_running_dur() const;
  void set_gc_running_dur(::int64_t value);

  private:
  ::int64_t _internal_gc_running_dur() const;
  void _internal_set_gc_running_dur(::int64_t value);

  public:
  // optional double gc_running_rate = 11;
  [[nodiscard]] bool has_gc_running_rate()
      const;
  void clear_gc_running_rate() ;
  [[nodiscard]] double gc_running_rate() const;
  void set_gc_running_rate(double value);

  private:
  double _internal_gc_running_rate() const;
  void _internal_set_gc_running_rate(double value);

  public:
  // optional double gc_running_efficiency = 12;
  [[nodiscard]] bool has_gc_running_efficiency()
      const;
  void clear_gc_running_efficiency() ;
  [[nodiscard]] double gc_running_efficiency() const;
  void set_gc_running_efficiency(double value);

  private:
  double _internal_gc_running_efficiency() const;
  void _internal_set_gc_running_efficiency(double value);

  public:
  // optional int64 gc_during_android_startup_dur = 13;
  [[nodiscard]] bool has_gc_during_android_startup_dur()
      const;
  void clear_gc_during_android_startup_dur() ;
  [[nodiscard]] ::int64_t gc_during_android_startup_dur() const;
  void set_gc_during_android_startup_dur(::int64_t value);

  private:
  ::int64_t _internal_gc_during_android_startup_dur() const;
  void _internal_set_gc_during_android_startup_dur(::int64_t value);

  public:
  // optional int64 total_android_startup_dur = 14;
  [[nodiscard]] bool has_total_android_startup_dur()
      const;
  void clear_total_android_startup_dur() ;
  [[nodiscard]] ::int64_t total_android_startup_dur() const;
  void set_total_android_startup_dur(::int64_t value);

  private:
  ::int64_t _internal_total_android_startup_dur() const;
  void _internal_set_total_android_startup_dur(::int64_t value);

  public:
  // optional double gc_during_android_startup_rate = 15;
  [[nodiscard]] bool has_gc_during_android_startup_rate()
      const;
  void clear_gc_during_android_startup_rate() ;
  [[nodiscard]] double gc_during_android_startup_rate() const;
  void set_gc_during_android_startup_rate(double value);

  private:
  double _internal_gc_during_android_startup_rate() const;
  void _internal_set_gc_during_android_startup_rate(double value);

  public:
  // optional double gc_during_android_startup_efficiency = 16;
  [[nodiscard]] bool has_gc_during_android_startup_efficiency()
      const;
  void clear_gc_during_android_startup_efficiency() ;
  [[nodiscard]] double gc_during_android_startup_efficiency() const;
  void set_gc_during_android_startup_efficiency(double value);

  private:
  double _internal_gc_during_android_startup_efficiency() const;
  void _internal_set_gc_during_android_startup_efficiency(double value);

  public:
  // @@protoc_insertion_point(class_scope:perfetto.protos.AndroidGarbageCollectionStats)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<5, 17,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const AndroidGarbageCollectionStats& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::perfetto::protos::AndroidGarbageCollectionStats_ProcessStats > processes_;
    ::int64_t ts_;
    ::int64_t dur_;
    double heap_size_mbs_;
    double heap_size_mb_;
    double heap_allocated_mb_;
    double heap_allocation_rate_;
    double heap_live_mbs_;
    double heap_total_mbs_;
    double heap_utilization_;
    ::int64_t gc_running_dur_;
    double gc_running_rate_;
    double gc_running_efficiency_;
    ::int64_t gc_during_android_startup_dur_;
    ::int64_t total_android_startup_dur_;
    double gc_during_android_startup_rate_;
    double gc_during_android_startup_efficiency_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_protos_2fperfetto_2fmetrics_2fandroid_2fandroid_5fgarbage_5fcollection_5fstats_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull AndroidGarbageCollectionStats_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// AndroidGarbageCollectionStats_ProcessStats

// optional .perfetto.protos.AndroidProcessMetadata process = 1;
inline bool AndroidGarbageCollectionStats_ProcessStats::has_process() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  PROTOBUF_ASSUME(!value || _impl_.process_ != nullptr);
  return value;
}
inline const ::perfetto::protos::AndroidProcessMetadata& AndroidGarbageCollectionStats_ProcessStats::_internal_process() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::perfetto::protos::AndroidProcessMetadata* p = _impl_.process_;
  return p != nullptr ? *p : reinterpret_cast<const ::perfetto::protos::AndroidProcessMetadata&>(::perfetto::protos::_AndroidProcessMetadata_default_instance_);
}
inline const ::perfetto::protos::AndroidProcessMetadata& AndroidGarbageCollectionStats_ProcessStats::process() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:perfetto.protos.AndroidGarbageCollectionStats.ProcessStats.process)
  return _internal_process();
}
inline void AndroidGarbageCollectionStats_ProcessStats::unsafe_arena_set_allocated_process(
    ::perfetto::protos::AndroidProcessMetadata* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.process_);
  }
  _impl_.process_ = reinterpret_cast<::perfetto::protos::AndroidProcessMetadata*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:perfetto.protos.AndroidGarbageCollectionStats.ProcessStats.process)
}
inline ::perfetto::protos::AndroidProcessMetadata* PROTOBUF_NULLABLE AndroidGarbageCollectionStats_ProcessStats::release_process() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::perfetto::protos::AndroidProcessMetadata* released = _impl_.process_;
  _impl_.process_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::perfetto::protos::AndroidProcessMetadata* PROTOBUF_NULLABLE AndroidGarbageCollectionStats_ProcessStats::unsafe_arena_release_process() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:perfetto.protos.AndroidGarbageCollectionStats.ProcessStats.process)

  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::perfetto::protos::AndroidProcessMetadata* temp = _impl_.process_;
  _impl_.process_ = nullptr;
  return temp;
}
inline ::perfetto::protos::AndroidProcessMetadata* PROTOBUF_NONNULL AndroidGarbageCollectionStats_ProcessStats::_internal_mutable_process() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.process_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::perfetto::protos::AndroidProcessMetadata>(GetArena());
    _impl_.process_ = reinterpret_cast<::perfetto::protos::AndroidProcessMetadata*>(p);
  }
  return _impl_.process_;
}
inline ::perfetto::protos::AndroidProcessMetadata* PROTOBUF_NONNULL AndroidGarbageCollectionStats_ProcessStats::mutable_process()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::perfetto::protos::AndroidProcessMetadata* _msg = _internal_mutable_process();
  // @@protoc_insertion_point(field_mutable:perfetto.protos.AndroidGarbageCollectionStats.ProcessStats.process)
  return _msg;
}
inline void AndroidGarbageCollectionStats_ProcessStats::set_allocated_process(::perfetto::protos::AndroidProcessMetadata* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.process_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }

  _impl_.process_ = reinterpret_cast<::perfetto::protos::AndroidProcessMetadata*>(value);
  // @@protoc_insertion_point(field_set_allocated:perfetto.protos.AndroidGarbageCollectionStats.ProcessStats.process)
}

// optional double heap_size_mbs = 2;
inline bool AndroidGarbageCollectionStats_ProcessStats::has_heap_size_mbs() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  return value;
}
inline void AndroidGarbageCollectionStats_ProcessStats::clear_heap_size_mbs() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.heap_size_mbs_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline double AndroidGarbageCollectionStats_ProcessStats::heap_size_mbs() const {
  // @@protoc_insertion_point(field_get:perfetto.protos.AndroidGarbageCollectionStats.ProcessStats.heap_size_mbs)
  return _internal_heap_size_mbs();
}
inline void AndroidGarbageCollectionStats_ProcessStats::set_heap_size_mbs(double value) {
  _internal_set_heap_size_mbs(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:perfetto.protos.AndroidGarbageCollectionStats.ProcessStats.heap_size_mbs)
}
inline double AndroidGarbageCollectionStats_ProcessStats::_internal_heap_size_mbs() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.heap_size_mbs_;
}
inline void AndroidGarbageCollectionStats_ProcessStats::_internal_set_heap_size_mbs(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.heap_size_mbs_ = value;
}

// optional double heap_size_mb = 3;
inline bool AndroidGarbageCollectionStats_ProcessStats::has_heap_size_mb() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000004U);
  return value;
}
inline void AndroidGarbageCollectionStats_ProcessStats::clear_heap_size_mb() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.heap_size_mb_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline double AndroidGarbageCollectionStats_ProcessStats::heap_size_mb() const {
  // @@protoc_insertion_point(field_get:perfetto.protos.AndroidGarbageCollectionStats.ProcessStats.heap_size_mb)
  return _internal_heap_size_mb();
}
inline void AndroidGarbageCollectionStats_ProcessStats::set_heap_size_mb(double value) {
  _internal_set_heap_size_mb(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:perfetto.protos.AndroidGarbageCollectionStats.ProcessStats.heap_size_mb)
}
inline double AndroidGarbageCollectionStats_ProcessStats::_internal_heap_size_mb() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.heap_size_mb_;
}
inline void AndroidGarbageCollectionStats_ProcessStats::_internal_set_heap_size_mb(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.heap_size_mb_ = value;
}

// optional double heap_allocated_mb = 4;
inline bool AndroidGarbageCollectionStats_ProcessStats::has_heap_allocated_mb() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000008U);
  return value;
}
inline void AndroidGarbageCollectionStats_ProcessStats::clear_heap_allocated_mb() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.heap_allocated_mb_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline double AndroidGarbageCollectionStats_ProcessStats::heap_allocated_mb() const {
  // @@protoc_insertion_point(field_get:perfetto.protos.AndroidGarbageCollectionStats.ProcessStats.heap_allocated_mb)
  return _internal_heap_allocated_mb();
}
inline void AndroidGarbageCollectionStats_ProcessStats::set_heap_allocated_mb(double value) {
  _internal_set_heap_allocated_mb(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:perfetto.protos.AndroidGarbageCollectionStats.ProcessStats.heap_allocated_mb)
}
inline double AndroidGarbageCollectionStats_ProcessStats::_internal_heap_allocated_mb() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.heap_allocated_mb_;
}
inline void AndroidGarbageCollectionStats_ProcessStats::_internal_set_heap_allocated_mb(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.heap_allocated_mb_ = value;
}

// optional double heap_allocation_rate = 5;
inline bool AndroidGarbageCollectionStats_ProcessStats::has_heap_allocation_rate() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000010U);
  return value;
}
inline void AndroidGarbageCollectionStats_ProcessStats::clear_heap_allocation_rate() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.heap_allocation_rate_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline double AndroidGarbageCollectionStats_ProcessStats::heap_allocation_rate() const {
  // @@protoc_insertion_point(field_get:perfetto.protos.AndroidGarbageCollectionStats.ProcessStats.heap_allocation_rate)
  return _internal_heap_allocation_rate();
}
inline void AndroidGarbageCollectionStats_ProcessStats::set_heap_allocation_rate(double value) {
  _internal_set_heap_allocation_rate(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:perfetto.protos.AndroidGarbageCollectionStats.ProcessStats.heap_allocation_rate)
}
inline double AndroidGarbageCollectionStats_ProcessStats::_internal_heap_allocation_rate() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.heap_allocation_rate_;
}
inline void AndroidGarbageCollectionStats_ProcessStats::_internal_set_heap_allocation_rate(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.heap_allocation_rate_ = value;
}

// optional double heap_live_mbs = 6;
inline bool AndroidGarbageCollectionStats_ProcessStats::has_heap_live_mbs() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000020U);
  return value;
}
inline void AndroidGarbageCollectionStats_ProcessStats::clear_heap_live_mbs() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.heap_live_mbs_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000020U);
}
inline double AndroidGarbageCollectionStats_ProcessStats::heap_live_mbs() const {
  // @@protoc_insertion_point(field_get:perfetto.protos.AndroidGarbageCollectionStats.ProcessStats.heap_live_mbs)
  return _internal_heap_live_mbs();
}
inline void AndroidGarbageCollectionStats_ProcessStats::set_heap_live_mbs(double value) {
  _internal_set_heap_live_mbs(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  // @@protoc_insertion_point(field_set:perfetto.protos.AndroidGarbageCollectionStats.ProcessStats.heap_live_mbs)
}
inline double AndroidGarbageCollectionStats_ProcessStats::_internal_heap_live_mbs() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.heap_live_mbs_;
}
inline void AndroidGarbageCollectionStats_ProcessStats::_internal_set_heap_live_mbs(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.heap_live_mbs_ = value;
}

// optional double heap_total_mbs = 7;
inline bool AndroidGarbageCollectionStats_ProcessStats::has_heap_total_mbs() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000040U);
  return value;
}
inline void AndroidGarbageCollectionStats_ProcessStats::clear_heap_total_mbs() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.heap_total_mbs_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000040U);
}
inline double AndroidGarbageCollectionStats_ProcessStats::heap_total_mbs() const {
  // @@protoc_insertion_point(field_get:perfetto.protos.AndroidGarbageCollectionStats.ProcessStats.heap_total_mbs)
  return _internal_heap_total_mbs();
}
inline void AndroidGarbageCollectionStats_ProcessStats::set_heap_total_mbs(double value) {
  _internal_set_heap_total_mbs(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000040U);
  // @@protoc_insertion_point(field_set:perfetto.protos.AndroidGarbageCollectionStats.ProcessStats.heap_total_mbs)
}
inline double AndroidGarbageCollectionStats_ProcessStats::_internal_heap_total_mbs() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.heap_total_mbs_;
}
inline void AndroidGarbageCollectionStats_ProcessStats::_internal_set_heap_total_mbs(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.heap_total_mbs_ = value;
}

// optional double heap_utilization = 8;
inline bool AndroidGarbageCollectionStats_ProcessStats::has_heap_utilization() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000080U);
  return value;
}
inline void AndroidGarbageCollectionStats_ProcessStats::clear_heap_utilization() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.heap_utilization_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000080U);
}
inline double AndroidGarbageCollectionStats_ProcessStats::heap_utilization() const {
  // @@protoc_insertion_point(field_get:perfetto.protos.AndroidGarbageCollectionStats.ProcessStats.heap_utilization)
  return _internal_heap_utilization();
}
inline void AndroidGarbageCollectionStats_ProcessStats::set_heap_utilization(double value) {
  _internal_set_heap_utilization(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000080U);
  // @@protoc_insertion_point(field_set:perfetto.protos.AndroidGarbageCollectionStats.ProcessStats.heap_utilization)
}
inline double AndroidGarbageCollectionStats_ProcessStats::_internal_heap_utilization() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.heap_utilization_;
}
inline void AndroidGarbageCollectionStats_ProcessStats::_internal_set_heap_utilization(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.heap_utilization_ = value;
}

// optional int64 gc_running_dur = 9;
inline bool AndroidGarbageCollectionStats_ProcessStats::has_gc_running_dur() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000100U);
  return value;
}
inline void AndroidGarbageCollectionStats_ProcessStats::clear_gc_running_dur() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.gc_running_dur_ = ::int64_t{0};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000100U);
}
inline ::int64_t AndroidGarbageCollectionStats_ProcessStats::gc_running_dur() const {
  // @@protoc_insertion_point(field_get:perfetto.protos.AndroidGarbageCollectionStats.ProcessStats.gc_running_dur)
  return _internal_gc_running_dur();
}
inline void AndroidGarbageCollectionStats_ProcessStats::set_gc_running_dur(::int64_t value) {
  _internal_set_gc_running_dur(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000100U);
  // @@protoc_insertion_point(field_set:perfetto.protos.AndroidGarbageCollectionStats.ProcessStats.gc_running_dur)
}
inline ::int64_t AndroidGarbageCollectionStats_ProcessStats::_internal_gc_running_dur() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.gc_running_dur_;
}
inline void AndroidGarbageCollectionStats_ProcessStats::_internal_set_gc_running_dur(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.gc_running_dur_ = value;
}

// optional double gc_running_rate = 10;
inline bool AndroidGarbageCollectionStats_ProcessStats::has_gc_running_rate() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000200U);
  return value;
}
inline void AndroidGarbageCollectionStats_ProcessStats::clear_gc_running_rate() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.gc_running_rate_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000200U);
}
inline double AndroidGarbageCollectionStats_ProcessStats::gc_running_rate() const {
  // @@protoc_insertion_point(field_get:perfetto.protos.AndroidGarbageCollectionStats.ProcessStats.gc_running_rate)
  return _internal_gc_running_rate();
}
inline void AndroidGarbageCollectionStats_ProcessStats::set_gc_running_rate(double value) {
  _internal_set_gc_running_rate(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000200U);
  // @@protoc_insertion_point(field_set:perfetto.protos.AndroidGarbageCollectionStats.ProcessStats.gc_running_rate)
}
inline double AndroidGarbageCollectionStats_ProcessStats::_internal_gc_running_rate() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.gc_running_rate_;
}
inline void AndroidGarbageCollectionStats_ProcessStats::_internal_set_gc_running_rate(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.gc_running_rate_ = value;
}

// optional double gc_running_efficiency = 11;
inline bool AndroidGarbageCollectionStats_ProcessStats::has_gc_running_efficiency() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000400U);
  return value;
}
inline void AndroidGarbageCollectionStats_ProcessStats::clear_gc_running_efficiency() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.gc_running_efficiency_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000400U);
}
inline double AndroidGarbageCollectionStats_ProcessStats::gc_running_efficiency() const {
  // @@protoc_insertion_point(field_get:perfetto.protos.AndroidGarbageCollectionStats.ProcessStats.gc_running_efficiency)
  return _internal_gc_running_efficiency();
}
inline void AndroidGarbageCollectionStats_ProcessStats::set_gc_running_efficiency(double value) {
  _internal_set_gc_running_efficiency(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000400U);
  // @@protoc_insertion_point(field_set:perfetto.protos.AndroidGarbageCollectionStats.ProcessStats.gc_running_efficiency)
}
inline double AndroidGarbageCollectionStats_ProcessStats::_internal_gc_running_efficiency() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.gc_running_efficiency_;
}
inline void AndroidGarbageCollectionStats_ProcessStats::_internal_set_gc_running_efficiency(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.gc_running_efficiency_ = value;
}

// optional int64 gc_during_android_startup_dur = 12;
inline bool AndroidGarbageCollectionStats_ProcessStats::has_gc_during_android_startup_dur() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000800U);
  return value;
}
inline void AndroidGarbageCollectionStats_ProcessStats::clear_gc_during_android_startup_dur() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.gc_during_android_startup_dur_ = ::int64_t{0};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000800U);
}
inline ::int64_t AndroidGarbageCollectionStats_ProcessStats::gc_during_android_startup_dur() const {
  // @@protoc_insertion_point(field_get:perfetto.protos.AndroidGarbageCollectionStats.ProcessStats.gc_during_android_startup_dur)
  return _internal_gc_during_android_startup_dur();
}
inline void AndroidGarbageCollectionStats_ProcessStats::set_gc_during_android_startup_dur(::int64_t value) {
  _internal_set_gc_during_android_startup_dur(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000800U);
  // @@protoc_insertion_point(field_set:perfetto.protos.AndroidGarbageCollectionStats.ProcessStats.gc_during_android_startup_dur)
}
inline ::int64_t AndroidGarbageCollectionStats_ProcessStats::_internal_gc_during_android_startup_dur() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.gc_during_android_startup_dur_;
}
inline void AndroidGarbageCollectionStats_ProcessStats::_internal_set_gc_during_android_startup_dur(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.gc_during_android_startup_dur_ = value;
}

// optional double gc_during_android_startup_rate = 13;
inline bool AndroidGarbageCollectionStats_ProcessStats::has_gc_during_android_startup_rate() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00001000U);
  return value;
}
inline void AndroidGarbageCollectionStats_ProcessStats::clear_gc_during_android_startup_rate() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.gc_during_android_startup_rate_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00001000U);
}
inline double AndroidGarbageCollectionStats_ProcessStats::gc_during_android_startup_rate() const {
  // @@protoc_insertion_point(field_get:perfetto.protos.AndroidGarbageCollectionStats.ProcessStats.gc_during_android_startup_rate)
  return _internal_gc_during_android_startup_rate();
}
inline void AndroidGarbageCollectionStats_ProcessStats::set_gc_during_android_startup_rate(double value) {
  _internal_set_gc_during_android_startup_rate(value);
  SetHasBit(_impl_._has_bits_[0], 0x00001000U);
  // @@protoc_insertion_point(field_set:perfetto.protos.AndroidGarbageCollectionStats.ProcessStats.gc_during_android_startup_rate)
}
inline double AndroidGarbageCollectionStats_ProcessStats::_internal_gc_during_android_startup_rate() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.gc_during_android_startup_rate_;
}
inline void AndroidGarbageCollectionStats_ProcessStats::_internal_set_gc_during_android_startup_rate(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.gc_during_android_startup_rate_ = value;
}

// optional double gc_during_android_startup_efficiency = 14;
inline bool AndroidGarbageCollectionStats_ProcessStats::has_gc_during_android_startup_efficiency() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00002000U);
  return value;
}
inline void AndroidGarbageCollectionStats_ProcessStats::clear_gc_during_android_startup_efficiency() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.gc_during_android_startup_efficiency_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00002000U);
}
inline double AndroidGarbageCollectionStats_ProcessStats::gc_during_android_startup_efficiency() const {
  // @@protoc_insertion_point(field_get:perfetto.protos.AndroidGarbageCollectionStats.ProcessStats.gc_during_android_startup_efficiency)
  return _internal_gc_during_android_startup_efficiency();
}
inline void AndroidGarbageCollectionStats_ProcessStats::set_gc_during_android_startup_efficiency(double value) {
  _internal_set_gc_during_android_startup_efficiency(value);
  SetHasBit(_impl_._has_bits_[0], 0x00002000U);
  // @@protoc_insertion_point(field_set:perfetto.protos.AndroidGarbageCollectionStats.ProcessStats.gc_during_android_startup_efficiency)
}
inline double AndroidGarbageCollectionStats_ProcessStats::_internal_gc_during_android_startup_efficiency() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.gc_during_android_startup_efficiency_;
}
inline void AndroidGarbageCollectionStats_ProcessStats::_internal_set_gc_during_android_startup_efficiency(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.gc_during_android_startup_efficiency_ = value;
}

// -------------------------------------------------------------------

// AndroidGarbageCollectionStats

// optional int64 ts = 1;
inline bool AndroidGarbageCollectionStats::has_ts() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  return value;
}
inline void AndroidGarbageCollectionStats::clear_ts() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ts_ = ::int64_t{0};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::int64_t AndroidGarbageCollectionStats::ts() const {
  // @@protoc_insertion_point(field_get:perfetto.protos.AndroidGarbageCollectionStats.ts)
  return _internal_ts();
}
inline void AndroidGarbageCollectionStats::set_ts(::int64_t value) {
  _internal_set_ts(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:perfetto.protos.AndroidGarbageCollectionStats.ts)
}
inline ::int64_t AndroidGarbageCollectionStats::_internal_ts() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.ts_;
}
inline void AndroidGarbageCollectionStats::_internal_set_ts(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ts_ = value;
}

// optional int64 dur = 2;
inline bool AndroidGarbageCollectionStats::has_dur() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000004U);
  return value;
}
inline void AndroidGarbageCollectionStats::clear_dur() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.dur_ = ::int64_t{0};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::int64_t AndroidGarbageCollectionStats::dur() const {
  // @@protoc_insertion_point(field_get:perfetto.protos.AndroidGarbageCollectionStats.dur)
  return _internal_dur();
}
inline void AndroidGarbageCollectionStats::set_dur(::int64_t value) {
  _internal_set_dur(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:perfetto.protos.AndroidGarbageCollectionStats.dur)
}
inline ::int64_t AndroidGarbageCollectionStats::_internal_dur() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.dur_;
}
inline void AndroidGarbageCollectionStats::_internal_set_dur(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.dur_ = value;
}

// optional double heap_size_mbs = 3;
inline bool AndroidGarbageCollectionStats::has_heap_size_mbs() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000008U);
  return value;
}
inline void AndroidGarbageCollectionStats::clear_heap_size_mbs() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.heap_size_mbs_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline double AndroidGarbageCollectionStats::heap_size_mbs() const {
  // @@protoc_insertion_point(field_get:perfetto.protos.AndroidGarbageCollectionStats.heap_size_mbs)
  return _internal_heap_size_mbs();
}
inline void AndroidGarbageCollectionStats::set_heap_size_mbs(double value) {
  _internal_set_heap_size_mbs(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:perfetto.protos.AndroidGarbageCollectionStats.heap_size_mbs)
}
inline double AndroidGarbageCollectionStats::_internal_heap_size_mbs() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.heap_size_mbs_;
}
inline void AndroidGarbageCollectionStats::_internal_set_heap_size_mbs(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.heap_size_mbs_ = value;
}

// optional double heap_size_mb = 4;
inline bool AndroidGarbageCollectionStats::has_heap_size_mb() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000010U);
  return value;
}
inline void AndroidGarbageCollectionStats::clear_heap_size_mb() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.heap_size_mb_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline double AndroidGarbageCollectionStats::heap_size_mb() const {
  // @@protoc_insertion_point(field_get:perfetto.protos.AndroidGarbageCollectionStats.heap_size_mb)
  return _internal_heap_size_mb();
}
inline void AndroidGarbageCollectionStats::set_heap_size_mb(double value) {
  _internal_set_heap_size_mb(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:perfetto.protos.AndroidGarbageCollectionStats.heap_size_mb)
}
inline double AndroidGarbageCollectionStats::_internal_heap_size_mb() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.heap_size_mb_;
}
inline void AndroidGarbageCollectionStats::_internal_set_heap_size_mb(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.heap_size_mb_ = value;
}

// optional double heap_allocated_mb = 5;
inline bool AndroidGarbageCollectionStats::has_heap_allocated_mb() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000020U);
  return value;
}
inline void AndroidGarbageCollectionStats::clear_heap_allocated_mb() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.heap_allocated_mb_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000020U);
}
inline double AndroidGarbageCollectionStats::heap_allocated_mb() const {
  // @@protoc_insertion_point(field_get:perfetto.protos.AndroidGarbageCollectionStats.heap_allocated_mb)
  return _internal_heap_allocated_mb();
}
inline void AndroidGarbageCollectionStats::set_heap_allocated_mb(double value) {
  _internal_set_heap_allocated_mb(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  // @@protoc_insertion_point(field_set:perfetto.protos.AndroidGarbageCollectionStats.heap_allocated_mb)
}
inline double AndroidGarbageCollectionStats::_internal_heap_allocated_mb() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.heap_allocated_mb_;
}
inline void AndroidGarbageCollectionStats::_internal_set_heap_allocated_mb(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.heap_allocated_mb_ = value;
}

// optional double heap_allocation_rate = 6;
inline bool AndroidGarbageCollectionStats::has_heap_allocation_rate() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000040U);
  return value;
}
inline void AndroidGarbageCollectionStats::clear_heap_allocation_rate() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.heap_allocation_rate_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000040U);
}
inline double AndroidGarbageCollectionStats::heap_allocation_rate() const {
  // @@protoc_insertion_point(field_get:perfetto.protos.AndroidGarbageCollectionStats.heap_allocation_rate)
  return _internal_heap_allocation_rate();
}
inline void AndroidGarbageCollectionStats::set_heap_allocation_rate(double value) {
  _internal_set_heap_allocation_rate(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000040U);
  // @@protoc_insertion_point(field_set:perfetto.protos.AndroidGarbageCollectionStats.heap_allocation_rate)
}
inline double AndroidGarbageCollectionStats::_internal_heap_allocation_rate() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.heap_allocation_rate_;
}
inline void AndroidGarbageCollectionStats::_internal_set_heap_allocation_rate(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.heap_allocation_rate_ = value;
}

// optional double heap_live_mbs = 7;
inline bool AndroidGarbageCollectionStats::has_heap_live_mbs() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000080U);
  return value;
}
inline void AndroidGarbageCollectionStats::clear_heap_live_mbs() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.heap_live_mbs_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000080U);
}
inline double AndroidGarbageCollectionStats::heap_live_mbs() const {
  // @@protoc_insertion_point(field_get:perfetto.protos.AndroidGarbageCollectionStats.heap_live_mbs)
  return _internal_heap_live_mbs();
}
inline void AndroidGarbageCollectionStats::set_heap_live_mbs(double value) {
  _internal_set_heap_live_mbs(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000080U);
  // @@protoc_insertion_point(field_set:perfetto.protos.AndroidGarbageCollectionStats.heap_live_mbs)
}
inline double AndroidGarbageCollectionStats::_internal_heap_live_mbs() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.heap_live_mbs_;
}
inline void AndroidGarbageCollectionStats::_internal_set_heap_live_mbs(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.heap_live_mbs_ = value;
}

// optional double heap_total_mbs = 8;
inline bool AndroidGarbageCollectionStats::has_heap_total_mbs() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000100U);
  return value;
}
inline void AndroidGarbageCollectionStats::clear_heap_total_mbs() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.heap_total_mbs_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000100U);
}
inline double AndroidGarbageCollectionStats::heap_total_mbs() const {
  // @@protoc_insertion_point(field_get:perfetto.protos.AndroidGarbageCollectionStats.heap_total_mbs)
  return _internal_heap_total_mbs();
}
inline void AndroidGarbageCollectionStats::set_heap_total_mbs(double value) {
  _internal_set_heap_total_mbs(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000100U);
  // @@protoc_insertion_point(field_set:perfetto.protos.AndroidGarbageCollectionStats.heap_total_mbs)
}
inline double AndroidGarbageCollectionStats::_internal_heap_total_mbs() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.heap_total_mbs_;
}
inline void AndroidGarbageCollectionStats::_internal_set_heap_total_mbs(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.heap_total_mbs_ = value;
}

// optional double heap_utilization = 9;
inline bool AndroidGarbageCollectionStats::has_heap_utilization() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000200U);
  return value;
}
inline void AndroidGarbageCollectionStats::clear_heap_utilization() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.heap_utilization_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000200U);
}
inline double AndroidGarbageCollectionStats::heap_utilization() const {
  // @@protoc_insertion_point(field_get:perfetto.protos.AndroidGarbageCollectionStats.heap_utilization)
  return _internal_heap_utilization();
}
inline void AndroidGarbageCollectionStats::set_heap_utilization(double value) {
  _internal_set_heap_utilization(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000200U);
  // @@protoc_insertion_point(field_set:perfetto.protos.AndroidGarbageCollectionStats.heap_utilization)
}
inline double AndroidGarbageCollectionStats::_internal_heap_utilization() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.heap_utilization_;
}
inline void AndroidGarbageCollectionStats::_internal_set_heap_utilization(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.heap_utilization_ = value;
}

// optional int64 gc_running_dur = 10;
inline bool AndroidGarbageCollectionStats::has_gc_running_dur() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000400U);
  return value;
}
inline void AndroidGarbageCollectionStats::clear_gc_running_dur() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.gc_running_dur_ = ::int64_t{0};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000400U);
}
inline ::int64_t AndroidGarbageCollectionStats::gc_running_dur() const {
  // @@protoc_insertion_point(field_get:perfetto.protos.AndroidGarbageCollectionStats.gc_running_dur)
  return _internal_gc_running_dur();
}
inline void AndroidGarbageCollectionStats::set_gc_running_dur(::int64_t value) {
  _internal_set_gc_running_dur(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000400U);
  // @@protoc_insertion_point(field_set:perfetto.protos.AndroidGarbageCollectionStats.gc_running_dur)
}
inline ::int64_t AndroidGarbageCollectionStats::_internal_gc_running_dur() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.gc_running_dur_;
}
inline void AndroidGarbageCollectionStats::_internal_set_gc_running_dur(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.gc_running_dur_ = value;
}

// optional double gc_running_rate = 11;
inline bool AndroidGarbageCollectionStats::has_gc_running_rate() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000800U);
  return value;
}
inline void AndroidGarbageCollectionStats::clear_gc_running_rate() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.gc_running_rate_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000800U);
}
inline double AndroidGarbageCollectionStats::gc_running_rate() const {
  // @@protoc_insertion_point(field_get:perfetto.protos.AndroidGarbageCollectionStats.gc_running_rate)
  return _internal_gc_running_rate();
}
inline void AndroidGarbageCollectionStats::set_gc_running_rate(double value) {
  _internal_set_gc_running_rate(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000800U);
  // @@protoc_insertion_point(field_set:perfetto.protos.AndroidGarbageCollectionStats.gc_running_rate)
}
inline double AndroidGarbageCollectionStats::_internal_gc_running_rate() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.gc_running_rate_;
}
inline void AndroidGarbageCollectionStats::_internal_set_gc_running_rate(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.gc_running_rate_ = value;
}

// optional double gc_running_efficiency = 12;
inline bool AndroidGarbageCollectionStats::has_gc_running_efficiency() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00001000U);
  return value;
}
inline void AndroidGarbageCollectionStats::clear_gc_running_efficiency() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.gc_running_efficiency_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00001000U);
}
inline double AndroidGarbageCollectionStats::gc_running_efficiency() const {
  // @@protoc_insertion_point(field_get:perfetto.protos.AndroidGarbageCollectionStats.gc_running_efficiency)
  return _internal_gc_running_efficiency();
}
inline void AndroidGarbageCollectionStats::set_gc_running_efficiency(double value) {
  _internal_set_gc_running_efficiency(value);
  SetHasBit(_impl_._has_bits_[0], 0x00001000U);
  // @@protoc_insertion_point(field_set:perfetto.protos.AndroidGarbageCollectionStats.gc_running_efficiency)
}
inline double AndroidGarbageCollectionStats::_internal_gc_running_efficiency() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.gc_running_efficiency_;
}
inline void AndroidGarbageCollectionStats::_internal_set_gc_running_efficiency(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.gc_running_efficiency_ = value;
}

// optional int64 gc_during_android_startup_dur = 13;
inline bool AndroidGarbageCollectionStats::has_gc_during_android_startup_dur() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00002000U);
  return value;
}
inline void AndroidGarbageCollectionStats::clear_gc_during_android_startup_dur() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.gc_during_android_startup_dur_ = ::int64_t{0};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00002000U);
}
inline ::int64_t AndroidGarbageCollectionStats::gc_during_android_startup_dur() const {
  // @@protoc_insertion_point(field_get:perfetto.protos.AndroidGarbageCollectionStats.gc_during_android_startup_dur)
  return _internal_gc_during_android_startup_dur();
}
inline void AndroidGarbageCollectionStats::set_gc_during_android_startup_dur(::int64_t value) {
  _internal_set_gc_during_android_startup_dur(value);
  SetHasBit(_impl_._has_bits_[0], 0x00002000U);
  // @@protoc_insertion_point(field_set:perfetto.protos.AndroidGarbageCollectionStats.gc_during_android_startup_dur)
}
inline ::int64_t AndroidGarbageCollectionStats::_internal_gc_during_android_startup_dur() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.gc_during_android_startup_dur_;
}
inline void AndroidGarbageCollectionStats::_internal_set_gc_during_android_startup_dur(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.gc_during_android_startup_dur_ = value;
}

// optional int64 total_android_startup_dur = 14;
inline bool AndroidGarbageCollectionStats::has_total_android_startup_dur() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00004000U);
  return value;
}
inline void AndroidGarbageCollectionStats::clear_total_android_startup_dur() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.total_android_startup_dur_ = ::int64_t{0};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00004000U);
}
inline ::int64_t AndroidGarbageCollectionStats::total_android_startup_dur() const {
  // @@protoc_insertion_point(field_get:perfetto.protos.AndroidGarbageCollectionStats.total_android_startup_dur)
  return _internal_total_android_startup_dur();
}
inline void AndroidGarbageCollectionStats::set_total_android_startup_dur(::int64_t value) {
  _internal_set_total_android_startup_dur(value);
  SetHasBit(_impl_._has_bits_[0], 0x00004000U);
  // @@protoc_insertion_point(field_set:perfetto.protos.AndroidGarbageCollectionStats.total_android_startup_dur)
}
inline ::int64_t AndroidGarbageCollectionStats::_internal_total_android_startup_dur() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.total_android_startup_dur_;
}
inline void AndroidGarbageCollectionStats::_internal_set_total_android_startup_dur(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.total_android_startup_dur_ = value;
}

// optional double gc_during_android_startup_rate = 15;
inline bool AndroidGarbageCollectionStats::has_gc_during_android_startup_rate() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00008000U);
  return value;
}
inline void AndroidGarbageCollectionStats::clear_gc_during_android_startup_rate() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.gc_during_android_startup_rate_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00008000U);
}
inline double AndroidGarbageCollectionStats::gc_during_android_startup_rate() const {
  // @@protoc_insertion_point(field_get:perfetto.protos.AndroidGarbageCollectionStats.gc_during_android_startup_rate)
  return _internal_gc_during_android_startup_rate();
}
inline void AndroidGarbageCollectionStats::set_gc_during_android_startup_rate(double value) {
  _internal_set_gc_during_android_startup_rate(value);
  SetHasBit(_impl_._has_bits_[0], 0x00008000U);
  // @@protoc_insertion_point(field_set:perfetto.protos.AndroidGarbageCollectionStats.gc_during_android_startup_rate)
}
inline double AndroidGarbageCollectionStats::_internal_gc_during_android_startup_rate() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.gc_during_android_startup_rate_;
}
inline void AndroidGarbageCollectionStats::_internal_set_gc_during_android_startup_rate(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.gc_during_android_startup_rate_ = value;
}

// optional double gc_during_android_startup_efficiency = 16;
inline bool AndroidGarbageCollectionStats::has_gc_during_android_startup_efficiency() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00010000U);
  return value;
}
inline void AndroidGarbageCollectionStats::clear_gc_during_android_startup_efficiency() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.gc_during_android_startup_efficiency_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00010000U);
}
inline double AndroidGarbageCollectionStats::gc_during_android_startup_efficiency() const {
  // @@protoc_insertion_point(field_get:perfetto.protos.AndroidGarbageCollectionStats.gc_during_android_startup_efficiency)
  return _internal_gc_during_android_startup_efficiency();
}
inline void AndroidGarbageCollectionStats::set_gc_during_android_startup_efficiency(double value) {
  _internal_set_gc_during_android_startup_efficiency(value);
  SetHasBit(_impl_._has_bits_[0], 0x00010000U);
  // @@protoc_insertion_point(field_set:perfetto.protos.AndroidGarbageCollectionStats.gc_during_android_startup_efficiency)
}
inline double AndroidGarbageCollectionStats::_internal_gc_during_android_startup_efficiency() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.gc_during_android_startup_efficiency_;
}
inline void AndroidGarbageCollectionStats::_internal_set_gc_during_android_startup_efficiency(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.gc_during_android_startup_efficiency_ = value;
}

// repeated .perfetto.protos.AndroidGarbageCollectionStats.ProcessStats processes = 17;
inline int AndroidGarbageCollectionStats::_internal_processes_size() const {
  return _internal_processes().size();
}
inline int AndroidGarbageCollectionStats::processes_size() const {
  return _internal_processes_size();
}
inline void AndroidGarbageCollectionStats::clear_processes() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.processes_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::perfetto::protos::AndroidGarbageCollectionStats_ProcessStats* PROTOBUF_NONNULL AndroidGarbageCollectionStats::mutable_processes(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:perfetto.protos.AndroidGarbageCollectionStats.processes)
  return _internal_mutable_processes()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::perfetto::protos::AndroidGarbageCollectionStats_ProcessStats>* PROTOBUF_NONNULL AndroidGarbageCollectionStats::mutable_processes()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:perfetto.protos.AndroidGarbageCollectionStats.processes)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_processes();
}
inline const ::perfetto::protos::AndroidGarbageCollectionStats_ProcessStats& AndroidGarbageCollectionStats::processes(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:perfetto.protos.AndroidGarbageCollectionStats.processes)
  return _internal_processes().Get(index);
}
inline ::perfetto::protos::AndroidGarbageCollectionStats_ProcessStats* PROTOBUF_NONNULL AndroidGarbageCollectionStats::add_processes()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::perfetto::protos::AndroidGarbageCollectionStats_ProcessStats* _add =
      _internal_mutable_processes()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:perfetto.protos.AndroidGarbageCollectionStats.processes)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::perfetto::protos::AndroidGarbageCollectionStats_ProcessStats>& AndroidGarbageCollectionStats::processes() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:perfetto.protos.AndroidGarbageCollectionStats.processes)
  return _internal_processes();
}
inline const ::google::protobuf::RepeatedPtrField<::perfetto::protos::AndroidGarbageCollectionStats_ProcessStats>&
AndroidGarbageCollectionStats::_internal_processes() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.processes_;
}
inline ::google::protobuf::RepeatedPtrField<::perfetto::protos::AndroidGarbageCollectionStats_ProcessStats>* PROTOBUF_NONNULL
AndroidGarbageCollectionStats::_internal_mutable_processes() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.processes_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace protos
}  // namespace perfetto


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"
// clang-format on

#endif  // protos_2fperfetto_2fmetrics_2fandroid_2fandroid_5fgarbage_5fcollection_5fstats_2eproto_2epb_2eh
