// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protos/perfetto/metrics/android/fastrpc_metric.proto
// Protobuf C++ Version: 7.34.0

#include "protos/perfetto/metrics/android/fastrpc_metric.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/internal_visibility.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace perfetto {
namespace protos {

inline constexpr AndroidFastrpcMetric_Subsystem::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        avg_size_bytes_{0},
        min_size_bytes_{0},
        max_size_bytes_{0},
        total_alloc_size_bytes_{0} {}

template <typename>
constexpr AndroidFastrpcMetric_Subsystem::AndroidFastrpcMetric_Subsystem(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(AndroidFastrpcMetric_Subsystem_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
struct AndroidFastrpcMetric_SubsystemDefaultTypeInternal {
  constexpr AndroidFastrpcMetric_SubsystemDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AndroidFastrpcMetric_SubsystemDefaultTypeInternal() {}
  union {
    AndroidFastrpcMetric_Subsystem _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AndroidFastrpcMetric_SubsystemDefaultTypeInternal _AndroidFastrpcMetric_Subsystem_default_instance_;

inline constexpr AndroidFastrpcMetric::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        #ifdef PROTOBUF_INTERNAL_REMOVE_ARENA_PTRS_REPEATED_PTR_FIELD
        subsystem_{visibility, ::_pbi::InternalMetadataOffset::Build<
            ::perfetto::protos::AndroidFastrpcMetric,
            PROTOBUF_FIELD_OFFSET(::perfetto::protos::AndroidFastrpcMetric, _impl_.subsystem_)>()
        }
        #else  // !PROTOBUF_INTERNAL_REMOVE_ARENA_PTRS_REPEATED_PTR_FIELD
        subsystem_ {}
        #endif
     {}

template <typename>
constexpr AndroidFastrpcMetric::AndroidFastrpcMetric(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(AndroidFastrpcMetric_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
struct AndroidFastrpcMetricDefaultTypeInternal {
  constexpr AndroidFastrpcMetricDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AndroidFastrpcMetricDefaultTypeInternal() {}
  union {
    AndroidFastrpcMetric _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AndroidFastrpcMetricDefaultTypeInternal _AndroidFastrpcMetric_default_instance_;
}  // namespace protos
}  // namespace perfetto
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_protos_2fperfetto_2fmetrics_2fandroid_2ffastrpc_5fmetric_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_protos_2fperfetto_2fmetrics_2fandroid_2ffastrpc_5fmetric_2eproto = nullptr;
const ::uint32_t
    TableStruct_protos_2fperfetto_2fmetrics_2fandroid_2ffastrpc_5fmetric_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::perfetto::protos::AndroidFastrpcMetric_Subsystem, _impl_._has_bits_),
        8, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::perfetto::protos::AndroidFastrpcMetric_Subsystem, _impl_.name_),
        PROTOBUF_FIELD_OFFSET(::perfetto::protos::AndroidFastrpcMetric_Subsystem, _impl_.avg_size_bytes_),
        PROTOBUF_FIELD_OFFSET(::perfetto::protos::AndroidFastrpcMetric_Subsystem, _impl_.min_size_bytes_),
        PROTOBUF_FIELD_OFFSET(::perfetto::protos::AndroidFastrpcMetric_Subsystem, _impl_.max_size_bytes_),
        PROTOBUF_FIELD_OFFSET(::perfetto::protos::AndroidFastrpcMetric_Subsystem, _impl_.total_alloc_size_bytes_),
        0,
        1,
        2,
        3,
        4,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::perfetto::protos::AndroidFastrpcMetric, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::perfetto::protos::AndroidFastrpcMetric, _impl_.subsystem_),
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::perfetto::protos::AndroidFastrpcMetric_Subsystem)},
        {13, sizeof(::perfetto::protos::AndroidFastrpcMetric)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::perfetto::protos::_AndroidFastrpcMetric_Subsystem_default_instance_._instance,
    &::perfetto::protos::_AndroidFastrpcMetric_default_instance_._instance,
};
const char descriptor_table_protodef_protos_2fperfetto_2fmetrics_2fandroid_2ffastrpc_5fmetric_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n4protos/perfetto/metrics/android/fastrp"
    "c_metric.proto\022\017perfetto.protos\"\336\001\n\024Andr"
    "oidFastrpcMetric\022B\n\tsubsystem\030\001 \003(\0132/.pe"
    "rfetto.protos.AndroidFastrpcMetric.Subsy"
    "stem\032\201\001\n\tSubsystem\022\014\n\004name\030\001 \001(\t\022\026\n\016avg_"
    "size_bytes\030\002 \001(\001\022\026\n\016min_size_bytes\030\003 \001(\001"
    "\022\026\n\016max_size_bytes\030\004 \001(\001\022\036\n\026total_alloc_"
    "size_bytes\030\005 \001(\001"
};
static ::absl::once_flag descriptor_table_protos_2fperfetto_2fmetrics_2fandroid_2ffastrpc_5fmetric_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_protos_2fperfetto_2fmetrics_2fandroid_2ffastrpc_5fmetric_2eproto = {
    false,
    false,
    296,
    descriptor_table_protodef_protos_2fperfetto_2fmetrics_2fandroid_2ffastrpc_5fmetric_2eproto,
    "protos/perfetto/metrics/android/fastrpc_metric.proto",
    &descriptor_table_protos_2fperfetto_2fmetrics_2fandroid_2ffastrpc_5fmetric_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_protos_2fperfetto_2fmetrics_2fandroid_2ffastrpc_5fmetric_2eproto::offsets,
    file_level_enum_descriptors_protos_2fperfetto_2fmetrics_2fandroid_2ffastrpc_5fmetric_2eproto,
    file_level_service_descriptors_protos_2fperfetto_2fmetrics_2fandroid_2ffastrpc_5fmetric_2eproto,
};
namespace perfetto {
namespace protos {
// ===================================================================

class AndroidFastrpcMetric_Subsystem::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<AndroidFastrpcMetric_Subsystem>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(AndroidFastrpcMetric_Subsystem, _impl_._has_bits_);
};

AndroidFastrpcMetric_Subsystem::AndroidFastrpcMetric_Subsystem(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, AndroidFastrpcMetric_Subsystem_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:perfetto.protos.AndroidFastrpcMetric.Subsystem)
}
PROTOBUF_NDEBUG_INLINE AndroidFastrpcMetric_Subsystem::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::perfetto::protos::AndroidFastrpcMetric_Subsystem& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        name_(arena, from.name_) {}

AndroidFastrpcMetric_Subsystem::AndroidFastrpcMetric_Subsystem(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const AndroidFastrpcMetric_Subsystem& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, AndroidFastrpcMetric_Subsystem_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  AndroidFastrpcMetric_Subsystem* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, avg_size_bytes_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, avg_size_bytes_),
           offsetof(Impl_, total_alloc_size_bytes_) -
               offsetof(Impl_, avg_size_bytes_) +
               sizeof(Impl_::total_alloc_size_bytes_));

  // @@protoc_insertion_point(copy_constructor:perfetto.protos.AndroidFastrpcMetric.Subsystem)
}
PROTOBUF_NDEBUG_INLINE AndroidFastrpcMetric_Subsystem::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        name_(arena) {}

inline void AndroidFastrpcMetric_Subsystem::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, avg_size_bytes_),
           0,
           offsetof(Impl_, total_alloc_size_bytes_) -
               offsetof(Impl_, avg_size_bytes_) +
               sizeof(Impl_::total_alloc_size_bytes_));
}
AndroidFastrpcMetric_Subsystem::~AndroidFastrpcMetric_Subsystem() {
  // @@protoc_insertion_point(destructor:perfetto.protos.AndroidFastrpcMetric.Subsystem)
  SharedDtor(*this);
}
inline void AndroidFastrpcMetric_Subsystem::SharedDtor(MessageLite& self) {
  AndroidFastrpcMetric_Subsystem& this_ = static_cast<AndroidFastrpcMetric_Subsystem&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.name_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL AndroidFastrpcMetric_Subsystem::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) AndroidFastrpcMetric_Subsystem(arena);
}
constexpr auto AndroidFastrpcMetric_Subsystem::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(AndroidFastrpcMetric_Subsystem),
                                            alignof(AndroidFastrpcMetric_Subsystem));
}
constexpr auto AndroidFastrpcMetric_Subsystem::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_AndroidFastrpcMetric_Subsystem_default_instance_._instance,
          &_table_.header,
          nullptr,  // IsInitialized
          &AndroidFastrpcMetric_Subsystem::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<AndroidFastrpcMetric_Subsystem>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &AndroidFastrpcMetric_Subsystem::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<AndroidFastrpcMetric_Subsystem>(), &AndroidFastrpcMetric_Subsystem::ByteSizeLong,
              &AndroidFastrpcMetric_Subsystem::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(AndroidFastrpcMetric_Subsystem, _impl_._cached_size_),
          false,
      },
      &AndroidFastrpcMetric_Subsystem::kDescriptorMethods,
      &descriptor_table_protos_2fperfetto_2fmetrics_2fandroid_2ffastrpc_5fmetric_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull AndroidFastrpcMetric_Subsystem_class_data_ =
        AndroidFastrpcMetric_Subsystem::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
AndroidFastrpcMetric_Subsystem::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&AndroidFastrpcMetric_Subsystem_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(AndroidFastrpcMetric_Subsystem_class_data_.tc_table);
  return AndroidFastrpcMetric_Subsystem_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 0, 0, 2>
AndroidFastrpcMetric_Subsystem::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(AndroidFastrpcMetric_Subsystem, _impl_._has_bits_),
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    AndroidFastrpcMetric_Subsystem_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::perfetto::protos::AndroidFastrpcMetric_Subsystem>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // optional string name = 1;
    {::_pbi::TcParser::FastBS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(AndroidFastrpcMetric_Subsystem, _impl_.name_)}},
    // optional double avg_size_bytes = 2;
    {::_pbi::TcParser::FastF64S1,
     {17, 1, 0,
      PROTOBUF_FIELD_OFFSET(AndroidFastrpcMetric_Subsystem, _impl_.avg_size_bytes_)}},
    // optional double min_size_bytes = 3;
    {::_pbi::TcParser::FastF64S1,
     {25, 2, 0,
      PROTOBUF_FIELD_OFFSET(AndroidFastrpcMetric_Subsystem, _impl_.min_size_bytes_)}},
    // optional double max_size_bytes = 4;
    {::_pbi::TcParser::FastF64S1,
     {33, 3, 0,
      PROTOBUF_FIELD_OFFSET(AndroidFastrpcMetric_Subsystem, _impl_.max_size_bytes_)}},
    // optional double total_alloc_size_bytes = 5;
    {::_pbi::TcParser::FastF64S1,
     {41, 4, 0,
      PROTOBUF_FIELD_OFFSET(AndroidFastrpcMetric_Subsystem, _impl_.total_alloc_size_bytes_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // optional string name = 1;
    {PROTOBUF_FIELD_OFFSET(AndroidFastrpcMetric_Subsystem, _impl_.name_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // optional double avg_size_bytes = 2;
    {PROTOBUF_FIELD_OFFSET(AndroidFastrpcMetric_Subsystem, _impl_.avg_size_bytes_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kDouble)},
    // optional double min_size_bytes = 3;
    {PROTOBUF_FIELD_OFFSET(AndroidFastrpcMetric_Subsystem, _impl_.min_size_bytes_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kDouble)},
    // optional double max_size_bytes = 4;
    {PROTOBUF_FIELD_OFFSET(AndroidFastrpcMetric_Subsystem, _impl_.max_size_bytes_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kDouble)},
    // optional double total_alloc_size_bytes = 5;
    {PROTOBUF_FIELD_OFFSET(AndroidFastrpcMetric_Subsystem, _impl_.total_alloc_size_bytes_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kDouble)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void AndroidFastrpcMetric_Subsystem::Clear() {
// @@protoc_insertion_point(message_clear_start:perfetto.protos.AndroidFastrpcMetric.Subsystem)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _impl_.name_.ClearNonDefaultToEmpty();
  }
  if (BatchCheckHasBit(cached_has_bits, 0x0000001eU)) {
    ::memset(&_impl_.avg_size_bytes_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.total_alloc_size_bytes_) -
        reinterpret_cast<char*>(&_impl_.avg_size_bytes_)) + sizeof(_impl_.total_alloc_size_bytes_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL AndroidFastrpcMetric_Subsystem::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const AndroidFastrpcMetric_Subsystem& this_ = static_cast<const AndroidFastrpcMetric_Subsystem&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL AndroidFastrpcMetric_Subsystem::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const AndroidFastrpcMetric_Subsystem& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:perfetto.protos.AndroidFastrpcMetric.Subsystem)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional string name = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    const ::std::string& _s = this_._internal_name();
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // optional double avg_size_bytes = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(
        2, this_._internal_avg_size_bytes(), target);
  }

  // optional double min_size_bytes = 3;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(
        3, this_._internal_min_size_bytes(), target);
  }

  // optional double max_size_bytes = 4;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(
        4, this_._internal_max_size_bytes(), target);
  }

  // optional double total_alloc_size_bytes = 5;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(
        5, this_._internal_total_alloc_size_bytes(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:perfetto.protos.AndroidFastrpcMetric.Subsystem)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t AndroidFastrpcMetric_Subsystem::ByteSizeLong(const MessageLite& base) {
  const AndroidFastrpcMetric_Subsystem& this_ = static_cast<const AndroidFastrpcMetric_Subsystem&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t AndroidFastrpcMetric_Subsystem::ByteSizeLong() const {
  const AndroidFastrpcMetric_Subsystem& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:perfetto.protos.AndroidFastrpcMetric.Subsystem)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  total_size += ::absl::popcount(0x0000001eU & cached_has_bits) * 9;
   {
    // optional string name = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_name());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void AndroidFastrpcMetric_Subsystem::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<AndroidFastrpcMetric_Subsystem*>(&to_msg);
  auto& from = static_cast<const AndroidFastrpcMetric_Subsystem&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:perfetto.protos.AndroidFastrpcMetric.Subsystem)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _this->_internal_set_name(from._internal_name());
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _this->_impl_.avg_size_bytes_ = from._impl_.avg_size_bytes_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _this->_impl_.min_size_bytes_ = from._impl_.min_size_bytes_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      _this->_impl_.max_size_bytes_ = from._impl_.max_size_bytes_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      _this->_impl_.total_alloc_size_bytes_ = from._impl_.total_alloc_size_bytes_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void AndroidFastrpcMetric_Subsystem::CopyFrom(const AndroidFastrpcMetric_Subsystem& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:perfetto.protos.AndroidFastrpcMetric.Subsystem)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void AndroidFastrpcMetric_Subsystem::InternalSwap(AndroidFastrpcMetric_Subsystem* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(AndroidFastrpcMetric_Subsystem, _impl_.total_alloc_size_bytes_)
      + sizeof(AndroidFastrpcMetric_Subsystem::_impl_.total_alloc_size_bytes_)
      - PROTOBUF_FIELD_OFFSET(AndroidFastrpcMetric_Subsystem, _impl_.avg_size_bytes_)>(
          reinterpret_cast<char*>(&_impl_.avg_size_bytes_),
          reinterpret_cast<char*>(&other->_impl_.avg_size_bytes_));
}

::google::protobuf::Metadata AndroidFastrpcMetric_Subsystem::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class AndroidFastrpcMetric::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<AndroidFastrpcMetric>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(AndroidFastrpcMetric, _impl_._has_bits_);
};

AndroidFastrpcMetric::AndroidFastrpcMetric(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, AndroidFastrpcMetric_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:perfetto.protos.AndroidFastrpcMetric)
}
PROTOBUF_NDEBUG_INLINE AndroidFastrpcMetric::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::perfetto::protos::AndroidFastrpcMetric& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        #ifdef PROTOBUF_INTERNAL_REMOVE_ARENA_PTRS_REPEATED_PTR_FIELD
        subsystem_{visibility, ::_pbi::InternalMetadataOffset::Build<
            ::perfetto::protos::AndroidFastrpcMetric,
            PROTOBUF_FIELD_OFFSET(::perfetto::protos::AndroidFastrpcMetric, _impl_.subsystem_)>()
        , from.subsystem_}
        #else
        subsystem_ { visibility, arena, from.subsystem_ }
        #endif
     {}

AndroidFastrpcMetric::AndroidFastrpcMetric(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const AndroidFastrpcMetric& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, AndroidFastrpcMetric_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  AndroidFastrpcMetric* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:perfetto.protos.AndroidFastrpcMetric)
}
PROTOBUF_NDEBUG_INLINE AndroidFastrpcMetric::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        #ifdef PROTOBUF_INTERNAL_REMOVE_ARENA_PTRS_REPEATED_PTR_FIELD
        subsystem_{visibility, ::_pbi::InternalMetadataOffset::Build<
            ::perfetto::protos::AndroidFastrpcMetric,
            PROTOBUF_FIELD_OFFSET(::perfetto::protos::AndroidFastrpcMetric, _impl_.subsystem_)>()
        }
        #else
        subsystem_ { visibility, arena }
        #endif
     {}

inline void AndroidFastrpcMetric::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
AndroidFastrpcMetric::~AndroidFastrpcMetric() {
  // @@protoc_insertion_point(destructor:perfetto.protos.AndroidFastrpcMetric)
  SharedDtor(*this);
}
inline void AndroidFastrpcMetric::SharedDtor(MessageLite& self) {
  AndroidFastrpcMetric& this_ = static_cast<AndroidFastrpcMetric&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL AndroidFastrpcMetric::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) AndroidFastrpcMetric(arena);
}
#ifdef PROTOBUF_INTERNAL_REMOVE_ARENA_PTRS_REPEATED_PTR_FIELD
constexpr auto AndroidFastrpcMetric::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(AndroidFastrpcMetric),
                                            alignof(AndroidFastrpcMetric));
}
#else  // !PROTOBUF_INTERNAL_REMOVE_ARENA_PTRS_REPEATED_PTR_FIELD
constexpr auto AndroidFastrpcMetric::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(AndroidFastrpcMetric, _impl_.subsystem_) +
          decltype(AndroidFastrpcMetric::_impl_.subsystem_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(AndroidFastrpcMetric), alignof(AndroidFastrpcMetric), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&AndroidFastrpcMetric::PlacementNew_,
                                 sizeof(AndroidFastrpcMetric),
                                 alignof(AndroidFastrpcMetric));
  }
}
#endif
constexpr auto AndroidFastrpcMetric::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_AndroidFastrpcMetric_default_instance_._instance,
          &_table_.header,
          nullptr,  // IsInitialized
          &AndroidFastrpcMetric::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<AndroidFastrpcMetric>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &AndroidFastrpcMetric::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<AndroidFastrpcMetric>(), &AndroidFastrpcMetric::ByteSizeLong,
              &AndroidFastrpcMetric::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(AndroidFastrpcMetric, _impl_._cached_size_),
          false,
      },
      &AndroidFastrpcMetric::kDescriptorMethods,
      &descriptor_table_protos_2fperfetto_2fmetrics_2fandroid_2ffastrpc_5fmetric_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull AndroidFastrpcMetric_class_data_ =
        AndroidFastrpcMetric::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
AndroidFastrpcMetric::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&AndroidFastrpcMetric_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(AndroidFastrpcMetric_class_data_.tc_table);
  return AndroidFastrpcMetric_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2>
AndroidFastrpcMetric::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(AndroidFastrpcMetric, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    AndroidFastrpcMetric_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::perfetto::protos::AndroidFastrpcMetric>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .perfetto.protos.AndroidFastrpcMetric.Subsystem subsystem = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(AndroidFastrpcMetric, _impl_.subsystem_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .perfetto.protos.AndroidFastrpcMetric.Subsystem subsystem = 1;
    {PROTOBUF_FIELD_OFFSET(AndroidFastrpcMetric, _impl_.subsystem_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::perfetto::protos::AndroidFastrpcMetric_Subsystem>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void AndroidFastrpcMetric::Clear() {
// @@protoc_insertion_point(message_clear_start:perfetto.protos.AndroidFastrpcMetric)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    _impl_.subsystem_.Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL AndroidFastrpcMetric::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const AndroidFastrpcMetric& this_ = static_cast<const AndroidFastrpcMetric&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL AndroidFastrpcMetric::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const AndroidFastrpcMetric& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:perfetto.protos.AndroidFastrpcMetric)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // repeated .perfetto.protos.AndroidFastrpcMetric.Subsystem subsystem = 1;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    for (unsigned i = 0, n = static_cast<unsigned>(
                             this_._internal_subsystem_size());
         i < n; i++) {
      const auto& repfield = this_._internal_subsystem().Get(i);
      target =
          ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
              1, repfield, repfield.GetCachedSize(),
              target, stream);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:perfetto.protos.AndroidFastrpcMetric)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t AndroidFastrpcMetric::ByteSizeLong(const MessageLite& base) {
  const AndroidFastrpcMetric& this_ = static_cast<const AndroidFastrpcMetric&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t AndroidFastrpcMetric::ByteSizeLong() const {
  const AndroidFastrpcMetric& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:perfetto.protos.AndroidFastrpcMetric)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
   {
    // repeated .perfetto.protos.AndroidFastrpcMetric.Subsystem subsystem = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      total_size += 1UL * this_._internal_subsystem_size();
      for (const auto& msg : this_._internal_subsystem()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void AndroidFastrpcMetric::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<AndroidFastrpcMetric*>(&to_msg);
  auto& from = static_cast<const AndroidFastrpcMetric&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:perfetto.protos.AndroidFastrpcMetric)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    _this->_internal_mutable_subsystem()->InternalMergeFromWithArena(
        ::google::protobuf::MessageLite::internal_visibility(), arena,
        from._internal_subsystem());
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void AndroidFastrpcMetric::CopyFrom(const AndroidFastrpcMetric& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:perfetto.protos.AndroidFastrpcMetric)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void AndroidFastrpcMetric::InternalSwap(AndroidFastrpcMetric* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.subsystem_.InternalSwap(&other->_impl_.subsystem_);
}

::google::protobuf::Metadata AndroidFastrpcMetric::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace protos
}  // namespace perfetto
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_protos_2fperfetto_2fmetrics_2fandroid_2ffastrpc_5fmetric_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
