// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protos/perfetto/metrics/android/multiuser_metric.proto
// Protobuf C++ Version: 7.34.0

#include "protos/perfetto/metrics/android/multiuser_metric.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/internal_visibility.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace perfetto {
namespace protos {

inline constexpr AndroidMultiuserMetric_EventData_CpuUsage::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        process_name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        identifier_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        user_id_{0},
        cpu_mcycles_{0},
        cpu_percentage_{0} {}

template <typename>
constexpr AndroidMultiuserMetric_EventData_CpuUsage::AndroidMultiuserMetric_EventData_CpuUsage(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(AndroidMultiuserMetric_EventData_CpuUsage_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
struct AndroidMultiuserMetric_EventData_CpuUsageDefaultTypeInternal {
  constexpr AndroidMultiuserMetric_EventData_CpuUsageDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AndroidMultiuserMetric_EventData_CpuUsageDefaultTypeInternal() {}
  union {
    AndroidMultiuserMetric_EventData_CpuUsage _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AndroidMultiuserMetric_EventData_CpuUsageDefaultTypeInternal _AndroidMultiuserMetric_EventData_CpuUsage_default_instance_;

inline constexpr AndroidMultiuserMetric_EventData::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        #ifdef PROTOBUF_INTERNAL_REMOVE_ARENA_PTRS_REPEATED_PTR_FIELD
        cpu_usage_{visibility, ::_pbi::InternalMetadataOffset::Build<
            ::perfetto::protos::AndroidMultiuserMetric_EventData,
            PROTOBUF_FIELD_OFFSET(::perfetto::protos::AndroidMultiuserMetric_EventData, _impl_.cpu_usage_)>()
        }
        #else  // !PROTOBUF_INTERNAL_REMOVE_ARENA_PTRS_REPEATED_PTR_FIELD
        cpu_usage_ {}
        #endif
        ,
        duration_ms_{0} {}

template <typename>
constexpr AndroidMultiuserMetric_EventData::AndroidMultiuserMetric_EventData(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(AndroidMultiuserMetric_EventData_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
struct AndroidMultiuserMetric_EventDataDefaultTypeInternal {
  constexpr AndroidMultiuserMetric_EventDataDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AndroidMultiuserMetric_EventDataDefaultTypeInternal() {}
  union {
    AndroidMultiuserMetric_EventData _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AndroidMultiuserMetric_EventDataDefaultTypeInternal _AndroidMultiuserMetric_EventData_default_instance_;

inline constexpr AndroidMultiuserMetric::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        user_switch_{nullptr} {}

template <typename>
constexpr AndroidMultiuserMetric::AndroidMultiuserMetric(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(AndroidMultiuserMetric_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
struct AndroidMultiuserMetricDefaultTypeInternal {
  constexpr AndroidMultiuserMetricDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AndroidMultiuserMetricDefaultTypeInternal() {}
  union {
    AndroidMultiuserMetric _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AndroidMultiuserMetricDefaultTypeInternal _AndroidMultiuserMetric_default_instance_;
}  // namespace protos
}  // namespace perfetto
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_protos_2fperfetto_2fmetrics_2fandroid_2fmultiuser_5fmetric_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_protos_2fperfetto_2fmetrics_2fandroid_2fmultiuser_5fmetric_2eproto = nullptr;
const ::uint32_t
    TableStruct_protos_2fperfetto_2fmetrics_2fandroid_2fmultiuser_5fmetric_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::perfetto::protos::AndroidMultiuserMetric_EventData_CpuUsage, _impl_._has_bits_),
        8, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::perfetto::protos::AndroidMultiuserMetric_EventData_CpuUsage, _impl_.user_id_),
        PROTOBUF_FIELD_OFFSET(::perfetto::protos::AndroidMultiuserMetric_EventData_CpuUsage, _impl_.process_name_),
        PROTOBUF_FIELD_OFFSET(::perfetto::protos::AndroidMultiuserMetric_EventData_CpuUsage, _impl_.cpu_mcycles_),
        PROTOBUF_FIELD_OFFSET(::perfetto::protos::AndroidMultiuserMetric_EventData_CpuUsage, _impl_.cpu_percentage_),
        PROTOBUF_FIELD_OFFSET(::perfetto::protos::AndroidMultiuserMetric_EventData_CpuUsage, _impl_.identifier_),
        2,
        0,
        3,
        4,
        1,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::perfetto::protos::AndroidMultiuserMetric_EventData, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::perfetto::protos::AndroidMultiuserMetric_EventData, _impl_.duration_ms_),
        PROTOBUF_FIELD_OFFSET(::perfetto::protos::AndroidMultiuserMetric_EventData, _impl_.cpu_usage_),
        1,
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::perfetto::protos::AndroidMultiuserMetric, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::perfetto::protos::AndroidMultiuserMetric, _impl_.user_switch_),
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::perfetto::protos::AndroidMultiuserMetric_EventData_CpuUsage)},
        {13, sizeof(::perfetto::protos::AndroidMultiuserMetric_EventData)},
        {20, sizeof(::perfetto::protos::AndroidMultiuserMetric)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::perfetto::protos::_AndroidMultiuserMetric_EventData_CpuUsage_default_instance_._instance,
    &::perfetto::protos::_AndroidMultiuserMetric_EventData_default_instance_._instance,
    &::perfetto::protos::_AndroidMultiuserMetric_default_instance_._instance,
};
const char descriptor_table_protodef_protos_2fperfetto_2fmetrics_2fandroid_2fmultiuser_5fmetric_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n6protos/perfetto/metrics/android/multiu"
    "ser_metric.proto\022\017perfetto.protos\"\306\002\n\026An"
    "droidMultiuserMetric\022F\n\013user_switch\030\001 \001("
    "\01321.perfetto.protos.AndroidMultiuserMetr"
    "ic.EventData\032\343\001\n\tEventData\022\023\n\013duration_m"
    "s\030\001 \001(\005\022M\n\tcpu_usage\030\002 \003(\0132:.perfetto.pr"
    "otos.AndroidMultiuserMetric.EventData.Cp"
    "uUsage\032r\n\010CpuUsage\022\017\n\007user_id\030\001 \001(\005\022\024\n\014p"
    "rocess_name\030\002 \001(\t\022\023\n\013cpu_mcycles\030\003 \001(\005\022\026"
    "\n\016cpu_percentage\030\004 \001(\002\022\022\n\nidentifier\030\005 \001"
    "(\t"
};
static ::absl::once_flag descriptor_table_protos_2fperfetto_2fmetrics_2fandroid_2fmultiuser_5fmetric_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_protos_2fperfetto_2fmetrics_2fandroid_2fmultiuser_5fmetric_2eproto = {
    false,
    false,
    402,
    descriptor_table_protodef_protos_2fperfetto_2fmetrics_2fandroid_2fmultiuser_5fmetric_2eproto,
    "protos/perfetto/metrics/android/multiuser_metric.proto",
    &descriptor_table_protos_2fperfetto_2fmetrics_2fandroid_2fmultiuser_5fmetric_2eproto_once,
    nullptr,
    0,
    3,
    schemas,
    file_default_instances,
    TableStruct_protos_2fperfetto_2fmetrics_2fandroid_2fmultiuser_5fmetric_2eproto::offsets,
    file_level_enum_descriptors_protos_2fperfetto_2fmetrics_2fandroid_2fmultiuser_5fmetric_2eproto,
    file_level_service_descriptors_protos_2fperfetto_2fmetrics_2fandroid_2fmultiuser_5fmetric_2eproto,
};
namespace perfetto {
namespace protos {
// ===================================================================

class AndroidMultiuserMetric_EventData_CpuUsage::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<AndroidMultiuserMetric_EventData_CpuUsage>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(AndroidMultiuserMetric_EventData_CpuUsage, _impl_._has_bits_);
};

AndroidMultiuserMetric_EventData_CpuUsage::AndroidMultiuserMetric_EventData_CpuUsage(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, AndroidMultiuserMetric_EventData_CpuUsage_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:perfetto.protos.AndroidMultiuserMetric.EventData.CpuUsage)
}
PROTOBUF_NDEBUG_INLINE AndroidMultiuserMetric_EventData_CpuUsage::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::perfetto::protos::AndroidMultiuserMetric_EventData_CpuUsage& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        process_name_(arena, from.process_name_),
        identifier_(arena, from.identifier_) {}

AndroidMultiuserMetric_EventData_CpuUsage::AndroidMultiuserMetric_EventData_CpuUsage(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const AndroidMultiuserMetric_EventData_CpuUsage& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, AndroidMultiuserMetric_EventData_CpuUsage_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  AndroidMultiuserMetric_EventData_CpuUsage* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, user_id_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, user_id_),
           offsetof(Impl_, cpu_percentage_) -
               offsetof(Impl_, user_id_) +
               sizeof(Impl_::cpu_percentage_));

  // @@protoc_insertion_point(copy_constructor:perfetto.protos.AndroidMultiuserMetric.EventData.CpuUsage)
}
PROTOBUF_NDEBUG_INLINE AndroidMultiuserMetric_EventData_CpuUsage::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        process_name_(arena),
        identifier_(arena) {}

inline void AndroidMultiuserMetric_EventData_CpuUsage::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, user_id_),
           0,
           offsetof(Impl_, cpu_percentage_) -
               offsetof(Impl_, user_id_) +
               sizeof(Impl_::cpu_percentage_));
}
AndroidMultiuserMetric_EventData_CpuUsage::~AndroidMultiuserMetric_EventData_CpuUsage() {
  // @@protoc_insertion_point(destructor:perfetto.protos.AndroidMultiuserMetric.EventData.CpuUsage)
  SharedDtor(*this);
}
inline void AndroidMultiuserMetric_EventData_CpuUsage::SharedDtor(MessageLite& self) {
  AndroidMultiuserMetric_EventData_CpuUsage& this_ = static_cast<AndroidMultiuserMetric_EventData_CpuUsage&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.process_name_.Destroy();
  this_._impl_.identifier_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL AndroidMultiuserMetric_EventData_CpuUsage::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) AndroidMultiuserMetric_EventData_CpuUsage(arena);
}
constexpr auto AndroidMultiuserMetric_EventData_CpuUsage::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(AndroidMultiuserMetric_EventData_CpuUsage),
                                            alignof(AndroidMultiuserMetric_EventData_CpuUsage));
}
constexpr auto AndroidMultiuserMetric_EventData_CpuUsage::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_AndroidMultiuserMetric_EventData_CpuUsage_default_instance_._instance,
          &_table_.header,
          nullptr,  // IsInitialized
          &AndroidMultiuserMetric_EventData_CpuUsage::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<AndroidMultiuserMetric_EventData_CpuUsage>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &AndroidMultiuserMetric_EventData_CpuUsage::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<AndroidMultiuserMetric_EventData_CpuUsage>(), &AndroidMultiuserMetric_EventData_CpuUsage::ByteSizeLong,
              &AndroidMultiuserMetric_EventData_CpuUsage::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(AndroidMultiuserMetric_EventData_CpuUsage, _impl_._cached_size_),
          false,
      },
      &AndroidMultiuserMetric_EventData_CpuUsage::kDescriptorMethods,
      &descriptor_table_protos_2fperfetto_2fmetrics_2fandroid_2fmultiuser_5fmetric_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull AndroidMultiuserMetric_EventData_CpuUsage_class_data_ =
        AndroidMultiuserMetric_EventData_CpuUsage::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
AndroidMultiuserMetric_EventData_CpuUsage::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&AndroidMultiuserMetric_EventData_CpuUsage_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(AndroidMultiuserMetric_EventData_CpuUsage_class_data_.tc_table);
  return AndroidMultiuserMetric_EventData_CpuUsage_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 0, 0, 2>
AndroidMultiuserMetric_EventData_CpuUsage::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(AndroidMultiuserMetric_EventData_CpuUsage, _impl_._has_bits_),
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    AndroidMultiuserMetric_EventData_CpuUsage_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::perfetto::protos::AndroidMultiuserMetric_EventData_CpuUsage>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // optional int32 user_id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(AndroidMultiuserMetric_EventData_CpuUsage, _impl_.user_id_), 2>(),
     {8, 2, 0,
      PROTOBUF_FIELD_OFFSET(AndroidMultiuserMetric_EventData_CpuUsage, _impl_.user_id_)}},
    // optional string process_name = 2;
    {::_pbi::TcParser::FastBS1,
     {18, 0, 0,
      PROTOBUF_FIELD_OFFSET(AndroidMultiuserMetric_EventData_CpuUsage, _impl_.process_name_)}},
    // optional int32 cpu_mcycles = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(AndroidMultiuserMetric_EventData_CpuUsage, _impl_.cpu_mcycles_), 3>(),
     {24, 3, 0,
      PROTOBUF_FIELD_OFFSET(AndroidMultiuserMetric_EventData_CpuUsage, _impl_.cpu_mcycles_)}},
    // optional float cpu_percentage = 4;
    {::_pbi::TcParser::FastF32S1,
     {37, 4, 0,
      PROTOBUF_FIELD_OFFSET(AndroidMultiuserMetric_EventData_CpuUsage, _impl_.cpu_percentage_)}},
    // optional string identifier = 5;
    {::_pbi::TcParser::FastBS1,
     {42, 1, 0,
      PROTOBUF_FIELD_OFFSET(AndroidMultiuserMetric_EventData_CpuUsage, _impl_.identifier_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // optional int32 user_id = 1;
    {PROTOBUF_FIELD_OFFSET(AndroidMultiuserMetric_EventData_CpuUsage, _impl_.user_id_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional string process_name = 2;
    {PROTOBUF_FIELD_OFFSET(AndroidMultiuserMetric_EventData_CpuUsage, _impl_.process_name_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // optional int32 cpu_mcycles = 3;
    {PROTOBUF_FIELD_OFFSET(AndroidMultiuserMetric_EventData_CpuUsage, _impl_.cpu_mcycles_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional float cpu_percentage = 4;
    {PROTOBUF_FIELD_OFFSET(AndroidMultiuserMetric_EventData_CpuUsage, _impl_.cpu_percentage_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // optional string identifier = 5;
    {PROTOBUF_FIELD_OFFSET(AndroidMultiuserMetric_EventData_CpuUsage, _impl_.identifier_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void AndroidMultiuserMetric_EventData_CpuUsage::Clear() {
// @@protoc_insertion_point(message_clear_start:perfetto.protos.AndroidMultiuserMetric.EventData.CpuUsage)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.process_name_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.identifier_.ClearNonDefaultToEmpty();
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x0000001cU)) {
    ::memset(&_impl_.user_id_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.cpu_percentage_) -
        reinterpret_cast<char*>(&_impl_.user_id_)) + sizeof(_impl_.cpu_percentage_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL AndroidMultiuserMetric_EventData_CpuUsage::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const AndroidMultiuserMetric_EventData_CpuUsage& this_ = static_cast<const AndroidMultiuserMetric_EventData_CpuUsage&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL AndroidMultiuserMetric_EventData_CpuUsage::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const AndroidMultiuserMetric_EventData_CpuUsage& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:perfetto.protos.AndroidMultiuserMetric.EventData.CpuUsage)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional int32 user_id = 1;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<1>(
            stream, this_._internal_user_id(), target);
  }

  // optional string process_name = 2;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    const ::std::string& _s = this_._internal_process_name();
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // optional int32 cpu_mcycles = 3;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<3>(
            stream, this_._internal_cpu_mcycles(), target);
  }

  // optional float cpu_percentage = 4;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        4, this_._internal_cpu_percentage(), target);
  }

  // optional string identifier = 5;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    const ::std::string& _s = this_._internal_identifier();
    target = stream->WriteStringMaybeAliased(5, _s, target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:perfetto.protos.AndroidMultiuserMetric.EventData.CpuUsage)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t AndroidMultiuserMetric_EventData_CpuUsage::ByteSizeLong(const MessageLite& base) {
  const AndroidMultiuserMetric_EventData_CpuUsage& this_ = static_cast<const AndroidMultiuserMetric_EventData_CpuUsage&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t AndroidMultiuserMetric_EventData_CpuUsage::ByteSizeLong() const {
  const AndroidMultiuserMetric_EventData_CpuUsage& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:perfetto.protos.AndroidMultiuserMetric.EventData.CpuUsage)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  total_size += static_cast<bool>(0x00000010U & cached_has_bits) * 5;
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    // optional string process_name = 2;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_process_name());
    }
    // optional string identifier = 5;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_identifier());
    }
    // optional int32 user_id = 1;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this_._internal_user_id());
    }
    // optional int32 cpu_mcycles = 3;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this_._internal_cpu_mcycles());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void AndroidMultiuserMetric_EventData_CpuUsage::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<AndroidMultiuserMetric_EventData_CpuUsage*>(&to_msg);
  auto& from = static_cast<const AndroidMultiuserMetric_EventData_CpuUsage&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:perfetto.protos.AndroidMultiuserMetric.EventData.CpuUsage)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _this->_internal_set_process_name(from._internal_process_name());
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _this->_internal_set_identifier(from._internal_identifier());
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _this->_impl_.user_id_ = from._impl_.user_id_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      _this->_impl_.cpu_mcycles_ = from._impl_.cpu_mcycles_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      _this->_impl_.cpu_percentage_ = from._impl_.cpu_percentage_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void AndroidMultiuserMetric_EventData_CpuUsage::CopyFrom(const AndroidMultiuserMetric_EventData_CpuUsage& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:perfetto.protos.AndroidMultiuserMetric.EventData.CpuUsage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void AndroidMultiuserMetric_EventData_CpuUsage::InternalSwap(AndroidMultiuserMetric_EventData_CpuUsage* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.process_name_, &other->_impl_.process_name_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.identifier_, &other->_impl_.identifier_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(AndroidMultiuserMetric_EventData_CpuUsage, _impl_.cpu_percentage_)
      + sizeof(AndroidMultiuserMetric_EventData_CpuUsage::_impl_.cpu_percentage_)
      - PROTOBUF_FIELD_OFFSET(AndroidMultiuserMetric_EventData_CpuUsage, _impl_.user_id_)>(
          reinterpret_cast<char*>(&_impl_.user_id_),
          reinterpret_cast<char*>(&other->_impl_.user_id_));
}

::google::protobuf::Metadata AndroidMultiuserMetric_EventData_CpuUsage::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class AndroidMultiuserMetric_EventData::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<AndroidMultiuserMetric_EventData>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(AndroidMultiuserMetric_EventData, _impl_._has_bits_);
};

AndroidMultiuserMetric_EventData::AndroidMultiuserMetric_EventData(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, AndroidMultiuserMetric_EventData_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:perfetto.protos.AndroidMultiuserMetric.EventData)
}
PROTOBUF_NDEBUG_INLINE AndroidMultiuserMetric_EventData::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::perfetto::protos::AndroidMultiuserMetric_EventData& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        #ifdef PROTOBUF_INTERNAL_REMOVE_ARENA_PTRS_REPEATED_PTR_FIELD
        cpu_usage_{visibility, ::_pbi::InternalMetadataOffset::Build<
            ::perfetto::protos::AndroidMultiuserMetric_EventData,
            PROTOBUF_FIELD_OFFSET(::perfetto::protos::AndroidMultiuserMetric_EventData, _impl_.cpu_usage_)>()
        , from.cpu_usage_}
        #else
        cpu_usage_ { visibility, arena, from.cpu_usage_ }
        #endif
     {}

AndroidMultiuserMetric_EventData::AndroidMultiuserMetric_EventData(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const AndroidMultiuserMetric_EventData& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, AndroidMultiuserMetric_EventData_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  AndroidMultiuserMetric_EventData* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.duration_ms_ = from._impl_.duration_ms_;

  // @@protoc_insertion_point(copy_constructor:perfetto.protos.AndroidMultiuserMetric.EventData)
}
PROTOBUF_NDEBUG_INLINE AndroidMultiuserMetric_EventData::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        #ifdef PROTOBUF_INTERNAL_REMOVE_ARENA_PTRS_REPEATED_PTR_FIELD
        cpu_usage_{visibility, ::_pbi::InternalMetadataOffset::Build<
            ::perfetto::protos::AndroidMultiuserMetric_EventData,
            PROTOBUF_FIELD_OFFSET(::perfetto::protos::AndroidMultiuserMetric_EventData, _impl_.cpu_usage_)>()
        }
        #else
        cpu_usage_ { visibility, arena }
        #endif
     {}

inline void AndroidMultiuserMetric_EventData::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.duration_ms_ = {};
}
AndroidMultiuserMetric_EventData::~AndroidMultiuserMetric_EventData() {
  // @@protoc_insertion_point(destructor:perfetto.protos.AndroidMultiuserMetric.EventData)
  SharedDtor(*this);
}
inline void AndroidMultiuserMetric_EventData::SharedDtor(MessageLite& self) {
  AndroidMultiuserMetric_EventData& this_ = static_cast<AndroidMultiuserMetric_EventData&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL AndroidMultiuserMetric_EventData::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) AndroidMultiuserMetric_EventData(arena);
}
#ifdef PROTOBUF_INTERNAL_REMOVE_ARENA_PTRS_REPEATED_PTR_FIELD
constexpr auto AndroidMultiuserMetric_EventData::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(AndroidMultiuserMetric_EventData),
                                            alignof(AndroidMultiuserMetric_EventData));
}
#else  // !PROTOBUF_INTERNAL_REMOVE_ARENA_PTRS_REPEATED_PTR_FIELD
constexpr auto AndroidMultiuserMetric_EventData::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(AndroidMultiuserMetric_EventData, _impl_.cpu_usage_) +
          decltype(AndroidMultiuserMetric_EventData::_impl_.cpu_usage_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(AndroidMultiuserMetric_EventData), alignof(AndroidMultiuserMetric_EventData), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&AndroidMultiuserMetric_EventData::PlacementNew_,
                                 sizeof(AndroidMultiuserMetric_EventData),
                                 alignof(AndroidMultiuserMetric_EventData));
  }
}
#endif
constexpr auto AndroidMultiuserMetric_EventData::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_AndroidMultiuserMetric_EventData_default_instance_._instance,
          &_table_.header,
          nullptr,  // IsInitialized
          &AndroidMultiuserMetric_EventData::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<AndroidMultiuserMetric_EventData>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &AndroidMultiuserMetric_EventData::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<AndroidMultiuserMetric_EventData>(), &AndroidMultiuserMetric_EventData::ByteSizeLong,
              &AndroidMultiuserMetric_EventData::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(AndroidMultiuserMetric_EventData, _impl_._cached_size_),
          false,
      },
      &AndroidMultiuserMetric_EventData::kDescriptorMethods,
      &descriptor_table_protos_2fperfetto_2fmetrics_2fandroid_2fmultiuser_5fmetric_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull AndroidMultiuserMetric_EventData_class_data_ =
        AndroidMultiuserMetric_EventData::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
AndroidMultiuserMetric_EventData::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&AndroidMultiuserMetric_EventData_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(AndroidMultiuserMetric_EventData_class_data_.tc_table);
  return AndroidMultiuserMetric_EventData_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 0, 2>
AndroidMultiuserMetric_EventData::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(AndroidMultiuserMetric_EventData, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    AndroidMultiuserMetric_EventData_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::perfetto::protos::AndroidMultiuserMetric_EventData>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .perfetto.protos.AndroidMultiuserMetric.EventData.CpuUsage cpu_usage = 2;
    {::_pbi::TcParser::FastMtR1,
     {18, 0, 0,
      PROTOBUF_FIELD_OFFSET(AndroidMultiuserMetric_EventData, _impl_.cpu_usage_)}},
    // optional int32 duration_ms = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(AndroidMultiuserMetric_EventData, _impl_.duration_ms_), 1>(),
     {8, 1, 0,
      PROTOBUF_FIELD_OFFSET(AndroidMultiuserMetric_EventData, _impl_.duration_ms_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional int32 duration_ms = 1;
    {PROTOBUF_FIELD_OFFSET(AndroidMultiuserMetric_EventData, _impl_.duration_ms_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // repeated .perfetto.protos.AndroidMultiuserMetric.EventData.CpuUsage cpu_usage = 2;
    {PROTOBUF_FIELD_OFFSET(AndroidMultiuserMetric_EventData, _impl_.cpu_usage_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::perfetto::protos::AndroidMultiuserMetric_EventData_CpuUsage>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void AndroidMultiuserMetric_EventData::Clear() {
// @@protoc_insertion_point(message_clear_start:perfetto.protos.AndroidMultiuserMetric.EventData)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    _impl_.cpu_usage_.Clear();
  }
  _impl_.duration_ms_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL AndroidMultiuserMetric_EventData::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const AndroidMultiuserMetric_EventData& this_ = static_cast<const AndroidMultiuserMetric_EventData&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL AndroidMultiuserMetric_EventData::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const AndroidMultiuserMetric_EventData& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:perfetto.protos.AndroidMultiuserMetric.EventData)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional int32 duration_ms = 1;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<1>(
            stream, this_._internal_duration_ms(), target);
  }

  // repeated .perfetto.protos.AndroidMultiuserMetric.EventData.CpuUsage cpu_usage = 2;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    for (unsigned i = 0, n = static_cast<unsigned>(
                             this_._internal_cpu_usage_size());
         i < n; i++) {
      const auto& repfield = this_._internal_cpu_usage().Get(i);
      target =
          ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
              2, repfield, repfield.GetCachedSize(),
              target, stream);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:perfetto.protos.AndroidMultiuserMetric.EventData)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t AndroidMultiuserMetric_EventData::ByteSizeLong(const MessageLite& base) {
  const AndroidMultiuserMetric_EventData& this_ = static_cast<const AndroidMultiuserMetric_EventData&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t AndroidMultiuserMetric_EventData::ByteSizeLong() const {
  const AndroidMultiuserMetric_EventData& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:perfetto.protos.AndroidMultiuserMetric.EventData)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // repeated .perfetto.protos.AndroidMultiuserMetric.EventData.CpuUsage cpu_usage = 2;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      total_size += 1UL * this_._internal_cpu_usage_size();
      for (const auto& msg : this_._internal_cpu_usage()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
    // optional int32 duration_ms = 1;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this_._internal_duration_ms());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void AndroidMultiuserMetric_EventData::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<AndroidMultiuserMetric_EventData*>(&to_msg);
  auto& from = static_cast<const AndroidMultiuserMetric_EventData&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:perfetto.protos.AndroidMultiuserMetric.EventData)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _this->_internal_mutable_cpu_usage()->InternalMergeFromWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), arena,
          from._internal_cpu_usage());
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _this->_impl_.duration_ms_ = from._impl_.duration_ms_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void AndroidMultiuserMetric_EventData::CopyFrom(const AndroidMultiuserMetric_EventData& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:perfetto.protos.AndroidMultiuserMetric.EventData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void AndroidMultiuserMetric_EventData::InternalSwap(AndroidMultiuserMetric_EventData* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.cpu_usage_.InternalSwap(&other->_impl_.cpu_usage_);
  swap(_impl_.duration_ms_, other->_impl_.duration_ms_);
}

::google::protobuf::Metadata AndroidMultiuserMetric_EventData::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class AndroidMultiuserMetric::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<AndroidMultiuserMetric>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(AndroidMultiuserMetric, _impl_._has_bits_);
};

AndroidMultiuserMetric::AndroidMultiuserMetric(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, AndroidMultiuserMetric_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:perfetto.protos.AndroidMultiuserMetric)
}
PROTOBUF_NDEBUG_INLINE AndroidMultiuserMetric::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::perfetto::protos::AndroidMultiuserMetric& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

AndroidMultiuserMetric::AndroidMultiuserMetric(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const AndroidMultiuserMetric& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, AndroidMultiuserMetric_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  AndroidMultiuserMetric* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.user_switch_ = (CheckHasBit(cached_has_bits, 0x00000001U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.user_switch_)
                : nullptr;

  // @@protoc_insertion_point(copy_constructor:perfetto.protos.AndroidMultiuserMetric)
}
PROTOBUF_NDEBUG_INLINE AndroidMultiuserMetric::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void AndroidMultiuserMetric::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.user_switch_ = {};
}
AndroidMultiuserMetric::~AndroidMultiuserMetric() {
  // @@protoc_insertion_point(destructor:perfetto.protos.AndroidMultiuserMetric)
  SharedDtor(*this);
}
inline void AndroidMultiuserMetric::SharedDtor(MessageLite& self) {
  AndroidMultiuserMetric& this_ = static_cast<AndroidMultiuserMetric&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.user_switch_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL AndroidMultiuserMetric::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) AndroidMultiuserMetric(arena);
}
constexpr auto AndroidMultiuserMetric::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(AndroidMultiuserMetric),
                                            alignof(AndroidMultiuserMetric));
}
constexpr auto AndroidMultiuserMetric::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_AndroidMultiuserMetric_default_instance_._instance,
          &_table_.header,
          nullptr,  // IsInitialized
          &AndroidMultiuserMetric::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<AndroidMultiuserMetric>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &AndroidMultiuserMetric::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<AndroidMultiuserMetric>(), &AndroidMultiuserMetric::ByteSizeLong,
              &AndroidMultiuserMetric::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(AndroidMultiuserMetric, _impl_._cached_size_),
          false,
      },
      &AndroidMultiuserMetric::kDescriptorMethods,
      &descriptor_table_protos_2fperfetto_2fmetrics_2fandroid_2fmultiuser_5fmetric_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull AndroidMultiuserMetric_class_data_ =
        AndroidMultiuserMetric::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
AndroidMultiuserMetric::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&AndroidMultiuserMetric_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(AndroidMultiuserMetric_class_data_.tc_table);
  return AndroidMultiuserMetric_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2>
AndroidMultiuserMetric::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(AndroidMultiuserMetric, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    AndroidMultiuserMetric_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::perfetto::protos::AndroidMultiuserMetric>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // optional .perfetto.protos.AndroidMultiuserMetric.EventData user_switch = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(AndroidMultiuserMetric, _impl_.user_switch_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional .perfetto.protos.AndroidMultiuserMetric.EventData user_switch = 1;
    {PROTOBUF_FIELD_OFFSET(AndroidMultiuserMetric, _impl_.user_switch_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::perfetto::protos::AndroidMultiuserMetric_EventData>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void AndroidMultiuserMetric::Clear() {
// @@protoc_insertion_point(message_clear_start:perfetto.protos.AndroidMultiuserMetric)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    ABSL_DCHECK(_impl_.user_switch_ != nullptr);
    _impl_.user_switch_->Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL AndroidMultiuserMetric::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const AndroidMultiuserMetric& this_ = static_cast<const AndroidMultiuserMetric&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL AndroidMultiuserMetric::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const AndroidMultiuserMetric& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:perfetto.protos.AndroidMultiuserMetric)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional .perfetto.protos.AndroidMultiuserMetric.EventData user_switch = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        1, *this_._impl_.user_switch_, this_._impl_.user_switch_->GetCachedSize(), target,
        stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:perfetto.protos.AndroidMultiuserMetric)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t AndroidMultiuserMetric::ByteSizeLong(const MessageLite& base) {
  const AndroidMultiuserMetric& this_ = static_cast<const AndroidMultiuserMetric&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t AndroidMultiuserMetric::ByteSizeLong() const {
  const AndroidMultiuserMetric& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:perfetto.protos.AndroidMultiuserMetric)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // optional .perfetto.protos.AndroidMultiuserMetric.EventData user_switch = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.user_switch_);
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void AndroidMultiuserMetric::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<AndroidMultiuserMetric*>(&to_msg);
  auto& from = static_cast<const AndroidMultiuserMetric&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:perfetto.protos.AndroidMultiuserMetric)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    ABSL_DCHECK(from._impl_.user_switch_ != nullptr);
    if (_this->_impl_.user_switch_ == nullptr) {
      _this->_impl_.user_switch_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.user_switch_);
    } else {
      _this->_impl_.user_switch_->MergeFrom(*from._impl_.user_switch_);
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void AndroidMultiuserMetric::CopyFrom(const AndroidMultiuserMetric& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:perfetto.protos.AndroidMultiuserMetric)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void AndroidMultiuserMetric::InternalSwap(AndroidMultiuserMetric* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.user_switch_, other->_impl_.user_switch_);
}

::google::protobuf::Metadata AndroidMultiuserMetric::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace protos
}  // namespace perfetto
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_protos_2fperfetto_2fmetrics_2fandroid_2fmultiuser_5fmetric_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
