// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protos/perfetto/common/semantic_type.proto
// Protobuf C++ Version: 7.34.0

#ifndef protos_2fperfetto_2fcommon_2fsemantic_5ftype_2eproto_2epb_2eh
#define protos_2fperfetto_2fcommon_2fsemantic_5ftype_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

// clang-format off
#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 7034000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_protos_2fperfetto_2fcommon_2fsemantic_5ftype_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_protos_2fperfetto_2fcommon_2fsemantic_5ftype_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_protos_2fperfetto_2fcommon_2fsemantic_5ftype_2eproto;
}  // extern "C"
namespace perfetto {
namespace protos {
enum SemanticType : int;
extern const uint32_t SemanticType_internal_data_[];
}  // namespace protos
}  // namespace perfetto
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::perfetto::protos::SemanticType_internal_data_>
    internal::EnumTraitsImpl::value<::perfetto::protos::SemanticType>;
}  // namespace protobuf
}  // namespace google

namespace perfetto {
namespace protos {
enum SemanticType : int {
  SEMANTIC_TYPE_UNSPECIFIED = 0,
  SEMANTIC_TYPE_ATRACE = 1,
  SEMANTIC_TYPE_JOB = 2,
  SEMANTIC_TYPE_WAKELOCK = 3,
};

extern const uint32_t SemanticType_internal_data_[];
inline constexpr SemanticType SemanticType_MIN =
    static_cast<SemanticType>(0);
inline constexpr SemanticType SemanticType_MAX =
    static_cast<SemanticType>(3);
[[nodiscard]] inline bool SemanticType_IsValid(int value) {
  return 0 <= value && value <= 3;
}
inline constexpr int SemanticType_ARRAYSIZE = 3 + 1;
[[nodiscard]] const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL
SemanticType_descriptor();
[[nodiscard]] inline auto ProtobufInternalGetEnumDescriptor(SemanticType) {
  return SemanticType_descriptor();
}
template <typename T>
[[nodiscard]] const ::std::string& SemanticType_Name(T value) {
  static_assert(::std::is_same<T, SemanticType>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to SemanticType_Name().");
  return SemanticType_Name(static_cast<SemanticType>(value));
}
template <>
[[nodiscard]] inline const ::std::string& SemanticType_Name(SemanticType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<SemanticType_descriptor, 0, 3>(
      static_cast<int>(value));
}
[[nodiscard]] inline bool SemanticType_Parse(
    ::absl::string_view name, SemanticType* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<SemanticType>(SemanticType_descriptor(), name,
                                           value);
}

// ===================================================================



// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace protos
}  // namespace perfetto


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::perfetto::protos::SemanticType> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::perfetto::protos::SemanticType>() {
  return ::perfetto::protos::SemanticType_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"
// clang-format on

#endif  // protos_2fperfetto_2fcommon_2fsemantic_5ftype_2eproto_2epb_2eh
