// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protos/perfetto/config/android/cpu_per_uid_config.proto
// Protobuf C++ Version: 7.34.0

#include "protos/perfetto/config/android/cpu_per_uid_config.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/internal_visibility.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace perfetto {
namespace protos {

inline constexpr CpuPerUidConfig::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        poll_ms_{0u} {}

template <typename>
constexpr CpuPerUidConfig::CpuPerUidConfig(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(CpuPerUidConfig_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
struct CpuPerUidConfigDefaultTypeInternal {
  constexpr CpuPerUidConfigDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CpuPerUidConfigDefaultTypeInternal() {}
  union {
    CpuPerUidConfig _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CpuPerUidConfigDefaultTypeInternal _CpuPerUidConfig_default_instance_;
}  // namespace protos
}  // namespace perfetto
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_protos_2fperfetto_2fconfig_2fandroid_2fcpu_5fper_5fuid_5fconfig_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_protos_2fperfetto_2fconfig_2fandroid_2fcpu_5fper_5fuid_5fconfig_2eproto = nullptr;
const ::uint32_t
    TableStruct_protos_2fperfetto_2fconfig_2fandroid_2fcpu_5fper_5fuid_5fconfig_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::perfetto::protos::CpuPerUidConfig, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::perfetto::protos::CpuPerUidConfig, _impl_.poll_ms_),
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::perfetto::protos::CpuPerUidConfig)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::perfetto::protos::_CpuPerUidConfig_default_instance_._instance,
};
const char descriptor_table_protodef_protos_2fperfetto_2fconfig_2fandroid_2fcpu_5fper_5fuid_5fconfig_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n7protos/perfetto/config/android/cpu_per"
    "_uid_config.proto\022\017perfetto.protos\"\"\n\017Cp"
    "uPerUidConfig\022\017\n\007poll_ms\030\001 \001(\r"
};
static ::absl::once_flag descriptor_table_protos_2fperfetto_2fconfig_2fandroid_2fcpu_5fper_5fuid_5fconfig_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_protos_2fperfetto_2fconfig_2fandroid_2fcpu_5fper_5fuid_5fconfig_2eproto = {
    false,
    false,
    110,
    descriptor_table_protodef_protos_2fperfetto_2fconfig_2fandroid_2fcpu_5fper_5fuid_5fconfig_2eproto,
    "protos/perfetto/config/android/cpu_per_uid_config.proto",
    &descriptor_table_protos_2fperfetto_2fconfig_2fandroid_2fcpu_5fper_5fuid_5fconfig_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_protos_2fperfetto_2fconfig_2fandroid_2fcpu_5fper_5fuid_5fconfig_2eproto::offsets,
    file_level_enum_descriptors_protos_2fperfetto_2fconfig_2fandroid_2fcpu_5fper_5fuid_5fconfig_2eproto,
    file_level_service_descriptors_protos_2fperfetto_2fconfig_2fandroid_2fcpu_5fper_5fuid_5fconfig_2eproto,
};
namespace perfetto {
namespace protos {
// ===================================================================

class CpuPerUidConfig::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<CpuPerUidConfig>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(CpuPerUidConfig, _impl_._has_bits_);
};

CpuPerUidConfig::CpuPerUidConfig(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CpuPerUidConfig_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:perfetto.protos.CpuPerUidConfig)
}
CpuPerUidConfig::CpuPerUidConfig(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CpuPerUidConfig& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CpuPerUidConfig_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE CpuPerUidConfig::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void CpuPerUidConfig::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.poll_ms_ = {};
}
CpuPerUidConfig::~CpuPerUidConfig() {
  // @@protoc_insertion_point(destructor:perfetto.protos.CpuPerUidConfig)
  SharedDtor(*this);
}
inline void CpuPerUidConfig::SharedDtor(MessageLite& self) {
  CpuPerUidConfig& this_ = static_cast<CpuPerUidConfig&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL CpuPerUidConfig::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) CpuPerUidConfig(arena);
}
constexpr auto CpuPerUidConfig::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(CpuPerUidConfig),
                                            alignof(CpuPerUidConfig));
}
constexpr auto CpuPerUidConfig::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_CpuPerUidConfig_default_instance_._instance,
          &_table_.header,
          nullptr,  // IsInitialized
          &CpuPerUidConfig::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<CpuPerUidConfig>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &CpuPerUidConfig::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<CpuPerUidConfig>(), &CpuPerUidConfig::ByteSizeLong,
              &CpuPerUidConfig::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(CpuPerUidConfig, _impl_._cached_size_),
          false,
      },
      &CpuPerUidConfig::kDescriptorMethods,
      &descriptor_table_protos_2fperfetto_2fconfig_2fandroid_2fcpu_5fper_5fuid_5fconfig_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull CpuPerUidConfig_class_data_ =
        CpuPerUidConfig::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
CpuPerUidConfig::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&CpuPerUidConfig_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(CpuPerUidConfig_class_data_.tc_table);
  return CpuPerUidConfig_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2>
CpuPerUidConfig::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CpuPerUidConfig, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    CpuPerUidConfig_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::perfetto::protos::CpuPerUidConfig>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // optional uint32 poll_ms = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CpuPerUidConfig, _impl_.poll_ms_), 0>(),
     {8, 0, 0,
      PROTOBUF_FIELD_OFFSET(CpuPerUidConfig, _impl_.poll_ms_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional uint32 poll_ms = 1;
    {PROTOBUF_FIELD_OFFSET(CpuPerUidConfig, _impl_.poll_ms_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void CpuPerUidConfig::Clear() {
// @@protoc_insertion_point(message_clear_start:perfetto.protos.CpuPerUidConfig)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.poll_ms_ = 0u;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL CpuPerUidConfig::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const CpuPerUidConfig& this_ = static_cast<const CpuPerUidConfig&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL CpuPerUidConfig::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const CpuPerUidConfig& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:perfetto.protos.CpuPerUidConfig)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional uint32 poll_ms = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        1, this_._internal_poll_ms(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:perfetto.protos.CpuPerUidConfig)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t CpuPerUidConfig::ByteSizeLong(const MessageLite& base) {
  const CpuPerUidConfig& this_ = static_cast<const CpuPerUidConfig&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t CpuPerUidConfig::ByteSizeLong() const {
  const CpuPerUidConfig& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:perfetto.protos.CpuPerUidConfig)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // optional uint32 poll_ms = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_poll_ms());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void CpuPerUidConfig::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<CpuPerUidConfig*>(&to_msg);
  auto& from = static_cast<const CpuPerUidConfig&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:perfetto.protos.CpuPerUidConfig)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _this->_impl_.poll_ms_ = from._impl_.poll_ms_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void CpuPerUidConfig::CopyFrom(const CpuPerUidConfig& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:perfetto.protos.CpuPerUidConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CpuPerUidConfig::InternalSwap(CpuPerUidConfig* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.poll_ms_, other->_impl_.poll_ms_);
}

::google::protobuf::Metadata CpuPerUidConfig::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace protos
}  // namespace perfetto
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_protos_2fperfetto_2fconfig_2fandroid_2fcpu_5fper_5fuid_5fconfig_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
