// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protos/perfetto/config/android/surfaceflinger_transactions_config.proto
// Protobuf C++ Version: 7.34.0

#ifndef protos_2fperfetto_2fconfig_2fandroid_2fsurfaceflinger_5ftransactions_5fconfig_2eproto_2epb_2eh
#define protos_2fperfetto_2fconfig_2fandroid_2fsurfaceflinger_5ftransactions_5fconfig_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

// clang-format off
#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 7034000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_protos_2fperfetto_2fconfig_2fandroid_2fsurfaceflinger_5ftransactions_5fconfig_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_protos_2fperfetto_2fconfig_2fandroid_2fsurfaceflinger_5ftransactions_5fconfig_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_protos_2fperfetto_2fconfig_2fandroid_2fsurfaceflinger_5ftransactions_5fconfig_2eproto;
}  // extern "C"
namespace perfetto {
namespace protos {
enum SurfaceFlingerTransactionsConfig_Mode : int;
extern const uint32_t SurfaceFlingerTransactionsConfig_Mode_internal_data_[];
class SurfaceFlingerTransactionsConfig;
struct SurfaceFlingerTransactionsConfigDefaultTypeInternal;
extern SurfaceFlingerTransactionsConfigDefaultTypeInternal _SurfaceFlingerTransactionsConfig_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull SurfaceFlingerTransactionsConfig_class_data_;
}  // namespace protos
}  // namespace perfetto
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::perfetto::protos::SurfaceFlingerTransactionsConfig_Mode_internal_data_>
    internal::EnumTraitsImpl::value<::perfetto::protos::SurfaceFlingerTransactionsConfig_Mode>;
}  // namespace protobuf
}  // namespace google

namespace perfetto {
namespace protos {
enum SurfaceFlingerTransactionsConfig_Mode : int {
  SurfaceFlingerTransactionsConfig_Mode_MODE_UNSPECIFIED = 0,
  SurfaceFlingerTransactionsConfig_Mode_MODE_CONTINUOUS = 1,
  SurfaceFlingerTransactionsConfig_Mode_MODE_ACTIVE = 2,
};

extern const uint32_t SurfaceFlingerTransactionsConfig_Mode_internal_data_[];
inline constexpr SurfaceFlingerTransactionsConfig_Mode SurfaceFlingerTransactionsConfig_Mode_Mode_MIN =
    static_cast<SurfaceFlingerTransactionsConfig_Mode>(0);
inline constexpr SurfaceFlingerTransactionsConfig_Mode SurfaceFlingerTransactionsConfig_Mode_Mode_MAX =
    static_cast<SurfaceFlingerTransactionsConfig_Mode>(2);
[[nodiscard]] inline bool SurfaceFlingerTransactionsConfig_Mode_IsValid(int value) {
  return 0 <= value && value <= 2;
}
inline constexpr int SurfaceFlingerTransactionsConfig_Mode_Mode_ARRAYSIZE = 2 + 1;
[[nodiscard]] const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL
SurfaceFlingerTransactionsConfig_Mode_descriptor();
[[nodiscard]] inline auto ProtobufInternalGetEnumDescriptor(SurfaceFlingerTransactionsConfig_Mode) {
  return SurfaceFlingerTransactionsConfig_Mode_descriptor();
}
template <typename T>
[[nodiscard]] const ::std::string& SurfaceFlingerTransactionsConfig_Mode_Name(T value) {
  static_assert(::std::is_same<T, SurfaceFlingerTransactionsConfig_Mode>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to Mode_Name().");
  return SurfaceFlingerTransactionsConfig_Mode_Name(static_cast<SurfaceFlingerTransactionsConfig_Mode>(value));
}
template <>
[[nodiscard]] inline const ::std::string& SurfaceFlingerTransactionsConfig_Mode_Name(SurfaceFlingerTransactionsConfig_Mode value) {
  return ::google::protobuf::internal::NameOfDenseEnum<SurfaceFlingerTransactionsConfig_Mode_descriptor, 0, 2>(
      static_cast<int>(value));
}
[[nodiscard]] inline bool SurfaceFlingerTransactionsConfig_Mode_Parse(
    ::absl::string_view name, SurfaceFlingerTransactionsConfig_Mode* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<SurfaceFlingerTransactionsConfig_Mode>(SurfaceFlingerTransactionsConfig_Mode_descriptor(), name,
                                           value);
}

// ===================================================================


// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED SurfaceFlingerTransactionsConfig final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:perfetto.protos.SurfaceFlingerTransactionsConfig) */ {
 public:
  inline SurfaceFlingerTransactionsConfig() : SurfaceFlingerTransactionsConfig(nullptr) {}
  ~SurfaceFlingerTransactionsConfig() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SurfaceFlingerTransactionsConfig* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SurfaceFlingerTransactionsConfig));
  }
#endif

  template <typename = void>
  explicit constexpr SurfaceFlingerTransactionsConfig(::google::protobuf::internal::ConstantInitialized);

  inline SurfaceFlingerTransactionsConfig(const SurfaceFlingerTransactionsConfig& from) : SurfaceFlingerTransactionsConfig(nullptr, from) {}
  inline SurfaceFlingerTransactionsConfig(SurfaceFlingerTransactionsConfig&& from) noexcept
      : SurfaceFlingerTransactionsConfig(nullptr, ::std::move(from)) {}
  inline SurfaceFlingerTransactionsConfig& operator=(const SurfaceFlingerTransactionsConfig& from) {
    CopyFrom(from);
    return *this;
  }
  inline SurfaceFlingerTransactionsConfig& operator=(SurfaceFlingerTransactionsConfig&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const SurfaceFlingerTransactionsConfig& default_instance() {
    return *reinterpret_cast<const SurfaceFlingerTransactionsConfig*>(
        &_SurfaceFlingerTransactionsConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(SurfaceFlingerTransactionsConfig& a, SurfaceFlingerTransactionsConfig& b) { a.Swap(&b); }
  inline void Swap(SurfaceFlingerTransactionsConfig* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SurfaceFlingerTransactionsConfig* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] SurfaceFlingerTransactionsConfig* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<SurfaceFlingerTransactionsConfig>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SurfaceFlingerTransactionsConfig& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const SurfaceFlingerTransactionsConfig& from) { SurfaceFlingerTransactionsConfig::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(SurfaceFlingerTransactionsConfig* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "perfetto.protos.SurfaceFlingerTransactionsConfig"; }

  explicit SurfaceFlingerTransactionsConfig(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  SurfaceFlingerTransactionsConfig(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const SurfaceFlingerTransactionsConfig& from);
  SurfaceFlingerTransactionsConfig(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, SurfaceFlingerTransactionsConfig&& from) noexcept
      : SurfaceFlingerTransactionsConfig(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using Mode = SurfaceFlingerTransactionsConfig_Mode;
  static constexpr Mode MODE_UNSPECIFIED = SurfaceFlingerTransactionsConfig_Mode_MODE_UNSPECIFIED;
  static constexpr Mode MODE_CONTINUOUS = SurfaceFlingerTransactionsConfig_Mode_MODE_CONTINUOUS;
  static constexpr Mode MODE_ACTIVE = SurfaceFlingerTransactionsConfig_Mode_MODE_ACTIVE;
  [[nodiscard]] static inline bool Mode_IsValid(int value) {
    return SurfaceFlingerTransactionsConfig_Mode_IsValid(value);
  }
  static constexpr Mode Mode_MIN = SurfaceFlingerTransactionsConfig_Mode_Mode_MIN;
  static constexpr Mode Mode_MAX = SurfaceFlingerTransactionsConfig_Mode_Mode_MAX;
  static constexpr int Mode_ARRAYSIZE = SurfaceFlingerTransactionsConfig_Mode_Mode_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL Mode_descriptor() {
    return SurfaceFlingerTransactionsConfig_Mode_descriptor();
  }
  template <typename T>
  [[nodiscard]] static inline const ::std::string& Mode_Name(T value) {
    return SurfaceFlingerTransactionsConfig_Mode_Name(value);
  }
  [[nodiscard]] static inline bool Mode_Parse(
      ::absl::string_view name, Mode* PROTOBUF_NONNULL value) {
    return SurfaceFlingerTransactionsConfig_Mode_Parse(name, value);
  }

  // accessors -------------------------------------------------------
  enum : int {
    kModeFieldNumber = 1,
  };
  // optional .perfetto.protos.SurfaceFlingerTransactionsConfig.Mode mode = 1;
  [[nodiscard]] bool has_mode()
      const;
  void clear_mode() ;
  [[nodiscard]] ::perfetto::protos::SurfaceFlingerTransactionsConfig_Mode mode() const;
  void set_mode(::perfetto::protos::SurfaceFlingerTransactionsConfig_Mode value);

  private:
  ::perfetto::protos::SurfaceFlingerTransactionsConfig_Mode _internal_mode() const;
  void _internal_set_mode(::perfetto::protos::SurfaceFlingerTransactionsConfig_Mode value);

  public:
  // @@protoc_insertion_point(class_scope:perfetto.protos.SurfaceFlingerTransactionsConfig)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const SurfaceFlingerTransactionsConfig& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    int mode_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_protos_2fperfetto_2fconfig_2fandroid_2fsurfaceflinger_5ftransactions_5fconfig_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull SurfaceFlingerTransactionsConfig_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// SurfaceFlingerTransactionsConfig

// optional .perfetto.protos.SurfaceFlingerTransactionsConfig.Mode mode = 1;
inline bool SurfaceFlingerTransactionsConfig::has_mode() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  return value;
}
inline void SurfaceFlingerTransactionsConfig::clear_mode() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.mode_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::perfetto::protos::SurfaceFlingerTransactionsConfig_Mode SurfaceFlingerTransactionsConfig::mode() const {
  // @@protoc_insertion_point(field_get:perfetto.protos.SurfaceFlingerTransactionsConfig.mode)
  return _internal_mode();
}
inline void SurfaceFlingerTransactionsConfig::set_mode(::perfetto::protos::SurfaceFlingerTransactionsConfig_Mode value) {
  _internal_set_mode(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:perfetto.protos.SurfaceFlingerTransactionsConfig.mode)
}
inline ::perfetto::protos::SurfaceFlingerTransactionsConfig_Mode SurfaceFlingerTransactionsConfig::_internal_mode() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::perfetto::protos::SurfaceFlingerTransactionsConfig_Mode>(_impl_.mode_);
}
inline void SurfaceFlingerTransactionsConfig::_internal_set_mode(::perfetto::protos::SurfaceFlingerTransactionsConfig_Mode value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);

                                          assert(::google::protobuf::internal::ValidateEnum(
                                              value, ::perfetto::protos::SurfaceFlingerTransactionsConfig_Mode_internal_data_));
                                          _impl_.mode_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace protos
}  // namespace perfetto


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::perfetto::protos::SurfaceFlingerTransactionsConfig_Mode> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::perfetto::protos::SurfaceFlingerTransactionsConfig_Mode>() {
  return ::perfetto::protos::SurfaceFlingerTransactionsConfig_Mode_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"
// clang-format on

#endif  // protos_2fperfetto_2fconfig_2fandroid_2fsurfaceflinger_5ftransactions_5fconfig_2eproto_2epb_2eh
