// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protos/perfetto/trace/ftrace/ipi.proto
// Protobuf C++ Version: 7.34.0

#include "protos/perfetto/trace/ftrace/ipi.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/internal_visibility.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace perfetto {
namespace protos {

inline constexpr IpiRaiseFtraceEvent::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        reason_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        target_cpus_{0u} {}

template <typename>
constexpr IpiRaiseFtraceEvent::IpiRaiseFtraceEvent(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(IpiRaiseFtraceEvent_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
struct IpiRaiseFtraceEventDefaultTypeInternal {
  constexpr IpiRaiseFtraceEventDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~IpiRaiseFtraceEventDefaultTypeInternal() {}
  union {
    IpiRaiseFtraceEvent _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 IpiRaiseFtraceEventDefaultTypeInternal _IpiRaiseFtraceEvent_default_instance_;

inline constexpr IpiExitFtraceEvent::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        reason_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
constexpr IpiExitFtraceEvent::IpiExitFtraceEvent(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(IpiExitFtraceEvent_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
struct IpiExitFtraceEventDefaultTypeInternal {
  constexpr IpiExitFtraceEventDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~IpiExitFtraceEventDefaultTypeInternal() {}
  union {
    IpiExitFtraceEvent _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 IpiExitFtraceEventDefaultTypeInternal _IpiExitFtraceEvent_default_instance_;

inline constexpr IpiEntryFtraceEvent::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        reason_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
constexpr IpiEntryFtraceEvent::IpiEntryFtraceEvent(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(IpiEntryFtraceEvent_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
struct IpiEntryFtraceEventDefaultTypeInternal {
  constexpr IpiEntryFtraceEventDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~IpiEntryFtraceEventDefaultTypeInternal() {}
  union {
    IpiEntryFtraceEvent _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 IpiEntryFtraceEventDefaultTypeInternal _IpiEntryFtraceEvent_default_instance_;
}  // namespace protos
}  // namespace perfetto
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_protos_2fperfetto_2ftrace_2fftrace_2fipi_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_protos_2fperfetto_2ftrace_2fftrace_2fipi_2eproto = nullptr;
const ::uint32_t
    TableStruct_protos_2fperfetto_2ftrace_2fftrace_2fipi_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::perfetto::protos::IpiEntryFtraceEvent, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::perfetto::protos::IpiEntryFtraceEvent, _impl_.reason_),
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::perfetto::protos::IpiExitFtraceEvent, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::perfetto::protos::IpiExitFtraceEvent, _impl_.reason_),
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::perfetto::protos::IpiRaiseFtraceEvent, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::perfetto::protos::IpiRaiseFtraceEvent, _impl_.target_cpus_),
        PROTOBUF_FIELD_OFFSET(::perfetto::protos::IpiRaiseFtraceEvent, _impl_.reason_),
        1,
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::perfetto::protos::IpiEntryFtraceEvent)},
        {5, sizeof(::perfetto::protos::IpiExitFtraceEvent)},
        {10, sizeof(::perfetto::protos::IpiRaiseFtraceEvent)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::perfetto::protos::_IpiEntryFtraceEvent_default_instance_._instance,
    &::perfetto::protos::_IpiExitFtraceEvent_default_instance_._instance,
    &::perfetto::protos::_IpiRaiseFtraceEvent_default_instance_._instance,
};
const char descriptor_table_protodef_protos_2fperfetto_2ftrace_2fftrace_2fipi_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n&protos/perfetto/trace/ftrace/ipi.proto"
    "\022\017perfetto.protos\"%\n\023IpiEntryFtraceEvent"
    "\022\016\n\006reason\030\001 \001(\t\"$\n\022IpiExitFtraceEvent\022\016"
    "\n\006reason\030\001 \001(\t\":\n\023IpiRaiseFtraceEvent\022\023\n"
    "\013target_cpus\030\001 \001(\r\022\016\n\006reason\030\002 \001(\t"
};
static ::absl::once_flag descriptor_table_protos_2fperfetto_2ftrace_2fftrace_2fipi_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_protos_2fperfetto_2ftrace_2fftrace_2fipi_2eproto = {
    false,
    false,
    194,
    descriptor_table_protodef_protos_2fperfetto_2ftrace_2fftrace_2fipi_2eproto,
    "protos/perfetto/trace/ftrace/ipi.proto",
    &descriptor_table_protos_2fperfetto_2ftrace_2fftrace_2fipi_2eproto_once,
    nullptr,
    0,
    3,
    schemas,
    file_default_instances,
    TableStruct_protos_2fperfetto_2ftrace_2fftrace_2fipi_2eproto::offsets,
    file_level_enum_descriptors_protos_2fperfetto_2ftrace_2fftrace_2fipi_2eproto,
    file_level_service_descriptors_protos_2fperfetto_2ftrace_2fftrace_2fipi_2eproto,
};
namespace perfetto {
namespace protos {
// ===================================================================

class IpiEntryFtraceEvent::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<IpiEntryFtraceEvent>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(IpiEntryFtraceEvent, _impl_._has_bits_);
};

IpiEntryFtraceEvent::IpiEntryFtraceEvent(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, IpiEntryFtraceEvent_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:perfetto.protos.IpiEntryFtraceEvent)
}
PROTOBUF_NDEBUG_INLINE IpiEntryFtraceEvent::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::perfetto::protos::IpiEntryFtraceEvent& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        reason_(arena, from.reason_) {}

IpiEntryFtraceEvent::IpiEntryFtraceEvent(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const IpiEntryFtraceEvent& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, IpiEntryFtraceEvent_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  IpiEntryFtraceEvent* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:perfetto.protos.IpiEntryFtraceEvent)
}
PROTOBUF_NDEBUG_INLINE IpiEntryFtraceEvent::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        reason_(arena) {}

inline void IpiEntryFtraceEvent::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
IpiEntryFtraceEvent::~IpiEntryFtraceEvent() {
  // @@protoc_insertion_point(destructor:perfetto.protos.IpiEntryFtraceEvent)
  SharedDtor(*this);
}
inline void IpiEntryFtraceEvent::SharedDtor(MessageLite& self) {
  IpiEntryFtraceEvent& this_ = static_cast<IpiEntryFtraceEvent&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.reason_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL IpiEntryFtraceEvent::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) IpiEntryFtraceEvent(arena);
}
constexpr auto IpiEntryFtraceEvent::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(IpiEntryFtraceEvent),
                                            alignof(IpiEntryFtraceEvent));
}
constexpr auto IpiEntryFtraceEvent::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_IpiEntryFtraceEvent_default_instance_._instance,
          &_table_.header,
          nullptr,  // IsInitialized
          &IpiEntryFtraceEvent::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<IpiEntryFtraceEvent>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &IpiEntryFtraceEvent::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<IpiEntryFtraceEvent>(), &IpiEntryFtraceEvent::ByteSizeLong,
              &IpiEntryFtraceEvent::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(IpiEntryFtraceEvent, _impl_._cached_size_),
          false,
      },
      &IpiEntryFtraceEvent::kDescriptorMethods,
      &descriptor_table_protos_2fperfetto_2ftrace_2fftrace_2fipi_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull IpiEntryFtraceEvent_class_data_ =
        IpiEntryFtraceEvent::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
IpiEntryFtraceEvent::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&IpiEntryFtraceEvent_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(IpiEntryFtraceEvent_class_data_.tc_table);
  return IpiEntryFtraceEvent_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2>
IpiEntryFtraceEvent::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(IpiEntryFtraceEvent, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    IpiEntryFtraceEvent_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::perfetto::protos::IpiEntryFtraceEvent>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // optional string reason = 1;
    {::_pbi::TcParser::FastBS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(IpiEntryFtraceEvent, _impl_.reason_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional string reason = 1;
    {PROTOBUF_FIELD_OFFSET(IpiEntryFtraceEvent, _impl_.reason_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void IpiEntryFtraceEvent::Clear() {
// @@protoc_insertion_point(message_clear_start:perfetto.protos.IpiEntryFtraceEvent)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _impl_.reason_.ClearNonDefaultToEmpty();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL IpiEntryFtraceEvent::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const IpiEntryFtraceEvent& this_ = static_cast<const IpiEntryFtraceEvent&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL IpiEntryFtraceEvent::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const IpiEntryFtraceEvent& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:perfetto.protos.IpiEntryFtraceEvent)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional string reason = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    const ::std::string& _s = this_._internal_reason();
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:perfetto.protos.IpiEntryFtraceEvent)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t IpiEntryFtraceEvent::ByteSizeLong(const MessageLite& base) {
  const IpiEntryFtraceEvent& this_ = static_cast<const IpiEntryFtraceEvent&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t IpiEntryFtraceEvent::ByteSizeLong() const {
  const IpiEntryFtraceEvent& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:perfetto.protos.IpiEntryFtraceEvent)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // optional string reason = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_reason());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void IpiEntryFtraceEvent::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<IpiEntryFtraceEvent*>(&to_msg);
  auto& from = static_cast<const IpiEntryFtraceEvent&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:perfetto.protos.IpiEntryFtraceEvent)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _this->_internal_set_reason(from._internal_reason());
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void IpiEntryFtraceEvent::CopyFrom(const IpiEntryFtraceEvent& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:perfetto.protos.IpiEntryFtraceEvent)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void IpiEntryFtraceEvent::InternalSwap(IpiEntryFtraceEvent* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.reason_, &other->_impl_.reason_, arena);
}

::google::protobuf::Metadata IpiEntryFtraceEvent::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class IpiExitFtraceEvent::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<IpiExitFtraceEvent>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(IpiExitFtraceEvent, _impl_._has_bits_);
};

IpiExitFtraceEvent::IpiExitFtraceEvent(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, IpiExitFtraceEvent_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:perfetto.protos.IpiExitFtraceEvent)
}
PROTOBUF_NDEBUG_INLINE IpiExitFtraceEvent::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::perfetto::protos::IpiExitFtraceEvent& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        reason_(arena, from.reason_) {}

IpiExitFtraceEvent::IpiExitFtraceEvent(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const IpiExitFtraceEvent& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, IpiExitFtraceEvent_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  IpiExitFtraceEvent* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:perfetto.protos.IpiExitFtraceEvent)
}
PROTOBUF_NDEBUG_INLINE IpiExitFtraceEvent::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        reason_(arena) {}

inline void IpiExitFtraceEvent::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
IpiExitFtraceEvent::~IpiExitFtraceEvent() {
  // @@protoc_insertion_point(destructor:perfetto.protos.IpiExitFtraceEvent)
  SharedDtor(*this);
}
inline void IpiExitFtraceEvent::SharedDtor(MessageLite& self) {
  IpiExitFtraceEvent& this_ = static_cast<IpiExitFtraceEvent&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.reason_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL IpiExitFtraceEvent::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) IpiExitFtraceEvent(arena);
}
constexpr auto IpiExitFtraceEvent::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(IpiExitFtraceEvent),
                                            alignof(IpiExitFtraceEvent));
}
constexpr auto IpiExitFtraceEvent::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_IpiExitFtraceEvent_default_instance_._instance,
          &_table_.header,
          nullptr,  // IsInitialized
          &IpiExitFtraceEvent::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<IpiExitFtraceEvent>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &IpiExitFtraceEvent::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<IpiExitFtraceEvent>(), &IpiExitFtraceEvent::ByteSizeLong,
              &IpiExitFtraceEvent::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(IpiExitFtraceEvent, _impl_._cached_size_),
          false,
      },
      &IpiExitFtraceEvent::kDescriptorMethods,
      &descriptor_table_protos_2fperfetto_2ftrace_2fftrace_2fipi_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull IpiExitFtraceEvent_class_data_ =
        IpiExitFtraceEvent::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
IpiExitFtraceEvent::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&IpiExitFtraceEvent_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(IpiExitFtraceEvent_class_data_.tc_table);
  return IpiExitFtraceEvent_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2>
IpiExitFtraceEvent::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(IpiExitFtraceEvent, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    IpiExitFtraceEvent_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::perfetto::protos::IpiExitFtraceEvent>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // optional string reason = 1;
    {::_pbi::TcParser::FastBS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(IpiExitFtraceEvent, _impl_.reason_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional string reason = 1;
    {PROTOBUF_FIELD_OFFSET(IpiExitFtraceEvent, _impl_.reason_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void IpiExitFtraceEvent::Clear() {
// @@protoc_insertion_point(message_clear_start:perfetto.protos.IpiExitFtraceEvent)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _impl_.reason_.ClearNonDefaultToEmpty();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL IpiExitFtraceEvent::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const IpiExitFtraceEvent& this_ = static_cast<const IpiExitFtraceEvent&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL IpiExitFtraceEvent::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const IpiExitFtraceEvent& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:perfetto.protos.IpiExitFtraceEvent)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional string reason = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    const ::std::string& _s = this_._internal_reason();
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:perfetto.protos.IpiExitFtraceEvent)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t IpiExitFtraceEvent::ByteSizeLong(const MessageLite& base) {
  const IpiExitFtraceEvent& this_ = static_cast<const IpiExitFtraceEvent&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t IpiExitFtraceEvent::ByteSizeLong() const {
  const IpiExitFtraceEvent& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:perfetto.protos.IpiExitFtraceEvent)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // optional string reason = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_reason());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void IpiExitFtraceEvent::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<IpiExitFtraceEvent*>(&to_msg);
  auto& from = static_cast<const IpiExitFtraceEvent&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:perfetto.protos.IpiExitFtraceEvent)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _this->_internal_set_reason(from._internal_reason());
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void IpiExitFtraceEvent::CopyFrom(const IpiExitFtraceEvent& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:perfetto.protos.IpiExitFtraceEvent)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void IpiExitFtraceEvent::InternalSwap(IpiExitFtraceEvent* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.reason_, &other->_impl_.reason_, arena);
}

::google::protobuf::Metadata IpiExitFtraceEvent::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class IpiRaiseFtraceEvent::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<IpiRaiseFtraceEvent>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(IpiRaiseFtraceEvent, _impl_._has_bits_);
};

IpiRaiseFtraceEvent::IpiRaiseFtraceEvent(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, IpiRaiseFtraceEvent_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:perfetto.protos.IpiRaiseFtraceEvent)
}
PROTOBUF_NDEBUG_INLINE IpiRaiseFtraceEvent::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::perfetto::protos::IpiRaiseFtraceEvent& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        reason_(arena, from.reason_) {}

IpiRaiseFtraceEvent::IpiRaiseFtraceEvent(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const IpiRaiseFtraceEvent& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, IpiRaiseFtraceEvent_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  IpiRaiseFtraceEvent* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.target_cpus_ = from._impl_.target_cpus_;

  // @@protoc_insertion_point(copy_constructor:perfetto.protos.IpiRaiseFtraceEvent)
}
PROTOBUF_NDEBUG_INLINE IpiRaiseFtraceEvent::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        reason_(arena) {}

inline void IpiRaiseFtraceEvent::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.target_cpus_ = {};
}
IpiRaiseFtraceEvent::~IpiRaiseFtraceEvent() {
  // @@protoc_insertion_point(destructor:perfetto.protos.IpiRaiseFtraceEvent)
  SharedDtor(*this);
}
inline void IpiRaiseFtraceEvent::SharedDtor(MessageLite& self) {
  IpiRaiseFtraceEvent& this_ = static_cast<IpiRaiseFtraceEvent&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.reason_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL IpiRaiseFtraceEvent::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) IpiRaiseFtraceEvent(arena);
}
constexpr auto IpiRaiseFtraceEvent::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(IpiRaiseFtraceEvent),
                                            alignof(IpiRaiseFtraceEvent));
}
constexpr auto IpiRaiseFtraceEvent::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_IpiRaiseFtraceEvent_default_instance_._instance,
          &_table_.header,
          nullptr,  // IsInitialized
          &IpiRaiseFtraceEvent::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<IpiRaiseFtraceEvent>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &IpiRaiseFtraceEvent::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<IpiRaiseFtraceEvent>(), &IpiRaiseFtraceEvent::ByteSizeLong,
              &IpiRaiseFtraceEvent::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(IpiRaiseFtraceEvent, _impl_._cached_size_),
          false,
      },
      &IpiRaiseFtraceEvent::kDescriptorMethods,
      &descriptor_table_protos_2fperfetto_2ftrace_2fftrace_2fipi_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull IpiRaiseFtraceEvent_class_data_ =
        IpiRaiseFtraceEvent::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
IpiRaiseFtraceEvent::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&IpiRaiseFtraceEvent_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(IpiRaiseFtraceEvent_class_data_.tc_table);
  return IpiRaiseFtraceEvent_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2>
IpiRaiseFtraceEvent::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(IpiRaiseFtraceEvent, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    IpiRaiseFtraceEvent_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::perfetto::protos::IpiRaiseFtraceEvent>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // optional string reason = 2;
    {::_pbi::TcParser::FastBS1,
     {18, 0, 0,
      PROTOBUF_FIELD_OFFSET(IpiRaiseFtraceEvent, _impl_.reason_)}},
    // optional uint32 target_cpus = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(IpiRaiseFtraceEvent, _impl_.target_cpus_), 1>(),
     {8, 1, 0,
      PROTOBUF_FIELD_OFFSET(IpiRaiseFtraceEvent, _impl_.target_cpus_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional uint32 target_cpus = 1;
    {PROTOBUF_FIELD_OFFSET(IpiRaiseFtraceEvent, _impl_.target_cpus_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // optional string reason = 2;
    {PROTOBUF_FIELD_OFFSET(IpiRaiseFtraceEvent, _impl_.reason_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void IpiRaiseFtraceEvent::Clear() {
// @@protoc_insertion_point(message_clear_start:perfetto.protos.IpiRaiseFtraceEvent)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _impl_.reason_.ClearNonDefaultToEmpty();
  }
  _impl_.target_cpus_ = 0u;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL IpiRaiseFtraceEvent::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const IpiRaiseFtraceEvent& this_ = static_cast<const IpiRaiseFtraceEvent&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL IpiRaiseFtraceEvent::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const IpiRaiseFtraceEvent& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:perfetto.protos.IpiRaiseFtraceEvent)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional uint32 target_cpus = 1;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        1, this_._internal_target_cpus(), target);
  }

  // optional string reason = 2;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    const ::std::string& _s = this_._internal_reason();
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:perfetto.protos.IpiRaiseFtraceEvent)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t IpiRaiseFtraceEvent::ByteSizeLong(const MessageLite& base) {
  const IpiRaiseFtraceEvent& this_ = static_cast<const IpiRaiseFtraceEvent&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t IpiRaiseFtraceEvent::ByteSizeLong() const {
  const IpiRaiseFtraceEvent& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:perfetto.protos.IpiRaiseFtraceEvent)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // optional string reason = 2;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_reason());
    }
    // optional uint32 target_cpus = 1;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_target_cpus());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void IpiRaiseFtraceEvent::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<IpiRaiseFtraceEvent*>(&to_msg);
  auto& from = static_cast<const IpiRaiseFtraceEvent&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:perfetto.protos.IpiRaiseFtraceEvent)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _this->_internal_set_reason(from._internal_reason());
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _this->_impl_.target_cpus_ = from._impl_.target_cpus_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void IpiRaiseFtraceEvent::CopyFrom(const IpiRaiseFtraceEvent& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:perfetto.protos.IpiRaiseFtraceEvent)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void IpiRaiseFtraceEvent::InternalSwap(IpiRaiseFtraceEvent* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.reason_, &other->_impl_.reason_, arena);
  swap(_impl_.target_cpus_, other->_impl_.target_cpus_);
}

::google::protobuf::Metadata IpiRaiseFtraceEvent::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace protos
}  // namespace perfetto
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_protos_2fperfetto_2ftrace_2fftrace_2fipi_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
