// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protos/perfetto/trace/android/view/enums.proto
// Protobuf C++ Version: 7.34.0

#include "protos/perfetto/trace/android/view/enums.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/internal_visibility.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace perfetto {
namespace protos {
}  // namespace protos
}  // namespace perfetto
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_protos_2fperfetto_2ftrace_2fandroid_2fview_2fenums_2eproto[3];
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_protos_2fperfetto_2ftrace_2fandroid_2fview_2fenums_2eproto = nullptr;
const ::uint32_t TableStruct_protos_2fperfetto_2ftrace_2fandroid_2fview_2fenums_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* PROTOBUF_NULLABLE schemas = nullptr;
static constexpr ::_pb::Message* PROTOBUF_NONNULL const* PROTOBUF_NULLABLE
    file_default_instances = nullptr;
const char descriptor_table_protodef_protos_2fperfetto_2ftrace_2fandroid_2fview_2fenums_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n.protos/perfetto/trace/android/view/enu"
    "ms.proto\022\017perfetto.protos*\306\001\n\020DisplaySta"
    "teEnum\022\031\n\025DISPLAY_STATE_UNKNOWN\020\000\022\025\n\021DIS"
    "PLAY_STATE_OFF\020\001\022\024\n\020DISPLAY_STATE_ON\020\002\022\026"
    "\n\022DISPLAY_STATE_DOZE\020\003\022\036\n\032DISPLAY_STATE_"
    "DOZE_SUSPEND\020\004\022\024\n\020DISPLAY_STATE_VR\020\005\022\034\n\030"
    "DISPLAY_STATE_ON_SUSPEND\020\006*\260\002\n\022DisplaySt"
    "ateReason\022 \n\034DISPLAY_STATE_REASON_UNKNOW"
    "N\020\000\022\'\n#DISPLAY_STATE_REASON_DEFAULT_POLI"
    "CY\020\001\022\'\n#DISPLAY_STATE_REASON_DRAW_WAKE_L"
    "OCK\020\002\022 \n\034DISPLAY_STATE_REASON_OFFLOAD\020\003\022"
    "\035\n\031DISPLAY_STATE_REASON_TILT\020\004\022&\n\"DISPLA"
    "Y_STATE_REASON_DREAM_MANAGER\020\005\022\034\n\030DISPLA"
    "Y_STATE_REASON_KEY\020\006\022\037\n\033DISPLAY_STATE_RE"
    "ASON_MOTION\020\007*\334\005\n\022TransitionTypeEnum\022\020\n\014"
    "TRANSIT_NONE\020\000\022\032\n\rTRANSIT_UNSET\020\377\377\377\377\377\377\377\377"
    "\377\001\022\031\n\025TRANSIT_ACTIVITY_OPEN\020\006\022\032\n\026TRANSIT"
    "_ACTIVITY_CLOSE\020\007\022\025\n\021TRANSIT_TASK_OPEN\020\010"
    "\022\026\n\022TRANSIT_TASK_CLOSE\020\t\022\031\n\025TRANSIT_TASK"
    "_TO_FRONT\020\n\022\030\n\024TRANSIT_TASK_TO_BACK\020\013\022\033\n"
    "\027TRANSIT_WALLPAPER_CLOSE\020\014\022\032\n\026TRANSIT_WA"
    "LLPAPER_OPEN\020\r\022 \n\034TRANSIT_WALLPAPER_INTR"
    "A_OPEN\020\016\022!\n\035TRANSIT_WALLPAPER_INTRA_CLOS"
    "E\020\017\022\034\n\030TRANSIT_TASK_OPEN_BEHIND\020\020\022\031\n\025TRA"
    "NSIT_TASK_IN_PLACE\020\021\022\035\n\031TRANSIT_ACTIVITY"
    "_RELAUNCH\020\022\022&\n\036TRANSIT_DOCK_TASK_FROM_RE"
    "CENTS\020\023\032\002\010\001\022\037\n\033TRANSIT_KEYGUARD_GOING_AW"
    "AY\020\024\022,\n(TRANSIT_KEYGUARD_GOING_AWAY_ON_W"
    "ALLPAPER\020\025\022\034\n\030TRANSIT_KEYGUARD_OCCLUDE\020\026"
    "\022\036\n\032TRANSIT_KEYGUARD_UNOCCLUDE\020\027\022%\n!TRAN"
    "SIT_TRANSLUCENT_ACTIVITY_OPEN\020\030\022&\n\"TRANS"
    "IT_TRANSLUCENT_ACTIVITY_CLOSE\020\031\022#\n\037TRANS"
    "IT_CRASHING_ACTIVITY_CLOSE\020\032"
};
static ::absl::once_flag descriptor_table_protos_2fperfetto_2ftrace_2fandroid_2fview_2fenums_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_protos_2fperfetto_2ftrace_2fandroid_2fview_2fenums_2eproto = {
    false,
    false,
    1308,
    descriptor_table_protodef_protos_2fperfetto_2ftrace_2fandroid_2fview_2fenums_2eproto,
    "protos/perfetto/trace/android/view/enums.proto",
    &descriptor_table_protos_2fperfetto_2ftrace_2fandroid_2fview_2fenums_2eproto_once,
    nullptr,
    0,
    0,
    schemas,
    file_default_instances,
    TableStruct_protos_2fperfetto_2ftrace_2fandroid_2fview_2fenums_2eproto::offsets,
    file_level_enum_descriptors_protos_2fperfetto_2ftrace_2fandroid_2fview_2fenums_2eproto,
    file_level_service_descriptors_protos_2fperfetto_2ftrace_2fandroid_2fview_2fenums_2eproto,
};
namespace perfetto {
namespace protos {
[[nodiscard]] const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL
DisplayStateEnum_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_protos_2fperfetto_2ftrace_2fandroid_2fview_2fenums_2eproto);
  return file_level_enum_descriptors_protos_2fperfetto_2ftrace_2fandroid_2fview_2fenums_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t DisplayStateEnum_internal_data_[] = {
    458752u, 0u, };
[[nodiscard]] const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL
DisplayStateReason_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_protos_2fperfetto_2ftrace_2fandroid_2fview_2fenums_2eproto);
  return file_level_enum_descriptors_protos_2fperfetto_2ftrace_2fandroid_2fview_2fenums_2eproto[1];
}
PROTOBUF_CONSTINIT const uint32_t DisplayStateReason_internal_data_[] = {
    524288u, 0u, };
[[nodiscard]] const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL
TransitionTypeEnum_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_protos_2fperfetto_2ftrace_2fandroid_2fview_2fenums_2eproto);
  return file_level_enum_descriptors_protos_2fperfetto_2ftrace_2fandroid_2fview_2fenums_2eproto[2];
}
PROTOBUF_CONSTINIT const uint32_t TransitionTypeEnum_internal_data_[] = {
    196607u, 32u, 67108832u, };
// @@protoc_insertion_point(namespace_scope)
}  // namespace protos
}  // namespace perfetto
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_protos_2fperfetto_2ftrace_2fandroid_2fview_2fenums_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
