// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protos/perfetto/trace/android/view/imefocuscontroller.proto
// Protobuf C++ Version: 7.34.0

#include "protos/perfetto/trace/android/view/imefocuscontroller.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/internal_visibility.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace perfetto {
namespace protos {

inline constexpr ImeFocusControllerProto::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        served_view_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        next_served_view_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        has_ime_focus_{false} {}

template <typename>
constexpr ImeFocusControllerProto::ImeFocusControllerProto(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(ImeFocusControllerProto_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
struct ImeFocusControllerProtoDefaultTypeInternal {
  constexpr ImeFocusControllerProtoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ImeFocusControllerProtoDefaultTypeInternal() {}
  union {
    ImeFocusControllerProto _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ImeFocusControllerProtoDefaultTypeInternal _ImeFocusControllerProto_default_instance_;
}  // namespace protos
}  // namespace perfetto
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_protos_2fperfetto_2ftrace_2fandroid_2fview_2fimefocuscontroller_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_protos_2fperfetto_2ftrace_2fandroid_2fview_2fimefocuscontroller_2eproto = nullptr;
const ::uint32_t
    TableStruct_protos_2fperfetto_2ftrace_2fandroid_2fview_2fimefocuscontroller_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::perfetto::protos::ImeFocusControllerProto, _impl_._has_bits_),
        6, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::perfetto::protos::ImeFocusControllerProto, _impl_.has_ime_focus_),
        PROTOBUF_FIELD_OFFSET(::perfetto::protos::ImeFocusControllerProto, _impl_.served_view_),
        PROTOBUF_FIELD_OFFSET(::perfetto::protos::ImeFocusControllerProto, _impl_.next_served_view_),
        2,
        0,
        1,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::perfetto::protos::ImeFocusControllerProto)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::perfetto::protos::_ImeFocusControllerProto_default_instance_._instance,
};
const char descriptor_table_protodef_protos_2fperfetto_2ftrace_2fandroid_2fview_2fimefocuscontroller_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n;protos/perfetto/trace/android/view/ime"
    "focuscontroller.proto\022\017perfetto.protos\"g"
    "\n\027ImeFocusControllerProto\022\025\n\rhas_ime_foc"
    "us\030\001 \001(\010\022\027\n\013served_view\030\002 \001(\tB\002\030\001\022\034\n\020nex"
    "t_served_view\030\003 \001(\tB\002\030\001"
};
static ::absl::once_flag descriptor_table_protos_2fperfetto_2ftrace_2fandroid_2fview_2fimefocuscontroller_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_protos_2fperfetto_2ftrace_2fandroid_2fview_2fimefocuscontroller_2eproto = {
    false,
    false,
    183,
    descriptor_table_protodef_protos_2fperfetto_2ftrace_2fandroid_2fview_2fimefocuscontroller_2eproto,
    "protos/perfetto/trace/android/view/imefocuscontroller.proto",
    &descriptor_table_protos_2fperfetto_2ftrace_2fandroid_2fview_2fimefocuscontroller_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_protos_2fperfetto_2ftrace_2fandroid_2fview_2fimefocuscontroller_2eproto::offsets,
    file_level_enum_descriptors_protos_2fperfetto_2ftrace_2fandroid_2fview_2fimefocuscontroller_2eproto,
    file_level_service_descriptors_protos_2fperfetto_2ftrace_2fandroid_2fview_2fimefocuscontroller_2eproto,
};
namespace perfetto {
namespace protos {
// ===================================================================

class ImeFocusControllerProto::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<ImeFocusControllerProto>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ImeFocusControllerProto, _impl_._has_bits_);
};

ImeFocusControllerProto::ImeFocusControllerProto(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ImeFocusControllerProto_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:perfetto.protos.ImeFocusControllerProto)
}
PROTOBUF_NDEBUG_INLINE ImeFocusControllerProto::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::perfetto::protos::ImeFocusControllerProto& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        served_view_(arena, from.served_view_),
        next_served_view_(arena, from.next_served_view_) {}

ImeFocusControllerProto::ImeFocusControllerProto(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const ImeFocusControllerProto& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ImeFocusControllerProto_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ImeFocusControllerProto* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.has_ime_focus_ = from._impl_.has_ime_focus_;

  // @@protoc_insertion_point(copy_constructor:perfetto.protos.ImeFocusControllerProto)
}
PROTOBUF_NDEBUG_INLINE ImeFocusControllerProto::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        served_view_(arena),
        next_served_view_(arena) {}

inline void ImeFocusControllerProto::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.has_ime_focus_ = {};
}
ImeFocusControllerProto::~ImeFocusControllerProto() {
  // @@protoc_insertion_point(destructor:perfetto.protos.ImeFocusControllerProto)
  SharedDtor(*this);
}
inline void ImeFocusControllerProto::SharedDtor(MessageLite& self) {
  ImeFocusControllerProto& this_ = static_cast<ImeFocusControllerProto&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.served_view_.Destroy();
  this_._impl_.next_served_view_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL ImeFocusControllerProto::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) ImeFocusControllerProto(arena);
}
constexpr auto ImeFocusControllerProto::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(ImeFocusControllerProto),
                                            alignof(ImeFocusControllerProto));
}
constexpr auto ImeFocusControllerProto::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_ImeFocusControllerProto_default_instance_._instance,
          &_table_.header,
          nullptr,  // IsInitialized
          &ImeFocusControllerProto::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<ImeFocusControllerProto>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &ImeFocusControllerProto::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<ImeFocusControllerProto>(), &ImeFocusControllerProto::ByteSizeLong,
              &ImeFocusControllerProto::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(ImeFocusControllerProto, _impl_._cached_size_),
          false,
      },
      &ImeFocusControllerProto::kDescriptorMethods,
      &descriptor_table_protos_2fperfetto_2ftrace_2fandroid_2fview_2fimefocuscontroller_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull ImeFocusControllerProto_class_data_ =
        ImeFocusControllerProto::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
ImeFocusControllerProto::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&ImeFocusControllerProto_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(ImeFocusControllerProto_class_data_.tc_table);
  return ImeFocusControllerProto_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 0, 2>
ImeFocusControllerProto::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ImeFocusControllerProto, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    ImeFocusControllerProto_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::perfetto::protos::ImeFocusControllerProto>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // optional bool has_ime_focus = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(ImeFocusControllerProto, _impl_.has_ime_focus_), 2>(),
     {8, 2, 0,
      PROTOBUF_FIELD_OFFSET(ImeFocusControllerProto, _impl_.has_ime_focus_)}},
    // optional string served_view = 2 [deprecated = true];
    {::_pbi::TcParser::FastBS1,
     {18, 0, 0,
      PROTOBUF_FIELD_OFFSET(ImeFocusControllerProto, _impl_.served_view_)}},
    // optional string next_served_view = 3 [deprecated = true];
    {::_pbi::TcParser::FastBS1,
     {26, 1, 0,
      PROTOBUF_FIELD_OFFSET(ImeFocusControllerProto, _impl_.next_served_view_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional bool has_ime_focus = 1;
    {PROTOBUF_FIELD_OFFSET(ImeFocusControllerProto, _impl_.has_ime_focus_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // optional string served_view = 2 [deprecated = true];
    {PROTOBUF_FIELD_OFFSET(ImeFocusControllerProto, _impl_.served_view_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // optional string next_served_view = 3 [deprecated = true];
    {PROTOBUF_FIELD_OFFSET(ImeFocusControllerProto, _impl_.next_served_view_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void ImeFocusControllerProto::Clear() {
// @@protoc_insertion_point(message_clear_start:perfetto.protos.ImeFocusControllerProto)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.served_view_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.next_served_view_.ClearNonDefaultToEmpty();
    }
  }
  _impl_.has_ime_focus_ = false;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL ImeFocusControllerProto::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const ImeFocusControllerProto& this_ = static_cast<const ImeFocusControllerProto&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL ImeFocusControllerProto::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const ImeFocusControllerProto& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:perfetto.protos.ImeFocusControllerProto)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional bool has_ime_focus = 1;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        1, this_._internal_has_ime_focus(), target);
  }

  // optional string served_view = 2 [deprecated = true];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    const ::std::string& _s = this_._internal_served_view();
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // optional string next_served_view = 3 [deprecated = true];
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    const ::std::string& _s = this_._internal_next_served_view();
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:perfetto.protos.ImeFocusControllerProto)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t ImeFocusControllerProto::ByteSizeLong(const MessageLite& base) {
  const ImeFocusControllerProto& this_ = static_cast<const ImeFocusControllerProto&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t ImeFocusControllerProto::ByteSizeLong() const {
  const ImeFocusControllerProto& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:perfetto.protos.ImeFocusControllerProto)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  total_size += static_cast<bool>(0x00000004U & cached_has_bits) * 2;
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // optional string served_view = 2 [deprecated = true];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_served_view());
    }
    // optional string next_served_view = 3 [deprecated = true];
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_next_served_view());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void ImeFocusControllerProto::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<ImeFocusControllerProto*>(&to_msg);
  auto& from = static_cast<const ImeFocusControllerProto&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:perfetto.protos.ImeFocusControllerProto)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _this->_internal_set_served_view(from._internal_served_view());
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _this->_internal_set_next_served_view(from._internal_next_served_view());
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _this->_impl_.has_ime_focus_ = from._impl_.has_ime_focus_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void ImeFocusControllerProto::CopyFrom(const ImeFocusControllerProto& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:perfetto.protos.ImeFocusControllerProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ImeFocusControllerProto::InternalSwap(ImeFocusControllerProto* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.served_view_, &other->_impl_.served_view_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.next_served_view_, &other->_impl_.next_served_view_, arena);
  swap(_impl_.has_ime_focus_, other->_impl_.has_ime_focus_);
}

::google::protobuf::Metadata ImeFocusControllerProto::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace protos
}  // namespace perfetto
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_protos_2fperfetto_2ftrace_2fandroid_2fview_2fimefocuscontroller_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
