// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protos/perfetto/trace/android/app_wakelock_data.proto
// Protobuf C++ Version: 7.34.0

#include "protos/perfetto/trace/android/app_wakelock_data.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/internal_visibility.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace perfetto {
namespace protos {

inline constexpr AppWakelockInfo::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        tag_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        iid_{0},
        flags_{0},
        owner_pid_{0},
        owner_uid_{0},
        work_uid_{0} {}

template <typename>
constexpr AppWakelockInfo::AppWakelockInfo(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(AppWakelockInfo_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
struct AppWakelockInfoDefaultTypeInternal {
  constexpr AppWakelockInfoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AppWakelockInfoDefaultTypeInternal() {}
  union {
    AppWakelockInfo _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AppWakelockInfoDefaultTypeInternal _AppWakelockInfo_default_instance_;

inline constexpr AppWakelockBundle::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        #ifdef PROTOBUF_INTERNAL_REMOVE_ARENA_PTRS_REPEATED_FIELD
        intern_id_{visibility, ::_pbi::InternalMetadataOffset::Build<
            ::perfetto::protos::AppWakelockBundle,
            PROTOBUF_FIELD_OFFSET(::perfetto::protos::AppWakelockBundle, _impl_.intern_id_)>()
        }
        #else
        intern_id_ {}
        #endif
        ,
        _intern_id_cached_byte_size_{0},
        #ifdef PROTOBUF_INTERNAL_REMOVE_ARENA_PTRS_REPEATED_FIELD
        encoded_ts_{visibility, ::_pbi::InternalMetadataOffset::Build<
            ::perfetto::protos::AppWakelockBundle,
            PROTOBUF_FIELD_OFFSET(::perfetto::protos::AppWakelockBundle, _impl_.encoded_ts_)>()
        }
        #else
        encoded_ts_ {}
        #endif
        ,
        _encoded_ts_cached_byte_size_{0},
        info_{nullptr},
        acquired_{false} {}

template <typename>
constexpr AppWakelockBundle::AppWakelockBundle(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(AppWakelockBundle_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
struct AppWakelockBundleDefaultTypeInternal {
  constexpr AppWakelockBundleDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AppWakelockBundleDefaultTypeInternal() {}
  union {
    AppWakelockBundle _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AppWakelockBundleDefaultTypeInternal _AppWakelockBundle_default_instance_;
}  // namespace protos
}  // namespace perfetto
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_protos_2fperfetto_2ftrace_2fandroid_2fapp_5fwakelock_5fdata_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_protos_2fperfetto_2ftrace_2fandroid_2fapp_5fwakelock_5fdata_2eproto = nullptr;
const ::uint32_t
    TableStruct_protos_2fperfetto_2ftrace_2fandroid_2fapp_5fwakelock_5fdata_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::perfetto::protos::AppWakelockInfo, _impl_._has_bits_),
        9, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::perfetto::protos::AppWakelockInfo, _impl_.iid_),
        PROTOBUF_FIELD_OFFSET(::perfetto::protos::AppWakelockInfo, _impl_.tag_),
        PROTOBUF_FIELD_OFFSET(::perfetto::protos::AppWakelockInfo, _impl_.flags_),
        PROTOBUF_FIELD_OFFSET(::perfetto::protos::AppWakelockInfo, _impl_.owner_pid_),
        PROTOBUF_FIELD_OFFSET(::perfetto::protos::AppWakelockInfo, _impl_.owner_uid_),
        PROTOBUF_FIELD_OFFSET(::perfetto::protos::AppWakelockInfo, _impl_.work_uid_),
        1,
        0,
        2,
        3,
        4,
        5,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::perfetto::protos::AppWakelockBundle, _impl_._has_bits_),
        7, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::perfetto::protos::AppWakelockBundle, _impl_.intern_id_),
        PROTOBUF_FIELD_OFFSET(::perfetto::protos::AppWakelockBundle, _impl_.encoded_ts_),
        PROTOBUF_FIELD_OFFSET(::perfetto::protos::AppWakelockBundle, _impl_.info_),
        PROTOBUF_FIELD_OFFSET(::perfetto::protos::AppWakelockBundle, _impl_.acquired_),
        0,
        1,
        2,
        3,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::perfetto::protos::AppWakelockInfo)},
        {15, sizeof(::perfetto::protos::AppWakelockBundle)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::perfetto::protos::_AppWakelockInfo_default_instance_._instance,
    &::perfetto::protos::_AppWakelockBundle_default_instance_._instance,
};
const char descriptor_table_protodef_protos_2fperfetto_2ftrace_2fandroid_2fapp_5fwakelock_5fdata_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n5protos/perfetto/trace/android/app_wake"
    "lock_data.proto\022\017perfetto.protos\"r\n\017AppW"
    "akelockInfo\022\013\n\003iid\030\001 \001(\005\022\013\n\003tag\030\002 \001(\t\022\r\n"
    "\005flags\030\003 \001(\005\022\021\n\towner_pid\030\004 \001(\005\022\021\n\towner"
    "_uid\030\005 \001(\005\022\020\n\010work_uid\030\006 \001(\005\"\204\001\n\021AppWake"
    "lockBundle\022\025\n\tintern_id\030\001 \003(\rB\002\020\001\022\026\n\nenc"
    "oded_ts\030\002 \003(\004B\002\020\001\022.\n\004info\030\003 \001(\0132 .perfet"
    "to.protos.AppWakelockInfo\022\020\n\010acquired\030\004 "
    "\001(\010"
};
static ::absl::once_flag descriptor_table_protos_2fperfetto_2ftrace_2fandroid_2fapp_5fwakelock_5fdata_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_protos_2fperfetto_2ftrace_2fandroid_2fapp_5fwakelock_5fdata_2eproto = {
    false,
    false,
    323,
    descriptor_table_protodef_protos_2fperfetto_2ftrace_2fandroid_2fapp_5fwakelock_5fdata_2eproto,
    "protos/perfetto/trace/android/app_wakelock_data.proto",
    &descriptor_table_protos_2fperfetto_2ftrace_2fandroid_2fapp_5fwakelock_5fdata_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_protos_2fperfetto_2ftrace_2fandroid_2fapp_5fwakelock_5fdata_2eproto::offsets,
    file_level_enum_descriptors_protos_2fperfetto_2ftrace_2fandroid_2fapp_5fwakelock_5fdata_2eproto,
    file_level_service_descriptors_protos_2fperfetto_2ftrace_2fandroid_2fapp_5fwakelock_5fdata_2eproto,
};
namespace perfetto {
namespace protos {
// ===================================================================

class AppWakelockInfo::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<AppWakelockInfo>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(AppWakelockInfo, _impl_._has_bits_);
};

AppWakelockInfo::AppWakelockInfo(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, AppWakelockInfo_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:perfetto.protos.AppWakelockInfo)
}
PROTOBUF_NDEBUG_INLINE AppWakelockInfo::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::perfetto::protos::AppWakelockInfo& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        tag_(arena, from.tag_) {}

AppWakelockInfo::AppWakelockInfo(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const AppWakelockInfo& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, AppWakelockInfo_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  AppWakelockInfo* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, iid_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, iid_),
           offsetof(Impl_, work_uid_) -
               offsetof(Impl_, iid_) +
               sizeof(Impl_::work_uid_));

  // @@protoc_insertion_point(copy_constructor:perfetto.protos.AppWakelockInfo)
}
PROTOBUF_NDEBUG_INLINE AppWakelockInfo::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        tag_(arena) {}

inline void AppWakelockInfo::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, iid_),
           0,
           offsetof(Impl_, work_uid_) -
               offsetof(Impl_, iid_) +
               sizeof(Impl_::work_uid_));
}
AppWakelockInfo::~AppWakelockInfo() {
  // @@protoc_insertion_point(destructor:perfetto.protos.AppWakelockInfo)
  SharedDtor(*this);
}
inline void AppWakelockInfo::SharedDtor(MessageLite& self) {
  AppWakelockInfo& this_ = static_cast<AppWakelockInfo&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.tag_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL AppWakelockInfo::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) AppWakelockInfo(arena);
}
constexpr auto AppWakelockInfo::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(AppWakelockInfo),
                                            alignof(AppWakelockInfo));
}
constexpr auto AppWakelockInfo::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_AppWakelockInfo_default_instance_._instance,
          &_table_.header,
          nullptr,  // IsInitialized
          &AppWakelockInfo::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<AppWakelockInfo>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &AppWakelockInfo::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<AppWakelockInfo>(), &AppWakelockInfo::ByteSizeLong,
              &AppWakelockInfo::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(AppWakelockInfo, _impl_._cached_size_),
          false,
      },
      &AppWakelockInfo::kDescriptorMethods,
      &descriptor_table_protos_2fperfetto_2ftrace_2fandroid_2fapp_5fwakelock_5fdata_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull AppWakelockInfo_class_data_ =
        AppWakelockInfo::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
AppWakelockInfo::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&AppWakelockInfo_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(AppWakelockInfo_class_data_.tc_table);
  return AppWakelockInfo_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 6, 0, 0, 2>
AppWakelockInfo::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(AppWakelockInfo, _impl_._has_bits_),
    0, // no _extensions_
    6, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967232,  // skipmap
    offsetof(decltype(_table_), field_entries),
    6,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    AppWakelockInfo_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::perfetto::protos::AppWakelockInfo>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // optional int32 iid = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(AppWakelockInfo, _impl_.iid_), 1>(),
     {8, 1, 0,
      PROTOBUF_FIELD_OFFSET(AppWakelockInfo, _impl_.iid_)}},
    // optional string tag = 2;
    {::_pbi::TcParser::FastBS1,
     {18, 0, 0,
      PROTOBUF_FIELD_OFFSET(AppWakelockInfo, _impl_.tag_)}},
    // optional int32 flags = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(AppWakelockInfo, _impl_.flags_), 2>(),
     {24, 2, 0,
      PROTOBUF_FIELD_OFFSET(AppWakelockInfo, _impl_.flags_)}},
    // optional int32 owner_pid = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(AppWakelockInfo, _impl_.owner_pid_), 3>(),
     {32, 3, 0,
      PROTOBUF_FIELD_OFFSET(AppWakelockInfo, _impl_.owner_pid_)}},
    // optional int32 owner_uid = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(AppWakelockInfo, _impl_.owner_uid_), 4>(),
     {40, 4, 0,
      PROTOBUF_FIELD_OFFSET(AppWakelockInfo, _impl_.owner_uid_)}},
    // optional int32 work_uid = 6;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(AppWakelockInfo, _impl_.work_uid_), 5>(),
     {48, 5, 0,
      PROTOBUF_FIELD_OFFSET(AppWakelockInfo, _impl_.work_uid_)}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // optional int32 iid = 1;
    {PROTOBUF_FIELD_OFFSET(AppWakelockInfo, _impl_.iid_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional string tag = 2;
    {PROTOBUF_FIELD_OFFSET(AppWakelockInfo, _impl_.tag_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // optional int32 flags = 3;
    {PROTOBUF_FIELD_OFFSET(AppWakelockInfo, _impl_.flags_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional int32 owner_pid = 4;
    {PROTOBUF_FIELD_OFFSET(AppWakelockInfo, _impl_.owner_pid_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional int32 owner_uid = 5;
    {PROTOBUF_FIELD_OFFSET(AppWakelockInfo, _impl_.owner_uid_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional int32 work_uid = 6;
    {PROTOBUF_FIELD_OFFSET(AppWakelockInfo, _impl_.work_uid_), _Internal::kHasBitsOffset + 5, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void AppWakelockInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:perfetto.protos.AppWakelockInfo)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _impl_.tag_.ClearNonDefaultToEmpty();
  }
  if (BatchCheckHasBit(cached_has_bits, 0x0000003eU)) {
    ::memset(&_impl_.iid_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.work_uid_) -
        reinterpret_cast<char*>(&_impl_.iid_)) + sizeof(_impl_.work_uid_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL AppWakelockInfo::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const AppWakelockInfo& this_ = static_cast<const AppWakelockInfo&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL AppWakelockInfo::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const AppWakelockInfo& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:perfetto.protos.AppWakelockInfo)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional int32 iid = 1;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<1>(
            stream, this_._internal_iid(), target);
  }

  // optional string tag = 2;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    const ::std::string& _s = this_._internal_tag();
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // optional int32 flags = 3;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<3>(
            stream, this_._internal_flags(), target);
  }

  // optional int32 owner_pid = 4;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<4>(
            stream, this_._internal_owner_pid(), target);
  }

  // optional int32 owner_uid = 5;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<5>(
            stream, this_._internal_owner_uid(), target);
  }

  // optional int32 work_uid = 6;
  if (CheckHasBit(cached_has_bits, 0x00000020U)) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<6>(
            stream, this_._internal_work_uid(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:perfetto.protos.AppWakelockInfo)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t AppWakelockInfo::ByteSizeLong(const MessageLite& base) {
  const AppWakelockInfo& this_ = static_cast<const AppWakelockInfo&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t AppWakelockInfo::ByteSizeLong() const {
  const AppWakelockInfo& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:perfetto.protos.AppWakelockInfo)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000003fU)) {
    // optional string tag = 2;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_tag());
    }
    // optional int32 iid = 1;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this_._internal_iid());
    }
    // optional int32 flags = 3;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this_._internal_flags());
    }
    // optional int32 owner_pid = 4;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this_._internal_owner_pid());
    }
    // optional int32 owner_uid = 5;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this_._internal_owner_uid());
    }
    // optional int32 work_uid = 6;
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this_._internal_work_uid());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void AppWakelockInfo::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<AppWakelockInfo*>(&to_msg);
  auto& from = static_cast<const AppWakelockInfo&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:perfetto.protos.AppWakelockInfo)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000003fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _this->_internal_set_tag(from._internal_tag());
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _this->_impl_.iid_ = from._impl_.iid_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _this->_impl_.flags_ = from._impl_.flags_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      _this->_impl_.owner_pid_ = from._impl_.owner_pid_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      _this->_impl_.owner_uid_ = from._impl_.owner_uid_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      _this->_impl_.work_uid_ = from._impl_.work_uid_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void AppWakelockInfo::CopyFrom(const AppWakelockInfo& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:perfetto.protos.AppWakelockInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void AppWakelockInfo::InternalSwap(AppWakelockInfo* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.tag_, &other->_impl_.tag_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(AppWakelockInfo, _impl_.work_uid_)
      + sizeof(AppWakelockInfo::_impl_.work_uid_)
      - PROTOBUF_FIELD_OFFSET(AppWakelockInfo, _impl_.iid_)>(
          reinterpret_cast<char*>(&_impl_.iid_),
          reinterpret_cast<char*>(&other->_impl_.iid_));
}

::google::protobuf::Metadata AppWakelockInfo::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class AppWakelockBundle::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<AppWakelockBundle>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(AppWakelockBundle, _impl_._has_bits_);
};

AppWakelockBundle::AppWakelockBundle(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, AppWakelockBundle_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:perfetto.protos.AppWakelockBundle)
}
PROTOBUF_NDEBUG_INLINE AppWakelockBundle::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::perfetto::protos::AppWakelockBundle& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        #ifdef PROTOBUF_INTERNAL_REMOVE_ARENA_PTRS_REPEATED_FIELD
        intern_id_{visibility, ::_pbi::InternalMetadataOffset::Build<
            ::perfetto::protos::AppWakelockBundle,
            PROTOBUF_FIELD_OFFSET(::perfetto::protos::AppWakelockBundle, _impl_.intern_id_)>()
        , from.intern_id_}
        #else
        intern_id_ { visibility, arena, from.intern_id_ }
        #endif
        ,
        _intern_id_cached_byte_size_{0},
        #ifdef PROTOBUF_INTERNAL_REMOVE_ARENA_PTRS_REPEATED_FIELD
        encoded_ts_{visibility, ::_pbi::InternalMetadataOffset::Build<
            ::perfetto::protos::AppWakelockBundle,
            PROTOBUF_FIELD_OFFSET(::perfetto::protos::AppWakelockBundle, _impl_.encoded_ts_)>()
        , from.encoded_ts_}
        #else
        encoded_ts_ { visibility, arena, from.encoded_ts_ }
        #endif
        ,
        _encoded_ts_cached_byte_size_{0} {}

AppWakelockBundle::AppWakelockBundle(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const AppWakelockBundle& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, AppWakelockBundle_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  AppWakelockBundle* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.info_ = (CheckHasBit(cached_has_bits, 0x00000004U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.info_)
                : nullptr;
  _impl_.acquired_ = from._impl_.acquired_;

  // @@protoc_insertion_point(copy_constructor:perfetto.protos.AppWakelockBundle)
}
PROTOBUF_NDEBUG_INLINE AppWakelockBundle::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        #ifdef PROTOBUF_INTERNAL_REMOVE_ARENA_PTRS_REPEATED_FIELD
        intern_id_{visibility, ::_pbi::InternalMetadataOffset::Build<
            ::perfetto::protos::AppWakelockBundle,
            PROTOBUF_FIELD_OFFSET(::perfetto::protos::AppWakelockBundle, _impl_.intern_id_)>()
        }
        #else
        intern_id_ { visibility, arena }
        #endif
        ,
        _intern_id_cached_byte_size_{0},
        #ifdef PROTOBUF_INTERNAL_REMOVE_ARENA_PTRS_REPEATED_FIELD
        encoded_ts_{visibility, ::_pbi::InternalMetadataOffset::Build<
            ::perfetto::protos::AppWakelockBundle,
            PROTOBUF_FIELD_OFFSET(::perfetto::protos::AppWakelockBundle, _impl_.encoded_ts_)>()
        }
        #else
        encoded_ts_ { visibility, arena }
        #endif
        ,
        _encoded_ts_cached_byte_size_{0} {}

inline void AppWakelockBundle::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, info_),
           0,
           offsetof(Impl_, acquired_) -
               offsetof(Impl_, info_) +
               sizeof(Impl_::acquired_));
}
AppWakelockBundle::~AppWakelockBundle() {
  // @@protoc_insertion_point(destructor:perfetto.protos.AppWakelockBundle)
  SharedDtor(*this);
}
inline void AppWakelockBundle::SharedDtor(MessageLite& self) {
  AppWakelockBundle& this_ = static_cast<AppWakelockBundle&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.info_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL AppWakelockBundle::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) AppWakelockBundle(arena);
}
#ifdef PROTOBUF_INTERNAL_REMOVE_ARENA_PTRS_REPEATED_PTR_FIELD
constexpr auto AppWakelockBundle::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(AppWakelockBundle),
                                            alignof(AppWakelockBundle));
}
#else  // !PROTOBUF_INTERNAL_REMOVE_ARENA_PTRS_REPEATED_PTR_FIELD
constexpr auto AppWakelockBundle::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(AppWakelockBundle, _impl_.intern_id_) +
          decltype(AppWakelockBundle::_impl_.intern_id_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(AppWakelockBundle, _impl_.encoded_ts_) +
          decltype(AppWakelockBundle::_impl_.encoded_ts_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(AppWakelockBundle), alignof(AppWakelockBundle), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&AppWakelockBundle::PlacementNew_,
                                 sizeof(AppWakelockBundle),
                                 alignof(AppWakelockBundle));
  }
}
#endif
constexpr auto AppWakelockBundle::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_AppWakelockBundle_default_instance_._instance,
          &_table_.header,
          nullptr,  // IsInitialized
          &AppWakelockBundle::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<AppWakelockBundle>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &AppWakelockBundle::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<AppWakelockBundle>(), &AppWakelockBundle::ByteSizeLong,
              &AppWakelockBundle::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(AppWakelockBundle, _impl_._cached_size_),
          false,
      },
      &AppWakelockBundle::kDescriptorMethods,
      &descriptor_table_protos_2fperfetto_2ftrace_2fandroid_2fapp_5fwakelock_5fdata_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull AppWakelockBundle_class_data_ =
        AppWakelockBundle::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
AppWakelockBundle::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&AppWakelockBundle_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(AppWakelockBundle_class_data_.tc_table);
  return AppWakelockBundle_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 1, 0, 2>
AppWakelockBundle::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(AppWakelockBundle, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    AppWakelockBundle_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::perfetto::protos::AppWakelockBundle>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // optional bool acquired = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(AppWakelockBundle, _impl_.acquired_), 3>(),
     {32, 3, 0,
      PROTOBUF_FIELD_OFFSET(AppWakelockBundle, _impl_.acquired_)}},
    // repeated uint32 intern_id = 1 [packed = true];
    {::_pbi::TcParser::FastV32P1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(AppWakelockBundle, _impl_.intern_id_)}},
    // repeated uint64 encoded_ts = 2 [packed = true];
    {::_pbi::TcParser::FastV64P1,
     {18, 1, 0,
      PROTOBUF_FIELD_OFFSET(AppWakelockBundle, _impl_.encoded_ts_)}},
    // optional .perfetto.protos.AppWakelockInfo info = 3;
    {::_pbi::TcParser::FastMtS1,
     {26, 2, 0,
      PROTOBUF_FIELD_OFFSET(AppWakelockBundle, _impl_.info_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated uint32 intern_id = 1 [packed = true];
    {PROTOBUF_FIELD_OFFSET(AppWakelockBundle, _impl_.intern_id_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcRepeated | ::_fl::kPackedUInt32)},
    // repeated uint64 encoded_ts = 2 [packed = true];
    {PROTOBUF_FIELD_OFFSET(AppWakelockBundle, _impl_.encoded_ts_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcRepeated | ::_fl::kPackedUInt64)},
    // optional .perfetto.protos.AppWakelockInfo info = 3;
    {PROTOBUF_FIELD_OFFSET(AppWakelockBundle, _impl_.info_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // optional bool acquired = 4;
    {PROTOBUF_FIELD_OFFSET(AppWakelockBundle, _impl_.acquired_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::perfetto::protos::AppWakelockInfo>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void AppWakelockBundle::Clear() {
// @@protoc_insertion_point(message_clear_start:perfetto.protos.AppWakelockBundle)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _impl_.intern_id_.Clear();
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      _impl_.encoded_ts_.Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      ABSL_DCHECK(_impl_.info_ != nullptr);
      _impl_.info_->Clear();
    }
  }
  _impl_.acquired_ = false;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL AppWakelockBundle::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const AppWakelockBundle& this_ = static_cast<const AppWakelockBundle&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL AppWakelockBundle::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const AppWakelockBundle& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:perfetto.protos.AppWakelockBundle)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // repeated uint32 intern_id = 1 [packed = true];
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    {
      int byte_size = this_._impl_._intern_id_cached_byte_size_.Get();
      if (byte_size > 0) {
        target = stream->WriteUInt32Packed(
            1, this_._internal_intern_id(), byte_size, target);
      }
    }
  }

  // repeated uint64 encoded_ts = 2 [packed = true];
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
    {
      int byte_size = this_._impl_._encoded_ts_cached_byte_size_.Get();
      if (byte_size > 0) {
        target = stream->WriteUInt64Packed(
            2, this_._internal_encoded_ts(), byte_size, target);
      }
    }
  }

  // optional .perfetto.protos.AppWakelockInfo info = 3;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        3, *this_._impl_.info_, this_._impl_.info_->GetCachedSize(), target,
        stream);
  }

  // optional bool acquired = 4;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        4, this_._internal_acquired(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:perfetto.protos.AppWakelockBundle)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t AppWakelockBundle::ByteSizeLong(const MessageLite& base) {
  const AppWakelockBundle& this_ = static_cast<const AppWakelockBundle&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t AppWakelockBundle::ByteSizeLong() const {
  const AppWakelockBundle& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:perfetto.protos.AppWakelockBundle)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  total_size += static_cast<bool>(0x00000008U & cached_has_bits) * 2;
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    // repeated uint32 intern_id = 1 [packed = true];
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      total_size +=
          ::_pbi::WireFormatLite::UInt32SizeWithPackedTagSize(
              this_._internal_intern_id(), 1,
              this_._impl_._intern_id_cached_byte_size_);
    }
    // repeated uint64 encoded_ts = 2 [packed = true];
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      total_size +=
          ::_pbi::WireFormatLite::UInt64SizeWithPackedTagSize(
              this_._internal_encoded_ts(), 1,
              this_._impl_._encoded_ts_cached_byte_size_);
    }
    // optional .perfetto.protos.AppWakelockInfo info = 3;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.info_);
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void AppWakelockBundle::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<AppWakelockBundle*>(&to_msg);
  auto& from = static_cast<const AppWakelockBundle&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:perfetto.protos.AppWakelockBundle)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _this->_internal_mutable_intern_id()->MergeFrom(from._internal_intern_id());
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      _this->_internal_mutable_encoded_ts()->MergeFrom(from._internal_encoded_ts());
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      ABSL_DCHECK(from._impl_.info_ != nullptr);
      if (_this->_impl_.info_ == nullptr) {
        _this->_impl_.info_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.info_);
      } else {
        _this->_impl_.info_->MergeFrom(*from._impl_.info_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      _this->_impl_.acquired_ = from._impl_.acquired_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void AppWakelockBundle::CopyFrom(const AppWakelockBundle& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:perfetto.protos.AppWakelockBundle)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void AppWakelockBundle::InternalSwap(AppWakelockBundle* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.intern_id_.InternalSwap(&other->_impl_.intern_id_);
  _impl_.encoded_ts_.InternalSwap(&other->_impl_.encoded_ts_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(AppWakelockBundle, _impl_.acquired_)
      + sizeof(AppWakelockBundle::_impl_.acquired_)
      - PROTOBUF_FIELD_OFFSET(AppWakelockBundle, _impl_.info_)>(
          reinterpret_cast<char*>(&_impl_.info_),
          reinterpret_cast<char*>(&other->_impl_.info_));
}

::google::protobuf::Metadata AppWakelockBundle::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace protos
}  // namespace perfetto
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_protos_2fperfetto_2ftrace_2fandroid_2fapp_5fwakelock_5fdata_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
