// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protos/perfetto/trace/android/bluetooth_trace.proto
// Protobuf C++ Version: 7.34.0

#include "protos/perfetto/trace/android/bluetooth_trace.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/internal_visibility.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace perfetto {
namespace protos {

inline constexpr BluetoothTraceEvent::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        count_{0u},
        length_{0u},
        duration_{0u},
        op_code_{0u},
        event_code_{0u},
        subevent_code_{0u},
        connection_handle_{0u},
        packet_type_{static_cast< ::perfetto::protos::BluetoothTracePacketType >(1)} {}

template <typename>
constexpr BluetoothTraceEvent::BluetoothTraceEvent(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(BluetoothTraceEvent_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
struct BluetoothTraceEventDefaultTypeInternal {
  constexpr BluetoothTraceEventDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~BluetoothTraceEventDefaultTypeInternal() {}
  union {
    BluetoothTraceEvent _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BluetoothTraceEventDefaultTypeInternal _BluetoothTraceEvent_default_instance_;
}  // namespace protos
}  // namespace perfetto
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_protos_2fperfetto_2ftrace_2fandroid_2fbluetooth_5ftrace_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_protos_2fperfetto_2ftrace_2fandroid_2fbluetooth_5ftrace_2eproto = nullptr;
const ::uint32_t
    TableStruct_protos_2fperfetto_2ftrace_2fandroid_2fbluetooth_5ftrace_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::perfetto::protos::BluetoothTraceEvent, _impl_._has_bits_),
        11, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::perfetto::protos::BluetoothTraceEvent, _impl_.packet_type_),
        PROTOBUF_FIELD_OFFSET(::perfetto::protos::BluetoothTraceEvent, _impl_.count_),
        PROTOBUF_FIELD_OFFSET(::perfetto::protos::BluetoothTraceEvent, _impl_.length_),
        PROTOBUF_FIELD_OFFSET(::perfetto::protos::BluetoothTraceEvent, _impl_.duration_),
        PROTOBUF_FIELD_OFFSET(::perfetto::protos::BluetoothTraceEvent, _impl_.op_code_),
        PROTOBUF_FIELD_OFFSET(::perfetto::protos::BluetoothTraceEvent, _impl_.event_code_),
        PROTOBUF_FIELD_OFFSET(::perfetto::protos::BluetoothTraceEvent, _impl_.subevent_code_),
        PROTOBUF_FIELD_OFFSET(::perfetto::protos::BluetoothTraceEvent, _impl_.connection_handle_),
        7,
        0,
        1,
        2,
        3,
        4,
        5,
        6,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::perfetto::protos::BluetoothTraceEvent)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::perfetto::protos::_BluetoothTraceEvent_default_instance_._instance,
};
const char descriptor_table_protodef_protos_2fperfetto_2ftrace_2fandroid_2fbluetooth_5ftrace_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n3protos/perfetto/trace/android/bluetoot"
    "h_trace.proto\022\017perfetto.protos\"\335\001\n\023Bluet"
    "oothTraceEvent\022>\n\013packet_type\030\001 \001(\0162).pe"
    "rfetto.protos.BluetoothTracePacketType\022\r"
    "\n\005count\030\002 \001(\r\022\016\n\006length\030\003 \001(\r\022\020\n\010duratio"
    "n\030\004 \001(\r\022\017\n\007op_code\030\005 \001(\r\022\022\n\nevent_code\030\006"
    " \001(\r\022\025\n\rsubevent_code\030\007 \001(\r\022\031\n\021connectio"
    "n_handle\030\010 \001(\r*\224\001\n\030BluetoothTracePacketT"
    "ype\022\013\n\007HCI_CMD\020\001\022\013\n\007HCI_EVT\020\002\022\016\n\nHCI_ACL"
    "_RX\020\003\022\016\n\nHCI_ACL_TX\020\004\022\016\n\nHCI_SCO_RX\020\005\022\016\n"
    "\nHCI_SCO_TX\020\006\022\016\n\nHCI_ISO_RX\020\007\022\016\n\nHCI_ISO"
    "_TX\020\010"
};
static ::absl::once_flag descriptor_table_protos_2fperfetto_2ftrace_2fandroid_2fbluetooth_5ftrace_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_protos_2fperfetto_2ftrace_2fandroid_2fbluetooth_5ftrace_2eproto = {
    false,
    false,
    445,
    descriptor_table_protodef_protos_2fperfetto_2ftrace_2fandroid_2fbluetooth_5ftrace_2eproto,
    "protos/perfetto/trace/android/bluetooth_trace.proto",
    &descriptor_table_protos_2fperfetto_2ftrace_2fandroid_2fbluetooth_5ftrace_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_protos_2fperfetto_2ftrace_2fandroid_2fbluetooth_5ftrace_2eproto::offsets,
    file_level_enum_descriptors_protos_2fperfetto_2ftrace_2fandroid_2fbluetooth_5ftrace_2eproto,
    file_level_service_descriptors_protos_2fperfetto_2ftrace_2fandroid_2fbluetooth_5ftrace_2eproto,
};
namespace perfetto {
namespace protos {
[[nodiscard]] const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL
BluetoothTracePacketType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_protos_2fperfetto_2ftrace_2fandroid_2fbluetooth_5ftrace_2eproto);
  return file_level_enum_descriptors_protos_2fperfetto_2ftrace_2fandroid_2fbluetooth_5ftrace_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t BluetoothTracePacketType_internal_data_[] = {
    524289u, 0u, };
// ===================================================================

class BluetoothTraceEvent::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<BluetoothTraceEvent>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(BluetoothTraceEvent, _impl_._has_bits_);
};

BluetoothTraceEvent::BluetoothTraceEvent(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, BluetoothTraceEvent_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:perfetto.protos.BluetoothTraceEvent)
}
BluetoothTraceEvent::BluetoothTraceEvent(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const BluetoothTraceEvent& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, BluetoothTraceEvent_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE BluetoothTraceEvent::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        packet_type_{static_cast< ::perfetto::protos::BluetoothTracePacketType >(1)} {}

inline void BluetoothTraceEvent::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, count_),
           0,
           offsetof(Impl_, connection_handle_) -
               offsetof(Impl_, count_) +
               sizeof(Impl_::connection_handle_));
}
BluetoothTraceEvent::~BluetoothTraceEvent() {
  // @@protoc_insertion_point(destructor:perfetto.protos.BluetoothTraceEvent)
  SharedDtor(*this);
}
inline void BluetoothTraceEvent::SharedDtor(MessageLite& self) {
  BluetoothTraceEvent& this_ = static_cast<BluetoothTraceEvent&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL BluetoothTraceEvent::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) BluetoothTraceEvent(arena);
}
constexpr auto BluetoothTraceEvent::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(BluetoothTraceEvent),
                                            alignof(BluetoothTraceEvent));
}
constexpr auto BluetoothTraceEvent::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_BluetoothTraceEvent_default_instance_._instance,
          &_table_.header,
          nullptr,  // IsInitialized
          &BluetoothTraceEvent::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<BluetoothTraceEvent>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &BluetoothTraceEvent::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<BluetoothTraceEvent>(), &BluetoothTraceEvent::ByteSizeLong,
              &BluetoothTraceEvent::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(BluetoothTraceEvent, _impl_._cached_size_),
          false,
      },
      &BluetoothTraceEvent::kDescriptorMethods,
      &descriptor_table_protos_2fperfetto_2ftrace_2fandroid_2fbluetooth_5ftrace_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull BluetoothTraceEvent_class_data_ =
        BluetoothTraceEvent::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
BluetoothTraceEvent::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&BluetoothTraceEvent_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(BluetoothTraceEvent_class_data_.tc_table);
  return BluetoothTraceEvent_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 8, 1, 0, 2>
BluetoothTraceEvent::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(BluetoothTraceEvent, _impl_._has_bits_),
    0, // no _extensions_
    8, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967040,  // skipmap
    offsetof(decltype(_table_), field_entries),
    8,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    BluetoothTraceEvent_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::perfetto::protos::BluetoothTraceEvent>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // optional uint32 connection_handle = 8;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(BluetoothTraceEvent, _impl_.connection_handle_), 6>(),
     {64, 6, 0,
      PROTOBUF_FIELD_OFFSET(BluetoothTraceEvent, _impl_.connection_handle_)}},
    // optional .perfetto.protos.BluetoothTracePacketType packet_type = 1;
    {::_pbi::TcParser::FastEr1S1,
     {8, 7, 8,
      PROTOBUF_FIELD_OFFSET(BluetoothTraceEvent, _impl_.packet_type_)}},
    // optional uint32 count = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(BluetoothTraceEvent, _impl_.count_), 0>(),
     {16, 0, 0,
      PROTOBUF_FIELD_OFFSET(BluetoothTraceEvent, _impl_.count_)}},
    // optional uint32 length = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(BluetoothTraceEvent, _impl_.length_), 1>(),
     {24, 1, 0,
      PROTOBUF_FIELD_OFFSET(BluetoothTraceEvent, _impl_.length_)}},
    // optional uint32 duration = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(BluetoothTraceEvent, _impl_.duration_), 2>(),
     {32, 2, 0,
      PROTOBUF_FIELD_OFFSET(BluetoothTraceEvent, _impl_.duration_)}},
    // optional uint32 op_code = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(BluetoothTraceEvent, _impl_.op_code_), 3>(),
     {40, 3, 0,
      PROTOBUF_FIELD_OFFSET(BluetoothTraceEvent, _impl_.op_code_)}},
    // optional uint32 event_code = 6;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(BluetoothTraceEvent, _impl_.event_code_), 4>(),
     {48, 4, 0,
      PROTOBUF_FIELD_OFFSET(BluetoothTraceEvent, _impl_.event_code_)}},
    // optional uint32 subevent_code = 7;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(BluetoothTraceEvent, _impl_.subevent_code_), 5>(),
     {56, 5, 0,
      PROTOBUF_FIELD_OFFSET(BluetoothTraceEvent, _impl_.subevent_code_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional .perfetto.protos.BluetoothTracePacketType packet_type = 1;
    {PROTOBUF_FIELD_OFFSET(BluetoothTraceEvent, _impl_.packet_type_), _Internal::kHasBitsOffset + 7, 0, (0 | ::_fl::kFcOptional | ::_fl::kEnumRange)},
    // optional uint32 count = 2;
    {PROTOBUF_FIELD_OFFSET(BluetoothTraceEvent, _impl_.count_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // optional uint32 length = 3;
    {PROTOBUF_FIELD_OFFSET(BluetoothTraceEvent, _impl_.length_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // optional uint32 duration = 4;
    {PROTOBUF_FIELD_OFFSET(BluetoothTraceEvent, _impl_.duration_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // optional uint32 op_code = 5;
    {PROTOBUF_FIELD_OFFSET(BluetoothTraceEvent, _impl_.op_code_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // optional uint32 event_code = 6;
    {PROTOBUF_FIELD_OFFSET(BluetoothTraceEvent, _impl_.event_code_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // optional uint32 subevent_code = 7;
    {PROTOBUF_FIELD_OFFSET(BluetoothTraceEvent, _impl_.subevent_code_), _Internal::kHasBitsOffset + 5, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // optional uint32 connection_handle = 8;
    {PROTOBUF_FIELD_OFFSET(BluetoothTraceEvent, _impl_.connection_handle_), _Internal::kHasBitsOffset + 6, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
  }},
  {{
      {1, 8},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void BluetoothTraceEvent::Clear() {
// @@protoc_insertion_point(message_clear_start:perfetto.protos.BluetoothTraceEvent)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    ::memset(&_impl_.count_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.connection_handle_) -
        reinterpret_cast<char*>(&_impl_.count_)) + sizeof(_impl_.connection_handle_));
    _impl_.packet_type_ = 1;
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL BluetoothTraceEvent::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const BluetoothTraceEvent& this_ = static_cast<const BluetoothTraceEvent&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL BluetoothTraceEvent::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const BluetoothTraceEvent& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:perfetto.protos.BluetoothTraceEvent)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional .perfetto.protos.BluetoothTracePacketType packet_type = 1;
  if (CheckHasBit(cached_has_bits, 0x00000080U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        1, this_._internal_packet_type(), target);
  }

  // optional uint32 count = 2;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        2, this_._internal_count(), target);
  }

  // optional uint32 length = 3;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        3, this_._internal_length(), target);
  }

  // optional uint32 duration = 4;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        4, this_._internal_duration(), target);
  }

  // optional uint32 op_code = 5;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        5, this_._internal_op_code(), target);
  }

  // optional uint32 event_code = 6;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        6, this_._internal_event_code(), target);
  }

  // optional uint32 subevent_code = 7;
  if (CheckHasBit(cached_has_bits, 0x00000020U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        7, this_._internal_subevent_code(), target);
  }

  // optional uint32 connection_handle = 8;
  if (CheckHasBit(cached_has_bits, 0x00000040U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        8, this_._internal_connection_handle(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:perfetto.protos.BluetoothTraceEvent)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t BluetoothTraceEvent::ByteSizeLong(const MessageLite& base) {
  const BluetoothTraceEvent& this_ = static_cast<const BluetoothTraceEvent&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t BluetoothTraceEvent::ByteSizeLong() const {
  const BluetoothTraceEvent& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:perfetto.protos.BluetoothTraceEvent)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    // optional uint32 count = 2;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_count());
    }
    // optional uint32 length = 3;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_length());
    }
    // optional uint32 duration = 4;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_duration());
    }
    // optional uint32 op_code = 5;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_op_code());
    }
    // optional uint32 event_code = 6;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_event_code());
    }
    // optional uint32 subevent_code = 7;
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_subevent_code());
    }
    // optional uint32 connection_handle = 8;
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_connection_handle());
    }
    // optional .perfetto.protos.BluetoothTracePacketType packet_type = 1;
    if (CheckHasBit(cached_has_bits, 0x00000080U)) {
      total_size += 1 +
                    ::_pbi::WireFormatLite::EnumSize(this_._internal_packet_type());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void BluetoothTraceEvent::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<BluetoothTraceEvent*>(&to_msg);
  auto& from = static_cast<const BluetoothTraceEvent&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:perfetto.protos.BluetoothTraceEvent)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _this->_impl_.count_ = from._impl_.count_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _this->_impl_.length_ = from._impl_.length_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _this->_impl_.duration_ = from._impl_.duration_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      _this->_impl_.op_code_ = from._impl_.op_code_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      _this->_impl_.event_code_ = from._impl_.event_code_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      _this->_impl_.subevent_code_ = from._impl_.subevent_code_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      _this->_impl_.connection_handle_ = from._impl_.connection_handle_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000080U)) {
      _this->_impl_.packet_type_ = from._impl_.packet_type_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void BluetoothTraceEvent::CopyFrom(const BluetoothTraceEvent& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:perfetto.protos.BluetoothTraceEvent)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void BluetoothTraceEvent::InternalSwap(BluetoothTraceEvent* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(BluetoothTraceEvent, _impl_.packet_type_)
      + sizeof(BluetoothTraceEvent::_impl_.packet_type_)
      - PROTOBUF_FIELD_OFFSET(BluetoothTraceEvent, _impl_.count_)>(
          reinterpret_cast<char*>(&_impl_.count_),
          reinterpret_cast<char*>(&other->_impl_.count_));
}

::google::protobuf::Metadata BluetoothTraceEvent::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace protos
}  // namespace perfetto
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_protos_2fperfetto_2ftrace_2fandroid_2fbluetooth_5ftrace_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
