// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protos/perfetto/trace/android/pixel_modem_events.proto
// Protobuf C++ Version: 7.34.0

#ifndef protos_2fperfetto_2ftrace_2fandroid_2fpixel_5fmodem_5fevents_2eproto_2epb_2eh
#define protos_2fperfetto_2ftrace_2fandroid_2fpixel_5fmodem_5fevents_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

// clang-format off
#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 7034000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_protos_2fperfetto_2ftrace_2fandroid_2fpixel_5fmodem_5fevents_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_protos_2fperfetto_2ftrace_2fandroid_2fpixel_5fmodem_5fevents_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_protos_2fperfetto_2ftrace_2fandroid_2fpixel_5fmodem_5fevents_2eproto;
}  // extern "C"
namespace perfetto {
namespace protos {
class PixelModemEvents;
struct PixelModemEventsDefaultTypeInternal;
extern PixelModemEventsDefaultTypeInternal _PixelModemEvents_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull PixelModemEvents_class_data_;
class PixelModemTokenDatabase;
struct PixelModemTokenDatabaseDefaultTypeInternal;
extern PixelModemTokenDatabaseDefaultTypeInternal _PixelModemTokenDatabase_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull PixelModemTokenDatabase_class_data_;
}  // namespace protos
}  // namespace perfetto
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace perfetto {
namespace protos {

// ===================================================================


// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED PixelModemTokenDatabase final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:perfetto.protos.PixelModemTokenDatabase) */ {
 public:
  inline PixelModemTokenDatabase() : PixelModemTokenDatabase(nullptr) {}
  ~PixelModemTokenDatabase() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PixelModemTokenDatabase* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PixelModemTokenDatabase));
  }
#endif

  template <typename = void>
  explicit constexpr PixelModemTokenDatabase(::google::protobuf::internal::ConstantInitialized);

  inline PixelModemTokenDatabase(const PixelModemTokenDatabase& from) : PixelModemTokenDatabase(nullptr, from) {}
  inline PixelModemTokenDatabase(PixelModemTokenDatabase&& from) noexcept
      : PixelModemTokenDatabase(nullptr, ::std::move(from)) {}
  inline PixelModemTokenDatabase& operator=(const PixelModemTokenDatabase& from) {
    CopyFrom(from);
    return *this;
  }
  inline PixelModemTokenDatabase& operator=(PixelModemTokenDatabase&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const PixelModemTokenDatabase& default_instance() {
    return *reinterpret_cast<const PixelModemTokenDatabase*>(
        &_PixelModemTokenDatabase_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(PixelModemTokenDatabase& a, PixelModemTokenDatabase& b) { a.Swap(&b); }
  inline void Swap(PixelModemTokenDatabase* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PixelModemTokenDatabase* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] PixelModemTokenDatabase* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PixelModemTokenDatabase>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PixelModemTokenDatabase& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PixelModemTokenDatabase& from) { PixelModemTokenDatabase::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PixelModemTokenDatabase* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "perfetto.protos.PixelModemTokenDatabase"; }

  explicit PixelModemTokenDatabase(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  PixelModemTokenDatabase(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PixelModemTokenDatabase& from);
  PixelModemTokenDatabase(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, PixelModemTokenDatabase&& from) noexcept
      : PixelModemTokenDatabase(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kDatabaseFieldNumber = 1,
  };
  // optional bytes database = 1;
  [[nodiscard]] bool has_database()
      const;
  void clear_database() ;
  [[nodiscard]] const ::std::string& database() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_database(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_database();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_database();
  void set_allocated_database(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_database() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_database(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_database();

  public:
  // @@protoc_insertion_point(class_scope:perfetto.protos.PixelModemTokenDatabase)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const PixelModemTokenDatabase& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr database_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_protos_2fperfetto_2ftrace_2fandroid_2fpixel_5fmodem_5fevents_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull PixelModemTokenDatabase_class_data_;
// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED PixelModemEvents final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:perfetto.protos.PixelModemEvents) */ {
 public:
  inline PixelModemEvents() : PixelModemEvents(nullptr) {}
  ~PixelModemEvents() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PixelModemEvents* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PixelModemEvents));
  }
#endif

  template <typename = void>
  explicit constexpr PixelModemEvents(::google::protobuf::internal::ConstantInitialized);

  inline PixelModemEvents(const PixelModemEvents& from) : PixelModemEvents(nullptr, from) {}
  inline PixelModemEvents(PixelModemEvents&& from) noexcept
      : PixelModemEvents(nullptr, ::std::move(from)) {}
  inline PixelModemEvents& operator=(const PixelModemEvents& from) {
    CopyFrom(from);
    return *this;
  }
  inline PixelModemEvents& operator=(PixelModemEvents&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const PixelModemEvents& default_instance() {
    return *reinterpret_cast<const PixelModemEvents*>(
        &_PixelModemEvents_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(PixelModemEvents& a, PixelModemEvents& b) { a.Swap(&b); }
  inline void Swap(PixelModemEvents* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PixelModemEvents* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] PixelModemEvents* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PixelModemEvents>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PixelModemEvents& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PixelModemEvents& from) { PixelModemEvents::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PixelModemEvents* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "perfetto.protos.PixelModemEvents"; }

  explicit PixelModemEvents(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  PixelModemEvents(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PixelModemEvents& from);
  PixelModemEvents(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, PixelModemEvents&& from) noexcept
      : PixelModemEvents(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kEventsFieldNumber = 1,
    kEventTimeNanosFieldNumber = 2,
  };
  // repeated bytes events = 1;
  [[nodiscard]] int events_size()
      const;
  private:
  int _internal_events_size() const;

  public:
  void clear_events() ;
  [[nodiscard]] const ::std::string& events(int index) const;
  ::std::string* PROTOBUF_NONNULL mutable_events(int index);
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_events(int index, Arg_&& value, Args_... args);
  ::std::string* PROTOBUF_NONNULL add_events();
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void add_events(Arg_&& value, Args_... args);
  [[nodiscard]] const ::google::protobuf::RepeatedPtrField<::std::string>&
  events() const;
  [[nodiscard]] ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
  mutable_events();

  private:
  const ::google::protobuf::RepeatedPtrField<::std::string>& _internal_events() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL _internal_mutable_events();

  public:
  // repeated uint64 event_time_nanos = 2;
  [[nodiscard]] int event_time_nanos_size()
      const;
  private:
  int _internal_event_time_nanos_size() const;

  public:
  void clear_event_time_nanos() ;
  [[nodiscard]] ::uint64_t event_time_nanos(int index) const;
  void set_event_time_nanos(int index, ::uint64_t value);
  void add_event_time_nanos(::uint64_t value);
  [[nodiscard]] const ::google::protobuf::RepeatedField<::uint64_t>& event_time_nanos() const;
  ::google::protobuf::RepeatedField<::uint64_t>* PROTOBUF_NONNULL mutable_event_time_nanos();

  private:
  const ::google::protobuf::RepeatedField<::uint64_t>& _internal_event_time_nanos() const;
  ::google::protobuf::RepeatedField<::uint64_t>* PROTOBUF_NONNULL _internal_mutable_event_time_nanos();

  public:
  // @@protoc_insertion_point(class_scope:perfetto.protos.PixelModemEvents)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const PixelModemEvents& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField<::std::string> events_;
    ::google::protobuf::RepeatedField<::uint64_t> event_time_nanos_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_protos_2fperfetto_2ftrace_2fandroid_2fpixel_5fmodem_5fevents_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull PixelModemEvents_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// PixelModemEvents

// repeated bytes events = 1;
inline int PixelModemEvents::_internal_events_size() const {
  return _internal_events().size();
}
inline int PixelModemEvents::events_size() const {
  return _internal_events_size();
}
inline void PixelModemEvents::clear_events() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.events_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::std::string* PROTOBUF_NONNULL PixelModemEvents::add_events()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::std::string* _s =
      _internal_mutable_events()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add_mutable:perfetto.protos.PixelModemEvents.events)
  return _s;
}
inline const ::std::string& PixelModemEvents::events(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:perfetto.protos.PixelModemEvents.events)
  return _internal_events().Get(index);
}
inline ::std::string* PROTOBUF_NONNULL PixelModemEvents::mutable_events(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:perfetto.protos.PixelModemEvents.events)
  return _internal_mutable_events()->Mutable(index);
}
template <typename Arg_, typename... Args_>
inline void PixelModemEvents::set_events(int index, Arg_&& value, Args_... args) {
  ::google::protobuf::internal::AssignToString(*_internal_mutable_events()->Mutable(index), ::std::forward<Arg_>(value),
                        args... , ::google::protobuf::internal::BytesTag{});
  // @@protoc_insertion_point(field_set:perfetto.protos.PixelModemEvents.events)
}
template <typename Arg_, typename... Args_>
inline void PixelModemEvents::add_events(Arg_&& value, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::google::protobuf::internal::AddToRepeatedPtrField(
      ::google::protobuf::MessageLite::internal_visibility(), GetArena(),
      *_internal_mutable_events(), ::std::forward<Arg_>(value),
      args... , ::google::protobuf::internal::BytesTag{});
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:perfetto.protos.PixelModemEvents.events)
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>& PixelModemEvents::events()
    const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:perfetto.protos.PixelModemEvents.events)
  return _internal_events();
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
PixelModemEvents::mutable_events() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:perfetto.protos.PixelModemEvents.events)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_events();
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>&
PixelModemEvents::_internal_events() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.events_;
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
PixelModemEvents::_internal_mutable_events() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.events_;
}

// repeated uint64 event_time_nanos = 2;
inline int PixelModemEvents::_internal_event_time_nanos_size() const {
  return _internal_event_time_nanos().size();
}
inline int PixelModemEvents::event_time_nanos_size() const {
  return _internal_event_time_nanos_size();
}
inline void PixelModemEvents::clear_event_time_nanos() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.event_time_nanos_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::uint64_t PixelModemEvents::event_time_nanos(int index) const {
  // @@protoc_insertion_point(field_get:perfetto.protos.PixelModemEvents.event_time_nanos)
  return _internal_event_time_nanos().Get(index);
}
inline void PixelModemEvents::set_event_time_nanos(int index, ::uint64_t value) {
  _internal_mutable_event_time_nanos()->Set(index, value);
  // @@protoc_insertion_point(field_set:perfetto.protos.PixelModemEvents.event_time_nanos)
}
inline void PixelModemEvents::add_event_time_nanos(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_event_time_nanos()->InternalAddWithArena(
      internal_visibility(), GetArena(), value);
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_add:perfetto.protos.PixelModemEvents.event_time_nanos)
}
inline const ::google::protobuf::RepeatedField<::uint64_t>& PixelModemEvents::event_time_nanos() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:perfetto.protos.PixelModemEvents.event_time_nanos)
  return _internal_event_time_nanos();
}
inline ::google::protobuf::RepeatedField<::uint64_t>* PROTOBUF_NONNULL PixelModemEvents::mutable_event_time_nanos()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_mutable_list:perfetto.protos.PixelModemEvents.event_time_nanos)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_event_time_nanos();
}
inline const ::google::protobuf::RepeatedField<::uint64_t>&
PixelModemEvents::_internal_event_time_nanos() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.event_time_nanos_;
}
inline ::google::protobuf::RepeatedField<::uint64_t>* PROTOBUF_NONNULL
PixelModemEvents::_internal_mutable_event_time_nanos() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.event_time_nanos_;
}

// -------------------------------------------------------------------

// PixelModemTokenDatabase

// optional bytes database = 1;
inline bool PixelModemTokenDatabase::has_database() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  return value;
}
inline void PixelModemTokenDatabase::clear_database() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.database_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& PixelModemTokenDatabase::database() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:perfetto.protos.PixelModemTokenDatabase.database)
  return _internal_database();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void PixelModemTokenDatabase::set_database(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.database_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:perfetto.protos.PixelModemTokenDatabase.database)
}
inline ::std::string* PROTOBUF_NONNULL PixelModemTokenDatabase::mutable_database()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_database();
  // @@protoc_insertion_point(field_mutable:perfetto.protos.PixelModemTokenDatabase.database)
  return _s;
}
inline const ::std::string& PixelModemTokenDatabase::_internal_database() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.database_.Get();
}
inline void PixelModemTokenDatabase::_internal_set_database(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.database_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL PixelModemTokenDatabase::_internal_mutable_database() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.database_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE PixelModemTokenDatabase::release_database() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:perfetto.protos.PixelModemTokenDatabase.database)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.database_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.database_.Set("", GetArena());
  }
  return released;
}
inline void PixelModemTokenDatabase::set_allocated_database(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.database_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.database_.IsDefault()) {
    _impl_.database_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:perfetto.protos.PixelModemTokenDatabase.database)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace protos
}  // namespace perfetto


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"
// clang-format on

#endif  // protos_2fperfetto_2ftrace_2fandroid_2fpixel_5fmodem_5fevents_2eproto_2epb_2eh
