// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protos/perfetto/trace/android/winscope.proto
// Protobuf C++ Version: 7.34.0

#include "protos/perfetto/trace/android/winscope.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/internal_visibility.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace perfetto {
namespace protos {

inline constexpr WinscopeTraceData::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        layers_snapshot_{nullptr},
        transactions_{nullptr},
        shell_transition_{nullptr},
        protolog_message_{nullptr},
        winscope_extensions_{nullptr},
        viewcapture_{nullptr},
        android_input_event_{nullptr} {}

template <typename>
constexpr WinscopeTraceData::WinscopeTraceData(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(WinscopeTraceData_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
struct WinscopeTraceDataDefaultTypeInternal {
  constexpr WinscopeTraceDataDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~WinscopeTraceDataDefaultTypeInternal() {}
  union {
    WinscopeTraceData _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 WinscopeTraceDataDefaultTypeInternal _WinscopeTraceData_default_instance_;
}  // namespace protos
}  // namespace perfetto
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_protos_2fperfetto_2ftrace_2fandroid_2fwinscope_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_protos_2fperfetto_2ftrace_2fandroid_2fwinscope_2eproto = nullptr;
const ::uint32_t
    TableStruct_protos_2fperfetto_2ftrace_2fandroid_2fwinscope_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::perfetto::protos::WinscopeTraceData, _impl_._has_bits_),
        10, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::perfetto::protos::WinscopeTraceData, _impl_.layers_snapshot_),
        PROTOBUF_FIELD_OFFSET(::perfetto::protos::WinscopeTraceData, _impl_.transactions_),
        PROTOBUF_FIELD_OFFSET(::perfetto::protos::WinscopeTraceData, _impl_.shell_transition_),
        PROTOBUF_FIELD_OFFSET(::perfetto::protos::WinscopeTraceData, _impl_.protolog_message_),
        PROTOBUF_FIELD_OFFSET(::perfetto::protos::WinscopeTraceData, _impl_.winscope_extensions_),
        PROTOBUF_FIELD_OFFSET(::perfetto::protos::WinscopeTraceData, _impl_.viewcapture_),
        PROTOBUF_FIELD_OFFSET(::perfetto::protos::WinscopeTraceData, _impl_.android_input_event_),
        0,
        1,
        2,
        3,
        4,
        5,
        6,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::perfetto::protos::WinscopeTraceData)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::perfetto::protos::_WinscopeTraceData_default_instance_._instance,
};
const char descriptor_table_protodef_protos_2fperfetto_2ftrace_2fandroid_2fwinscope_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n,protos/perfetto/trace/android/winscope"
    ".proto\022\017perfetto.protos\0327protos/perfetto"
    "/trace/android/android_input_event.proto"
    "\032,protos/perfetto/trace/android/protolog"
    ".proto\0324protos/perfetto/trace/android/sh"
    "ell_transition.proto\0329protos/perfetto/tr"
    "ace/android/surfaceflinger_layers.proto\032"
    "\?protos/perfetto/trace/android/surfacefl"
    "inger_transactions.proto\032/protos/perfett"
    "o/trace/android/viewcapture.proto\032<proto"
    "s/perfetto/trace/android/winscope_extens"
    "ions_impl.proto\"\302\003\n\021WinscopeTraceData\022=\n"
    "\017layers_snapshot\030\001 \001(\0132$.perfetto.protos"
    ".LayersSnapshotProto\022<\n\014transactions\030\002 \001"
    "(\0132&.perfetto.protos.TransactionTraceEnt"
    "ry\022:\n\020shell_transition\030\003 \001(\0132 .perfetto."
    "protos.ShellTransition\022:\n\020protolog_messa"
    "ge\030\004 \001(\0132 .perfetto.protos.ProtoLogMessa"
    "ge\022D\n\023winscope_extensions\030\005 \001(\0132\'.perfet"
    "to.protos.WinscopeExtensionsImpl\0221\n\013view"
    "capture\030\006 \001(\0132\034.perfetto.protos.ViewCapt"
    "ure\022\?\n\023android_input_event\030\007 \001(\0132\".perfe"
    "tto.protos.AndroidInputEvent"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_protos_2fperfetto_2ftrace_2fandroid_2fwinscope_2eproto_deps[7] = {
        &::descriptor_table_protos_2fperfetto_2ftrace_2fandroid_2fandroid_5finput_5fevent_2eproto,
        &::descriptor_table_protos_2fperfetto_2ftrace_2fandroid_2fprotolog_2eproto,
        &::descriptor_table_protos_2fperfetto_2ftrace_2fandroid_2fshell_5ftransition_2eproto,
        &::descriptor_table_protos_2fperfetto_2ftrace_2fandroid_2fsurfaceflinger_5flayers_2eproto,
        &::descriptor_table_protos_2fperfetto_2ftrace_2fandroid_2fsurfaceflinger_5ftransactions_2eproto,
        &::descriptor_table_protos_2fperfetto_2ftrace_2fandroid_2fviewcapture_2eproto,
        &::descriptor_table_protos_2fperfetto_2ftrace_2fandroid_2fwinscope_5fextensions_5fimpl_2eproto,
};
static ::absl::once_flag descriptor_table_protos_2fperfetto_2ftrace_2fandroid_2fwinscope_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_protos_2fperfetto_2ftrace_2fandroid_2fwinscope_2eproto = {
    false,
    false,
    908,
    descriptor_table_protodef_protos_2fperfetto_2ftrace_2fandroid_2fwinscope_2eproto,
    "protos/perfetto/trace/android/winscope.proto",
    &descriptor_table_protos_2fperfetto_2ftrace_2fandroid_2fwinscope_2eproto_once,
    descriptor_table_protos_2fperfetto_2ftrace_2fandroid_2fwinscope_2eproto_deps,
    7,
    1,
    schemas,
    file_default_instances,
    TableStruct_protos_2fperfetto_2ftrace_2fandroid_2fwinscope_2eproto::offsets,
    file_level_enum_descriptors_protos_2fperfetto_2ftrace_2fandroid_2fwinscope_2eproto,
    file_level_service_descriptors_protos_2fperfetto_2ftrace_2fandroid_2fwinscope_2eproto,
};
namespace perfetto {
namespace protos {
// ===================================================================

class WinscopeTraceData::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<WinscopeTraceData>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(WinscopeTraceData, _impl_._has_bits_);
};

void WinscopeTraceData::clear_layers_snapshot() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.layers_snapshot_ != nullptr) _impl_.layers_snapshot_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
void WinscopeTraceData::clear_transactions() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.transactions_ != nullptr) _impl_.transactions_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
void WinscopeTraceData::clear_shell_transition() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.shell_transition_ != nullptr) _impl_.shell_transition_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
void WinscopeTraceData::clear_protolog_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.protolog_message_ != nullptr) _impl_.protolog_message_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
void WinscopeTraceData::clear_winscope_extensions() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.winscope_extensions_ != nullptr) _impl_.winscope_extensions_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
void WinscopeTraceData::clear_viewcapture() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.viewcapture_ != nullptr) _impl_.viewcapture_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000020U);
}
void WinscopeTraceData::clear_android_input_event() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.android_input_event_ != nullptr) _impl_.android_input_event_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000040U);
}
WinscopeTraceData::WinscopeTraceData(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, WinscopeTraceData_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:perfetto.protos.WinscopeTraceData)
}
PROTOBUF_NDEBUG_INLINE WinscopeTraceData::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::perfetto::protos::WinscopeTraceData& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

WinscopeTraceData::WinscopeTraceData(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const WinscopeTraceData& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, WinscopeTraceData_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  WinscopeTraceData* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.layers_snapshot_ = (CheckHasBit(cached_has_bits, 0x00000001U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.layers_snapshot_)
                : nullptr;
  _impl_.transactions_ = (CheckHasBit(cached_has_bits, 0x00000002U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.transactions_)
                : nullptr;
  _impl_.shell_transition_ = (CheckHasBit(cached_has_bits, 0x00000004U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.shell_transition_)
                : nullptr;
  _impl_.protolog_message_ = (CheckHasBit(cached_has_bits, 0x00000008U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.protolog_message_)
                : nullptr;
  _impl_.winscope_extensions_ = (CheckHasBit(cached_has_bits, 0x00000010U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.winscope_extensions_)
                : nullptr;
  _impl_.viewcapture_ = (CheckHasBit(cached_has_bits, 0x00000020U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.viewcapture_)
                : nullptr;
  _impl_.android_input_event_ = (CheckHasBit(cached_has_bits, 0x00000040U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.android_input_event_)
                : nullptr;

  // @@protoc_insertion_point(copy_constructor:perfetto.protos.WinscopeTraceData)
}
PROTOBUF_NDEBUG_INLINE WinscopeTraceData::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void WinscopeTraceData::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, layers_snapshot_),
           0,
           offsetof(Impl_, android_input_event_) -
               offsetof(Impl_, layers_snapshot_) +
               sizeof(Impl_::android_input_event_));
}
WinscopeTraceData::~WinscopeTraceData() {
  // @@protoc_insertion_point(destructor:perfetto.protos.WinscopeTraceData)
  SharedDtor(*this);
}
inline void WinscopeTraceData::SharedDtor(MessageLite& self) {
  WinscopeTraceData& this_ = static_cast<WinscopeTraceData&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.layers_snapshot_;
  delete this_._impl_.transactions_;
  delete this_._impl_.shell_transition_;
  delete this_._impl_.protolog_message_;
  delete this_._impl_.winscope_extensions_;
  delete this_._impl_.viewcapture_;
  delete this_._impl_.android_input_event_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL WinscopeTraceData::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) WinscopeTraceData(arena);
}
constexpr auto WinscopeTraceData::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(WinscopeTraceData),
                                            alignof(WinscopeTraceData));
}
constexpr auto WinscopeTraceData::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_WinscopeTraceData_default_instance_._instance,
          &_table_.header,
          nullptr,  // IsInitialized
          &WinscopeTraceData::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<WinscopeTraceData>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &WinscopeTraceData::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<WinscopeTraceData>(), &WinscopeTraceData::ByteSizeLong,
              &WinscopeTraceData::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(WinscopeTraceData, _impl_._cached_size_),
          false,
      },
      &WinscopeTraceData::kDescriptorMethods,
      &descriptor_table_protos_2fperfetto_2ftrace_2fandroid_2fwinscope_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull WinscopeTraceData_class_data_ =
        WinscopeTraceData::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
WinscopeTraceData::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&WinscopeTraceData_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(WinscopeTraceData_class_data_.tc_table);
  return WinscopeTraceData_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 7, 7, 0, 2>
WinscopeTraceData::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(WinscopeTraceData, _impl_._has_bits_),
    0, // no _extensions_
    7, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967168,  // skipmap
    offsetof(decltype(_table_), field_entries),
    7,  // num_field_entries
    7,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    WinscopeTraceData_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::perfetto::protos::WinscopeTraceData>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // optional .perfetto.protos.LayersSnapshotProto layers_snapshot = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(WinscopeTraceData, _impl_.layers_snapshot_)}},
    // optional .perfetto.protos.TransactionTraceEntry transactions = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 1, 1,
      PROTOBUF_FIELD_OFFSET(WinscopeTraceData, _impl_.transactions_)}},
    // optional .perfetto.protos.ShellTransition shell_transition = 3;
    {::_pbi::TcParser::FastMtS1,
     {26, 2, 2,
      PROTOBUF_FIELD_OFFSET(WinscopeTraceData, _impl_.shell_transition_)}},
    // optional .perfetto.protos.ProtoLogMessage protolog_message = 4;
    {::_pbi::TcParser::FastMtS1,
     {34, 3, 3,
      PROTOBUF_FIELD_OFFSET(WinscopeTraceData, _impl_.protolog_message_)}},
    // optional .perfetto.protos.WinscopeExtensionsImpl winscope_extensions = 5;
    {::_pbi::TcParser::FastMtS1,
     {42, 4, 4,
      PROTOBUF_FIELD_OFFSET(WinscopeTraceData, _impl_.winscope_extensions_)}},
    // optional .perfetto.protos.ViewCapture viewcapture = 6;
    {::_pbi::TcParser::FastMtS1,
     {50, 5, 5,
      PROTOBUF_FIELD_OFFSET(WinscopeTraceData, _impl_.viewcapture_)}},
    // optional .perfetto.protos.AndroidInputEvent android_input_event = 7;
    {::_pbi::TcParser::FastMtS1,
     {58, 6, 6,
      PROTOBUF_FIELD_OFFSET(WinscopeTraceData, _impl_.android_input_event_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional .perfetto.protos.LayersSnapshotProto layers_snapshot = 1;
    {PROTOBUF_FIELD_OFFSET(WinscopeTraceData, _impl_.layers_snapshot_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // optional .perfetto.protos.TransactionTraceEntry transactions = 2;
    {PROTOBUF_FIELD_OFFSET(WinscopeTraceData, _impl_.transactions_), _Internal::kHasBitsOffset + 1, 1, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // optional .perfetto.protos.ShellTransition shell_transition = 3;
    {PROTOBUF_FIELD_OFFSET(WinscopeTraceData, _impl_.shell_transition_), _Internal::kHasBitsOffset + 2, 2, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // optional .perfetto.protos.ProtoLogMessage protolog_message = 4;
    {PROTOBUF_FIELD_OFFSET(WinscopeTraceData, _impl_.protolog_message_), _Internal::kHasBitsOffset + 3, 3, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // optional .perfetto.protos.WinscopeExtensionsImpl winscope_extensions = 5;
    {PROTOBUF_FIELD_OFFSET(WinscopeTraceData, _impl_.winscope_extensions_), _Internal::kHasBitsOffset + 4, 4, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // optional .perfetto.protos.ViewCapture viewcapture = 6;
    {PROTOBUF_FIELD_OFFSET(WinscopeTraceData, _impl_.viewcapture_), _Internal::kHasBitsOffset + 5, 5, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // optional .perfetto.protos.AndroidInputEvent android_input_event = 7;
    {PROTOBUF_FIELD_OFFSET(WinscopeTraceData, _impl_.android_input_event_), _Internal::kHasBitsOffset + 6, 6, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::perfetto::protos::LayersSnapshotProto>()},
      {::_pbi::TcParser::GetTable<::perfetto::protos::TransactionTraceEntry>()},
      {::_pbi::TcParser::GetTable<::perfetto::protos::ShellTransition>()},
      {::_pbi::TcParser::GetTable<::perfetto::protos::ProtoLogMessage>()},
      {::_pbi::TcParser::GetTable<::perfetto::protos::WinscopeExtensionsImpl>()},
      {::_pbi::TcParser::GetTable<::perfetto::protos::ViewCapture>()},
      {::_pbi::TcParser::GetTable<::perfetto::protos::AndroidInputEvent>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void WinscopeTraceData::Clear() {
// @@protoc_insertion_point(message_clear_start:perfetto.protos.WinscopeTraceData)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000007fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      ABSL_DCHECK(_impl_.layers_snapshot_ != nullptr);
      _impl_.layers_snapshot_->Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      ABSL_DCHECK(_impl_.transactions_ != nullptr);
      _impl_.transactions_->Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      ABSL_DCHECK(_impl_.shell_transition_ != nullptr);
      _impl_.shell_transition_->Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      ABSL_DCHECK(_impl_.protolog_message_ != nullptr);
      _impl_.protolog_message_->Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      ABSL_DCHECK(_impl_.winscope_extensions_ != nullptr);
      _impl_.winscope_extensions_->Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      ABSL_DCHECK(_impl_.viewcapture_ != nullptr);
      _impl_.viewcapture_->Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      ABSL_DCHECK(_impl_.android_input_event_ != nullptr);
      _impl_.android_input_event_->Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL WinscopeTraceData::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const WinscopeTraceData& this_ = static_cast<const WinscopeTraceData&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL WinscopeTraceData::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const WinscopeTraceData& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:perfetto.protos.WinscopeTraceData)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional .perfetto.protos.LayersSnapshotProto layers_snapshot = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        1, *this_._impl_.layers_snapshot_, this_._impl_.layers_snapshot_->GetCachedSize(), target,
        stream);
  }

  // optional .perfetto.protos.TransactionTraceEntry transactions = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        2, *this_._impl_.transactions_, this_._impl_.transactions_->GetCachedSize(), target,
        stream);
  }

  // optional .perfetto.protos.ShellTransition shell_transition = 3;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        3, *this_._impl_.shell_transition_, this_._impl_.shell_transition_->GetCachedSize(), target,
        stream);
  }

  // optional .perfetto.protos.ProtoLogMessage protolog_message = 4;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        4, *this_._impl_.protolog_message_, this_._impl_.protolog_message_->GetCachedSize(), target,
        stream);
  }

  // optional .perfetto.protos.WinscopeExtensionsImpl winscope_extensions = 5;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        5, *this_._impl_.winscope_extensions_, this_._impl_.winscope_extensions_->GetCachedSize(), target,
        stream);
  }

  // optional .perfetto.protos.ViewCapture viewcapture = 6;
  if (CheckHasBit(cached_has_bits, 0x00000020U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        6, *this_._impl_.viewcapture_, this_._impl_.viewcapture_->GetCachedSize(), target,
        stream);
  }

  // optional .perfetto.protos.AndroidInputEvent android_input_event = 7;
  if (CheckHasBit(cached_has_bits, 0x00000040U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        7, *this_._impl_.android_input_event_, this_._impl_.android_input_event_->GetCachedSize(), target,
        stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:perfetto.protos.WinscopeTraceData)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t WinscopeTraceData::ByteSizeLong(const MessageLite& base) {
  const WinscopeTraceData& this_ = static_cast<const WinscopeTraceData&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t WinscopeTraceData::ByteSizeLong() const {
  const WinscopeTraceData& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:perfetto.protos.WinscopeTraceData)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000007fU)) {
    // optional .perfetto.protos.LayersSnapshotProto layers_snapshot = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.layers_snapshot_);
    }
    // optional .perfetto.protos.TransactionTraceEntry transactions = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.transactions_);
    }
    // optional .perfetto.protos.ShellTransition shell_transition = 3;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.shell_transition_);
    }
    // optional .perfetto.protos.ProtoLogMessage protolog_message = 4;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.protolog_message_);
    }
    // optional .perfetto.protos.WinscopeExtensionsImpl winscope_extensions = 5;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.winscope_extensions_);
    }
    // optional .perfetto.protos.ViewCapture viewcapture = 6;
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.viewcapture_);
    }
    // optional .perfetto.protos.AndroidInputEvent android_input_event = 7;
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.android_input_event_);
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void WinscopeTraceData::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<WinscopeTraceData*>(&to_msg);
  auto& from = static_cast<const WinscopeTraceData&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:perfetto.protos.WinscopeTraceData)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000007fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      ABSL_DCHECK(from._impl_.layers_snapshot_ != nullptr);
      if (_this->_impl_.layers_snapshot_ == nullptr) {
        _this->_impl_.layers_snapshot_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.layers_snapshot_);
      } else {
        _this->_impl_.layers_snapshot_->MergeFrom(*from._impl_.layers_snapshot_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      ABSL_DCHECK(from._impl_.transactions_ != nullptr);
      if (_this->_impl_.transactions_ == nullptr) {
        _this->_impl_.transactions_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.transactions_);
      } else {
        _this->_impl_.transactions_->MergeFrom(*from._impl_.transactions_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      ABSL_DCHECK(from._impl_.shell_transition_ != nullptr);
      if (_this->_impl_.shell_transition_ == nullptr) {
        _this->_impl_.shell_transition_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.shell_transition_);
      } else {
        _this->_impl_.shell_transition_->MergeFrom(*from._impl_.shell_transition_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      ABSL_DCHECK(from._impl_.protolog_message_ != nullptr);
      if (_this->_impl_.protolog_message_ == nullptr) {
        _this->_impl_.protolog_message_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.protolog_message_);
      } else {
        _this->_impl_.protolog_message_->MergeFrom(*from._impl_.protolog_message_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      ABSL_DCHECK(from._impl_.winscope_extensions_ != nullptr);
      if (_this->_impl_.winscope_extensions_ == nullptr) {
        _this->_impl_.winscope_extensions_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.winscope_extensions_);
      } else {
        _this->_impl_.winscope_extensions_->MergeFrom(*from._impl_.winscope_extensions_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      ABSL_DCHECK(from._impl_.viewcapture_ != nullptr);
      if (_this->_impl_.viewcapture_ == nullptr) {
        _this->_impl_.viewcapture_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.viewcapture_);
      } else {
        _this->_impl_.viewcapture_->MergeFrom(*from._impl_.viewcapture_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      ABSL_DCHECK(from._impl_.android_input_event_ != nullptr);
      if (_this->_impl_.android_input_event_ == nullptr) {
        _this->_impl_.android_input_event_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.android_input_event_);
      } else {
        _this->_impl_.android_input_event_->MergeFrom(*from._impl_.android_input_event_);
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void WinscopeTraceData::CopyFrom(const WinscopeTraceData& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:perfetto.protos.WinscopeTraceData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void WinscopeTraceData::InternalSwap(WinscopeTraceData* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(WinscopeTraceData, _impl_.android_input_event_)
      + sizeof(WinscopeTraceData::_impl_.android_input_event_)
      - PROTOBUF_FIELD_OFFSET(WinscopeTraceData, _impl_.layers_snapshot_)>(
          reinterpret_cast<char*>(&_impl_.layers_snapshot_),
          reinterpret_cast<char*>(&other->_impl_.layers_snapshot_));
}

::google::protobuf::Metadata WinscopeTraceData::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace protos
}  // namespace perfetto
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_protos_2fperfetto_2ftrace_2fandroid_2fwinscope_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
