#ifndef KOTLIN_TRACER_SRC_MAIN_CPP_UTILS_POINTERVALIDATION_H_
#define KOTLIN_TRACER_SRC_MAIN_CPP_UTILS_POINTERVALIDATION_H_

#include <cstdint>

extern bool is_valid(uint64_t address);
#endif //KOTLIN_TRACER_SRC_MAIN_CPP_UTILS_POINTERVALIDATION_H_
